/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.api


import java.util.*
import jakarta.persistence.*

import com.harbormaster.entity.*;

//-----------------------------------------------------------
// Command definitions
//-----------------------------------------------------------

// Organization Commands
data class CreateOrganizationCommand(
    @Id var organizationId: UUID? = null,
    var name: String? = null,
    var legalName: String? = null,
    var registrationCountry: String? = null,
    var website: String? = null
)

data class UpdateOrganizationCommand(
    @Id var organizationId: UUID? = null,
    var name: String? = null,
    var legalName: String? = null,
    var registrationCountry: String? = null,
    var website: String? = null,
    var departments:  Set<Department>? = null,
    var locations:  Set<Location>? = null,
    var jobFamilies:  Set<JobFamily>? = null,
    var benefitPlans:  Set<BenefitPlan>? = null,
    var costCenters:  Set<CostCenter>? = null,
    var payrollCalendars:  Set<PayrollCalendar>? = null
)

data class DeleteOrganizationCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignDepartmentsToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDepartmentsFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignLocationsToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveLocationsFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignJobFamiliesToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveJobFamiliesFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignBenefitPlansToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveBenefitPlansFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignCostCentersToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCostCentersFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignPayrollCalendarsToOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePayrollCalendarsFromOrganizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Department Commands
data class CreateDepartmentCommand(
    @Id var departmentId: UUID? = null,
    var name: String? = null,
    var code: String? = null
)

data class UpdateDepartmentCommand(
    @Id var departmentId: UUID? = null,
    var name: String? = null,
    var code: String? = null,
    var organization: Organization? = null,
    var manager: Employee? = null,
    var positions:  Set<Position>? = null,
    var employees:  Set<Employee>? = null,
    var costCenter: CostCenter? = null
)

data class DeleteDepartmentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignManagerToDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignManagerFromDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCostCenterToDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCostCenterFromDepartmentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignPositionsToDepartmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePositionsFromDepartmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEmployeesToDepartmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEmployeesFromDepartmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Location Commands
data class CreateLocationCommand(
    @Id var locationId: UUID? = null,
    var name: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    var timezone: String? = null
)

data class UpdateLocationCommand(
    @Id var locationId: UUID? = null,
    var name: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    var timezone: String? = null,
    var organization: Organization? = null,
    var departments:  Set<Department>? = null,
    var positions:  Set<Position>? = null,
    var employees:  Set<Employee>? = null
)

data class DeleteLocationCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToLocationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromLocationCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDepartmentsToLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDepartmentsFromLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignPositionsToLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePositionsFromLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEmployeesToLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEmployeesFromLocationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// CostCenter Commands
data class CreateCostCenterCommand(
    @Id var costCenterId: UUID? = null,
    var code: String? = null,
    var name: String? = null
)

data class UpdateCostCenterCommand(
    @Id var costCenterId: UUID? = null,
    var code: String? = null,
    var name: String? = null,
    var organization: Organization? = null,
    var departments:  Set<Department>? = null,
    var positions:  Set<Position>? = null,
    var employees:  Set<Employee>? = null
)

data class DeleteCostCenterCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToCostCenterCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromCostCenterCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDepartmentsToCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDepartmentsFromCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignPositionsToCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePositionsFromCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEmployeesToCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEmployeesFromCostCenterCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// JobFamily Commands
data class CreateJobFamilyCommand(
    @Id var jobFamilyId: UUID? = null,
    var name: String? = null,
    var description: String? = null
)

data class UpdateJobFamilyCommand(
    @Id var jobFamilyId: UUID? = null,
    var name: String? = null,
    var description: String? = null,
    var organization: Organization? = null,
    var jobProfiles:  Set<JobProfile>? = null
)

data class DeleteJobFamilyCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToJobFamilyCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromJobFamilyCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignJobProfilesToJobFamilyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveJobProfilesFromJobFamilyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// JobProfile Commands
data class CreateJobProfileCommand(
    @Id var jobProfileId: UUID? = null,
    var title: String? = null,
    var jobCode: String? = null,
    @Enumerated(EnumType.STRING) var jobLevel: JobLevel? = null,
    @Enumerated(EnumType.STRING) var exemptStatus: ExemptStatus? = null
)

data class UpdateJobProfileCommand(
    @Id var jobProfileId: UUID? = null,
    var title: String? = null,
    var jobCode: String? = null,
    var jobFamily: JobFamily? = null,
    var competencies:  Set<Competency>? = null,
    var trainingRecommendations:  Set<TrainingCourse>? = null,
    var positions:  Set<Position>? = null,
    @Enumerated(EnumType.STRING) var jobLevel: JobLevel? = null,
    @Enumerated(EnumType.STRING) var exemptStatus: ExemptStatus? = null
)

data class DeleteJobProfileCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignJobFamilyToJobProfileCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignJobFamilyFromJobProfileCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignCompetenciesToJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCompetenciesFromJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignTrainingRecommendationsToJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveTrainingRecommendationsFromJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignPositionsToJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePositionsFromJobProfileCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Competency Commands
data class CreateCompetencyCommand(
    @Id var competencyId: UUID? = null,
    var name: String? = null,
    var category: String? = null
)

data class UpdateCompetencyCommand(
    @Id var competencyId: UUID? = null,
    var name: String? = null,
    var category: String? = null,
    var jobProfiles:  Set<JobProfile>? = null,
    var competencyRatings:  Set<CompetencyRating>? = null
)

data class DeleteCompetencyCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignJobProfilesToCompetencyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveJobProfilesFromCompetencyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignCompetencyRatingsToCompetencyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCompetencyRatingsFromCompetencyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Position Commands
data class CreatePositionCommand(
    @Id var positionId: UUID? = null,
    var positionCode: String? = null,
    var fte: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var status: PositionStatus? = null,
    @Enumerated(EnumType.STRING) var workLocationType: WorkLocationType? = null
)

data class UpdatePositionCommand(
    @Id var positionId: UUID? = null,
    var positionCode: String? = null,
    var fte: java.math.BigDecimal? = null,
    var department: Department? = null,
    var jobProfile: JobProfile? = null,
    var costCenter: CostCenter? = null,
    var location: Location? = null,
    var managerPosition: Position? = null,
    var directReports:  Set<Position>? = null,
    var assignments:  Set<EmploymentAssignment>? = null,
    @Enumerated(EnumType.STRING) var status: PositionStatus? = null,
    @Enumerated(EnumType.STRING) var workLocationType: WorkLocationType? = null
)

data class DeletePositionCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignDepartmentToPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignDepartmentFromPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignJobProfileToPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignJobProfileFromPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCostCenterToPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCostCenterFromPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignLocationToPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignLocationFromPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignManagerPositionToPositionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignManagerPositionFromPositionCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDirectReportsToPositionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDirectReportsFromPositionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignAssignmentsToPositionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveAssignmentsFromPositionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Employee Commands
data class CreateEmployeeCommand(
    @Id var employeeId: UUID? = null,
    var employeeNumber: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "firstName", column = Column(name = "name_firstName")),
      AttributeOverride( name = "lastName", column = Column(name = "name_lastName")),
      AttributeOverride( name = "middleName", column = Column(name = "name_middleName")),
      AttributeOverride( name = "preferredName", column = Column(name = "name_preferredName"))
    )
    var name: PersonName? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "workEmail_value"))
    )
    var workEmail: Email? = null,
         @AttributeOverrides(
      AttributeOverride( name = "countryCode", column = Column(name = "workPhone_countryCode")),
      AttributeOverride( name = "number", column = Column(name = "workPhone_number")),
      AttributeOverride( name = "extension", column = Column(name = "workPhone_extension"))
    )
    var workPhone: PhoneNumber? = null,
    var dateOfHire:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "country", column = Column(name = "nationalId_country")),
      AttributeOverride( name = "idNumber", column = Column(name = "nationalId_idNumber")),
      AttributeOverride( name = "type", column = Column(name = "nationalId_type"))
    )
    var nationalId: NationalID? = null,
    @Enumerated(EnumType.STRING) var status: EmploymentStatus? = null
)

data class UpdateEmployeeCommand(
    @Id var employeeId: UUID? = null,
    var employeeNumber: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "firstName", column = Column(name = "name_firstName")),
      AttributeOverride( name = "lastName", column = Column(name = "name_lastName")),
      AttributeOverride( name = "middleName", column = Column(name = "name_middleName")),
      AttributeOverride( name = "preferredName", column = Column(name = "name_preferredName"))
    )
    var name: PersonName? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "workEmail_value"))
    )
    var workEmail: Email? = null,
         @AttributeOverrides(
      AttributeOverride( name = "countryCode", column = Column(name = "workPhone_countryCode")),
      AttributeOverride( name = "number", column = Column(name = "workPhone_number")),
      AttributeOverride( name = "extension", column = Column(name = "workPhone_extension"))
    )
    var workPhone: PhoneNumber? = null,
    var dateOfHire:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "country", column = Column(name = "nationalId_country")),
      AttributeOverride( name = "idNumber", column = Column(name = "nationalId_idNumber")),
      AttributeOverride( name = "type", column = Column(name = "nationalId_type"))
    )
    var nationalId: NationalID? = null,
    var manager: Employee? = null,
    var directReports:  Set<Employee>? = null,
    var department: Department? = null,
    var primaryLocation: Location? = null,
    var costCenter: CostCenter? = null,
    var employmentAssignments:  Set<EmploymentAssignment>? = null,
    var contracts:  Set<EmploymentContract>? = null,
    var benefitEnrollments:  Set<BenefitEnrollment>? = null,
    var timesheets:  Set<Timesheet>? = null,
    var leaveRequests:  Set<LeaveRequest>? = null,
    var performanceReviews:  Set<PerformanceReview>? = null,
    var trainingEnrollments:  Set<TrainingEnrollment>? = null,
    var workAuthorizations:  Set<WorkAuthorization>? = null,
    @Enumerated(EnumType.STRING) var status: EmploymentStatus? = null
)

data class DeleteEmployeeCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignManagerToEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignManagerFromEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignDepartmentToEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignDepartmentFromEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignPrimaryLocationToEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPrimaryLocationFromEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCostCenterToEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCostCenterFromEmployeeCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDirectReportsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDirectReportsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEmploymentAssignmentsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEmploymentAssignmentsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignContractsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveContractsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignBenefitEnrollmentsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveBenefitEnrollmentsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignTimesheetsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveTimesheetsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignLeaveRequestsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveLeaveRequestsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignPerformanceReviewsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePerformanceReviewsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignTrainingEnrollmentsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveTrainingEnrollmentsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignWorkAuthorizationsToEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveWorkAuthorizationsFromEmployeeCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// EmploymentAssignment Commands
data class CreateEmploymentAssignmentCommand(
    @Id var employmentAssignmentId: UUID? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var primary: Boolean? = null,
    @Enumerated(EnumType.STRING) var assignmentType: AssignmentType? = null,
    @Enumerated(EnumType.STRING) var status: AssignmentStatus? = null
)

data class UpdateEmploymentAssignmentCommand(
    @Id var employmentAssignmentId: UUID? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var primary: Boolean? = null,
    var employee: Employee? = null,
    var position: Position? = null,
    var supervisor: Employee? = null,
    @Enumerated(EnumType.STRING) var assignmentType: AssignmentType? = null,
    @Enumerated(EnumType.STRING) var status: AssignmentStatus? = null
)

data class DeleteEmploymentAssignmentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignPositionToEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPositionFromEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignSupervisorToEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignSupervisorFromEmploymentAssignmentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// EmploymentContract Commands
data class CreateEmploymentContractCommand(
    @Id var employmentContractId: UUID? = null,
    var contractNumber: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var workHoursPerWeek: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var employmentType: EmploymentType? = null,
    @Enumerated(EnumType.STRING) var status: ContractStatus? = null,
    @Enumerated(EnumType.STRING) var payFrequency: PayFrequency? = null
)

data class UpdateEmploymentContractCommand(
    @Id var employmentContractId: UUID? = null,
    var contractNumber: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var workHoursPerWeek: java.math.BigDecimal? = null,
    var employee: Employee? = null,
    var compensationPackage: CompensationPackage? = null,
    var workSchedule: WorkSchedule? = null,
    var location: Location? = null,
    var payrollCalendar: PayrollCalendar? = null,
    @Enumerated(EnumType.STRING) var employmentType: EmploymentType? = null,
    @Enumerated(EnumType.STRING) var status: ContractStatus? = null,
    @Enumerated(EnumType.STRING) var payFrequency: PayFrequency? = null
)

data class DeleteEmploymentContractCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCompensationPackageToEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCompensationPackageFromEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignWorkScheduleToEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignWorkScheduleFromEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignLocationToEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignLocationFromEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignPayrollCalendarToEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPayrollCalendarFromEmploymentContractCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// WorkSchedule Commands
data class CreateWorkScheduleCommand(
    @Id var workScheduleId: UUID? = null,
    var name: String? = null,
    var standardHoursPerWeek: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var scheduleType: ScheduleType? = null
)

data class UpdateWorkScheduleCommand(
    @Id var workScheduleId: UUID? = null,
    var name: String? = null,
    var standardHoursPerWeek: java.math.BigDecimal? = null,
    var contracts:  Set<EmploymentContract>? = null,
    var shifts:  Set<WorkShift>? = null,
    var exceptions:  Set<ScheduleException>? = null,
    @Enumerated(EnumType.STRING) var scheduleType: ScheduleType? = null
)

data class DeleteWorkScheduleCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignContractsToWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveContractsFromWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignShiftsToWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveShiftsFromWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignExceptionsToWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveExceptionsFromWorkScheduleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// WorkShift Commands
data class CreateWorkShiftCommand(
    @Id var workShiftId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "hour", column = Column(name = "startTime_hour")),
      AttributeOverride( name = "minute", column = Column(name = "startTime_minute"))
    )
    var startTime: LocalTime? = null,
         @AttributeOverrides(
      AttributeOverride( name = "hour", column = Column(name = "endTime_hour")),
      AttributeOverride( name = "minute", column = Column(name = "endTime_minute"))
    )
    var endTime: LocalTime? = null,
    var breakMinutes: Int? = null,
    @Enumerated(EnumType.STRING) var dayOfWeek_: DayOfWeek_? = null
)

data class UpdateWorkShiftCommand(
    @Id var workShiftId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "hour", column = Column(name = "startTime_hour")),
      AttributeOverride( name = "minute", column = Column(name = "startTime_minute"))
    )
    var startTime: LocalTime? = null,
         @AttributeOverrides(
      AttributeOverride( name = "hour", column = Column(name = "endTime_hour")),
      AttributeOverride( name = "minute", column = Column(name = "endTime_minute"))
    )
    var endTime: LocalTime? = null,
    var breakMinutes: Int? = null,
    var workSchedule: WorkSchedule? = null,
    @Enumerated(EnumType.STRING) var dayOfWeek_: DayOfWeek_? = null
)

data class DeleteWorkShiftCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignWorkScheduleToWorkShiftCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignWorkScheduleFromWorkShiftCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// ScheduleException Commands
data class CreateScheduleExceptionCommand(
    @Id var scheduleExceptionId: UUID? = null,
    var date:  Date? = null,
    var reason: String? = null,
    var hours: java.math.BigDecimal? = null
)

data class UpdateScheduleExceptionCommand(
    @Id var scheduleExceptionId: UUID? = null,
    var date:  Date? = null,
    var reason: String? = null,
    var hours: java.math.BigDecimal? = null,
    var workSchedule: WorkSchedule? = null,
    var employee: Employee? = null
)

data class DeleteScheduleExceptionCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignWorkScheduleToScheduleExceptionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignWorkScheduleFromScheduleExceptionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToScheduleExceptionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromScheduleExceptionCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// CompensationPackage Commands
data class CreateCompensationPackageCommand(
    @Id var compensationPackageId: UUID? = null,
    var effectiveFrom:  Date? = null,
    var effectiveTo:  Date? = null,
    var currency: String? = null
)

data class UpdateCompensationPackageCommand(
    @Id var compensationPackageId: UUID? = null,
    var effectiveFrom:  Date? = null,
    var effectiveTo:  Date? = null,
    var currency: String? = null,
    var contract: EmploymentContract? = null,
    var salaryComponents:  Set<SalaryComponent>? = null,
    var bonusPlans:  Set<BonusPlan>? = null,
    var equityGrants:  Set<EquityGrant>? = null
)

data class DeleteCompensationPackageCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignContractToCompensationPackageCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignContractFromCompensationPackageCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignSalaryComponentsToCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveSalaryComponentsFromCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignBonusPlansToCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveBonusPlansFromCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEquityGrantsToCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEquityGrantsFromCompensationPackageCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// SalaryComponent Commands
data class CreateSalaryComponentCommand(
    @Id var salaryComponentId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var recurring: Boolean? = null,
    @Enumerated(EnumType.STRING) var componentType: SalaryComponentType? = null
)

data class UpdateSalaryComponentCommand(
    @Id var salaryComponentId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var recurring: Boolean? = null,
    var compensationPackage: CompensationPackage? = null,
    @Enumerated(EnumType.STRING) var componentType: SalaryComponentType? = null
)

data class DeleteSalaryComponentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCompensationPackageToSalaryComponentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCompensationPackageFromSalaryComponentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// BonusPlan Commands
data class CreateBonusPlanCommand(
    @Id var bonusPlanId: UUID? = null,
    var name: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "targetPercentage_value"))
    )
    var targetPercentage: Percentage? = null
)

data class UpdateBonusPlanCommand(
    @Id var bonusPlanId: UUID? = null,
    var name: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "targetPercentage_value"))
    )
    var targetPercentage: Percentage? = null,
    var compensationPackages:  Set<CompensationPackage>? = null
)

data class DeleteBonusPlanCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignCompensationPackagesToBonusPlanCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCompensationPackagesFromBonusPlanCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// EquityGrant Commands
data class CreateEquityGrantCommand(
    @Id var equityGrantId: UUID? = null,
    var grantId: String? = null,
    var grantedUnits: Int? = null,
    var vestingStart:  Date? = null,
    @Enumerated(EnumType.STRING) var grantType: EquityType? = null
)

data class UpdateEquityGrantCommand(
    @Id var equityGrantId: UUID? = null,
    var grantId: String? = null,
    var grantedUnits: Int? = null,
    var vestingStart:  Date? = null,
    var compensationPackage: CompensationPackage? = null,
    @Enumerated(EnumType.STRING) var grantType: EquityType? = null
)

data class DeleteEquityGrantCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCompensationPackageToEquityGrantCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCompensationPackageFromEquityGrantCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// BenefitPlan Commands
data class CreateBenefitPlanCommand(
    @Id var benefitPlanId: UUID? = null,
    var name: String? = null,
    var providerName: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "employeeContributionRate_value"))
    )
    var employeeContributionRate: Percentage? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "employerContributionRate_value"))
    )
    var employerContributionRate: Percentage? = null,
    var eligibilityRules: String? = null,
    @Enumerated(EnumType.STRING) var benefitType: BenefitType? = null
)

data class UpdateBenefitPlanCommand(
    @Id var benefitPlanId: UUID? = null,
    var name: String? = null,
    var providerName: String? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "employeeContributionRate_value"))
    )
    var employeeContributionRate: Percentage? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "employerContributionRate_value"))
    )
    var employerContributionRate: Percentage? = null,
    var eligibilityRules: String? = null,
    var organization: Organization? = null,
    var enrollments:  Set<BenefitEnrollment>? = null,
    @Enumerated(EnumType.STRING) var benefitType: BenefitType? = null
)

data class DeleteBenefitPlanCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToBenefitPlanCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromBenefitPlanCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignEnrollmentsToBenefitPlanCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEnrollmentsFromBenefitPlanCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// BenefitEnrollment Commands
data class CreateBenefitEnrollmentCommand(
    @Id var benefitEnrollmentId: UUID? = null,
    var enrollmentId: String? = null,
    var effectiveFrom:  Date? = null,
    var effectiveTo:  Date? = null,
    @Enumerated(EnumType.STRING) var status: BenefitEnrollmentStatus? = null,
    @Enumerated(EnumType.STRING) var coverageLevel: CoverageLevel? = null
)

data class UpdateBenefitEnrollmentCommand(
    @Id var benefitEnrollmentId: UUID? = null,
    var enrollmentId: String? = null,
    var effectiveFrom:  Date? = null,
    var effectiveTo:  Date? = null,
    var benefitPlan: BenefitPlan? = null,
    var employee: Employee? = null,
    var dependents:  Set<Dependent>? = null,
    @Enumerated(EnumType.STRING) var status: BenefitEnrollmentStatus? = null,
    @Enumerated(EnumType.STRING) var coverageLevel: CoverageLevel? = null
)

data class DeleteBenefitEnrollmentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignBenefitPlanToBenefitEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignBenefitPlanFromBenefitEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToBenefitEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromBenefitEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDependentsToBenefitEnrollmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDependentsFromBenefitEnrollmentCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Dependent Commands
data class CreateDependentCommand(
    @Id var dependentId: UUID? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var birthDate:  Date? = null,
    @Enumerated(EnumType.STRING) var relationship: DependentRelationship? = null
)

data class UpdateDependentCommand(
    @Id var dependentId: UUID? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var birthDate:  Date? = null,
    var benefitEnrollment: BenefitEnrollment? = null,
    var employee: Employee? = null,
    @Enumerated(EnumType.STRING) var relationship: DependentRelationship? = null
)

data class DeleteDependentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignBenefitEnrollmentToDependentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignBenefitEnrollmentFromDependentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToDependentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromDependentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// PayrollCalendar Commands
data class CreatePayrollCalendarCommand(
    @Id var payrollCalendarId: UUID? = null,
    var name: String? = null,
    var country: String? = null,
    @Enumerated(EnumType.STRING) var payFrequency: PayFrequency? = null
)

data class UpdatePayrollCalendarCommand(
    @Id var payrollCalendarId: UUID? = null,
    var name: String? = null,
    var country: String? = null,
    var organization: Organization? = null,
    var payrollRuns:  Set<PayrollRun>? = null,
    var employees:  Set<Employee>? = null,
    @Enumerated(EnumType.STRING) var payFrequency: PayFrequency? = null
)

data class DeletePayrollCalendarCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToPayrollCalendarCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromPayrollCalendarCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignPayrollRunsToPayrollCalendarCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePayrollRunsFromPayrollCalendarCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEmployeesToPayrollCalendarCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEmployeesFromPayrollCalendarCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// PayrollRun Commands
data class CreatePayrollRunCommand(
    @Id var payrollRunId: UUID? = null,
    var runNumber: String? = null,
    var periodStart:  Date? = null,
    var periodEnd:  Date? = null,
    var paymentDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: PayrollStatus? = null
)

data class UpdatePayrollRunCommand(
    @Id var payrollRunId: UUID? = null,
    var runNumber: String? = null,
    var periodStart:  Date? = null,
    var periodEnd:  Date? = null,
    var paymentDate:  Date? = null,
    var payrollCalendar: PayrollCalendar? = null,
    var payrollItems:  Set<PayrollItem>? = null,
    @Enumerated(EnumType.STRING) var status: PayrollStatus? = null
)

data class DeletePayrollRunCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignPayrollCalendarToPayrollRunCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPayrollCalendarFromPayrollRunCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignPayrollItemsToPayrollRunCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePayrollItemsFromPayrollRunCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// PayrollItem Commands
data class CreatePayrollItemCommand(
    @Id var payrollItemId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var taxable: Boolean? = null,
    @Enumerated(EnumType.STRING) var itemType: PayrollItemType? = null
)

data class UpdatePayrollItemCommand(
    @Id var payrollItemId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var taxable: Boolean? = null,
    var payrollRun: PayrollRun? = null,
    var employee: Employee? = null,
    @Enumerated(EnumType.STRING) var itemType: PayrollItemType? = null
)

data class DeletePayrollItemCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignPayrollRunToPayrollItemCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPayrollRunFromPayrollItemCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToPayrollItemCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromPayrollItemCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// TaxWithholding Commands
data class CreateTaxWithholdingCommand(
    @Id var taxWithholdingId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "taxId_value")),
      AttributeOverride( name = "country", column = Column(name = "taxId_country"))
    )
    var taxId: TaxId? = null,
    var allowances: Int? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "additionalAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "additionalAmount_currency"))
    )
    var additionalAmount: Money? = null,
    @Enumerated(EnumType.STRING) var filingStatus: FilingStatus? = null
)

data class UpdateTaxWithholdingCommand(
    @Id var taxWithholdingId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "taxId_value")),
      AttributeOverride( name = "country", column = Column(name = "taxId_country"))
    )
    var taxId: TaxId? = null,
    var allowances: Int? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "additionalAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "additionalAmount_currency"))
    )
    var additionalAmount: Money? = null,
    var employee: Employee? = null,
    @Enumerated(EnumType.STRING) var filingStatus: FilingStatus? = null
)

data class DeleteTaxWithholdingCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToTaxWithholdingCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromTaxWithholdingCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// PaymentMethod Commands
data class CreatePaymentMethodCommand(
    @Id var paymentMethodId: UUID? = null,
    var preferred: Boolean? = null,
    @Enumerated(EnumType.STRING) var methodType: PaymentMethodType? = null
)

data class UpdatePaymentMethodCommand(
    @Id var paymentMethodId: UUID? = null,
    var preferred: Boolean? = null,
    var employee: Employee? = null,
    var bankAccount: BankAccount? = null,
    @Enumerated(EnumType.STRING) var methodType: PaymentMethodType? = null
)

data class DeletePaymentMethodCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToPaymentMethodCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromPaymentMethodCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignBankAccountToPaymentMethodCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignBankAccountFromPaymentMethodCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Timesheet Commands
data class CreateTimesheetCommand(
    @Id var timesheetId: UUID? = null,
    var periodStart:  Date? = null,
    var periodEnd:  Date? = null,
    var submissionDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: TimesheetStatus? = null
)

data class UpdateTimesheetCommand(
    @Id var timesheetId: UUID? = null,
    var periodStart:  Date? = null,
    var periodEnd:  Date? = null,
    var submissionDate:  Date? = null,
    var employee: Employee? = null,
    var timeEntries:  Set<TimeEntry>? = null,
    var approvals:  Set<Approval>? = null,
    @Enumerated(EnumType.STRING) var status: TimesheetStatus? = null
)

data class DeleteTimesheetCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToTimesheetCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromTimesheetCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignTimeEntriesToTimesheetCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveTimeEntriesFromTimesheetCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignApprovalsToTimesheetCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveApprovalsFromTimesheetCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// TimeEntry Commands
data class CreateTimeEntryCommand(
    @Id var timeEntryId: UUID? = null,
    var entryDate:  Date? = null,
    var hoursWorked: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var entryType: TimeEntryType? = null
)

data class UpdateTimeEntryCommand(
    @Id var timeEntryId: UUID? = null,
    var entryDate:  Date? = null,
    var hoursWorked: java.math.BigDecimal? = null,
    var timesheet: Timesheet? = null,
    var employee: Employee? = null,
    var costCenter: CostCenter? = null,
    @Enumerated(EnumType.STRING) var entryType: TimeEntryType? = null
)

data class DeleteTimeEntryCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignTimesheetToTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignTimesheetFromTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCostCenterToTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCostCenterFromTimeEntryCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Approval Commands
data class CreateApprovalCommand(
    @Id var approvalId: UUID? = null,
    var approverComment: String? = null,
    var actionDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: ApprovalStatus? = null
)

data class UpdateApprovalCommand(
    @Id var approvalId: UUID? = null,
    var approverComment: String? = null,
    var actionDate:  Date? = null,
    var approver: Employee? = null,
    var timesheet: Timesheet? = null,
    var leaveRequest: LeaveRequest? = null,
    @Enumerated(EnumType.STRING) var status: ApprovalStatus? = null
)

data class DeleteApprovalCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignApproverToApprovalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignApproverFromApprovalCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignTimesheetToApprovalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignTimesheetFromApprovalCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignLeaveRequestToApprovalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignLeaveRequestFromApprovalCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// LeavePolicy Commands
data class CreateLeavePolicyCommand(
    @Id var leavePolicyId: UUID? = null,
    var name: String? = null,
    var accrualRate: java.math.BigDecimal? = null,
    var carryoverAllowed: Boolean? = null,
    var maxBalance: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var leaveCategory: LeaveCategory? = null,
    @Enumerated(EnumType.STRING) var accrualUnit: AccrualUnit? = null
)

data class UpdateLeavePolicyCommand(
    @Id var leavePolicyId: UUID? = null,
    var name: String? = null,
    var accrualRate: java.math.BigDecimal? = null,
    var carryoverAllowed: Boolean? = null,
    var maxBalance: java.math.BigDecimal? = null,
    var organization: Organization? = null,
    var leaveRequests:  Set<LeaveRequest>? = null,
    @Enumerated(EnumType.STRING) var leaveCategory: LeaveCategory? = null,
    @Enumerated(EnumType.STRING) var accrualUnit: AccrualUnit? = null
)

data class DeleteLeavePolicyCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToLeavePolicyCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromLeavePolicyCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignLeaveRequestsToLeavePolicyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveLeaveRequestsFromLeavePolicyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// LeaveRequest Commands
data class CreateLeaveRequestCommand(
    @Id var leaveRequestId: UUID? = null,
    var requestNumber: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var reason: String? = null,
    var hours: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var status: LeaveStatus? = null
)

data class UpdateLeaveRequestCommand(
    @Id var leaveRequestId: UUID? = null,
    var requestNumber: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var reason: String? = null,
    var hours: java.math.BigDecimal? = null,
    var employee: Employee? = null,
    var leavePolicy: LeavePolicy? = null,
    var approvals:  Set<Approval>? = null,
    @Enumerated(EnumType.STRING) var status: LeaveStatus? = null
)

data class DeleteLeaveRequestCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToLeaveRequestCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromLeaveRequestCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignLeavePolicyToLeaveRequestCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignLeavePolicyFromLeaveRequestCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignApprovalsToLeaveRequestCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveApprovalsFromLeaveRequestCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// PerformanceCycle Commands
data class CreatePerformanceCycleCommand(
    @Id var performanceCycleId: UUID? = null,
    var name: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: CycleStatus? = null
)

data class UpdatePerformanceCycleCommand(
    @Id var performanceCycleId: UUID? = null,
    var name: String? = null,
    var startDate:  Date? = null,
    var endDate:  Date? = null,
    var organization: Organization? = null,
    var reviews:  Set<PerformanceReview>? = null,
    var goals:  Set<Goal>? = null,
    @Enumerated(EnumType.STRING) var status: CycleStatus? = null
)

data class DeletePerformanceCycleCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToPerformanceCycleCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromPerformanceCycleCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignReviewsToPerformanceCycleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveReviewsFromPerformanceCycleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignGoalsToPerformanceCycleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveGoalsFromPerformanceCycleCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Goal Commands
data class CreateGoalCommand(
    @Id var goalId: UUID? = null,
    var title: String? = null,
    var description: String? = null,
    var targetDate:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "weight_value"))
    )
    var weight: Percentage? = null,
    @Enumerated(EnumType.STRING) var status: GoalStatus? = null
)

data class UpdateGoalCommand(
    @Id var goalId: UUID? = null,
    var title: String? = null,
    var description: String? = null,
    var targetDate:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "weight_value"))
    )
    var weight: Percentage? = null,
    var employee: Employee? = null,
    var cycle: PerformanceCycle? = null,
    var parentGoal: Goal? = null,
    var childGoals:  Set<Goal>? = null,
    @Enumerated(EnumType.STRING) var status: GoalStatus? = null
)

data class DeleteGoalCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToGoalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromGoalCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCycleToGoalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCycleFromGoalCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignParentGoalToGoalCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignParentGoalFromGoalCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignChildGoalsToGoalCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveChildGoalsFromGoalCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// PerformanceReview Commands
data class CreatePerformanceReviewCommand(
    @Id var performanceReviewId: UUID? = null,
    var reviewNumber: String? = null,
    var reviewDate:  Date? = null,
    var reviewerComments: String? = null,
    @Enumerated(EnumType.STRING) var rating: PerformanceRating? = null,
    @Enumerated(EnumType.STRING) var status: ReviewStatus? = null
)

data class UpdatePerformanceReviewCommand(
    @Id var performanceReviewId: UUID? = null,
    var reviewNumber: String? = null,
    var reviewDate:  Date? = null,
    var reviewerComments: String? = null,
    var employee: Employee? = null,
    var reviewer: Employee? = null,
    var cycle: PerformanceCycle? = null,
    var competencyRatings:  Set<CompetencyRating>? = null,
    var goals:  Set<Goal>? = null,
    @Enumerated(EnumType.STRING) var rating: PerformanceRating? = null,
    @Enumerated(EnumType.STRING) var status: ReviewStatus? = null
)

data class DeletePerformanceReviewCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignReviewerToPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignReviewerFromPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCycleToPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCycleFromPerformanceReviewCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignCompetencyRatingsToPerformanceReviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCompetencyRatingsFromPerformanceReviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignGoalsToPerformanceReviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveGoalsFromPerformanceReviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// CompetencyRating Commands
data class CreateCompetencyRatingCommand(
    @Id var competencyRatingId: UUID? = null,
    var comment: String? = null,
    @Enumerated(EnumType.STRING) var rating: PerformanceRating? = null
)

data class UpdateCompetencyRatingCommand(
    @Id var competencyRatingId: UUID? = null,
    var comment: String? = null,
    var review: PerformanceReview? = null,
    var competency: Competency? = null,
    @Enumerated(EnumType.STRING) var rating: PerformanceRating? = null
)

data class DeleteCompetencyRatingCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignReviewToCompetencyRatingCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignReviewFromCompetencyRatingCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCompetencyToCompetencyRatingCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCompetencyFromCompetencyRatingCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// TrainingCourse Commands
data class CreateTrainingCourseCommand(
    @Id var trainingCourseId: UUID? = null,
    var code: String? = null,
    var title: String? = null,
    var durationHours: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var deliveryMethod: DeliveryMethod? = null
)

data class UpdateTrainingCourseCommand(
    @Id var trainingCourseId: UUID? = null,
    var code: String? = null,
    var title: String? = null,
    var durationHours: java.math.BigDecimal? = null,
    var prerequisites:  Set<TrainingCourse>? = null,
    var enrollments:  Set<TrainingEnrollment>? = null,
    var jobProfiles:  Set<JobProfile>? = null,
    @Enumerated(EnumType.STRING) var deliveryMethod: DeliveryMethod? = null
)

data class DeleteTrainingCourseCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignPrerequisitesToTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemovePrerequisitesFromTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignEnrollmentsToTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveEnrollmentsFromTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignJobProfilesToTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveJobProfilesFromTrainingCourseCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// TrainingEnrollment Commands
data class CreateTrainingEnrollmentCommand(
    @Id var trainingEnrollmentId: UUID? = null,
    var enrollmentNumber: String? = null,
    var completionDate:  Date? = null,
    var score: java.math.BigDecimal? = null,
    @Enumerated(EnumType.STRING) var status: TrainingStatus? = null
)

data class UpdateTrainingEnrollmentCommand(
    @Id var trainingEnrollmentId: UUID? = null,
    var enrollmentNumber: String? = null,
    var completionDate:  Date? = null,
    var score: java.math.BigDecimal? = null,
    var course: TrainingCourse? = null,
    var employee: Employee? = null,
    var instructor: Employee? = null,
    @Enumerated(EnumType.STRING) var status: TrainingStatus? = null
)

data class DeleteTrainingEnrollmentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCourseToTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCourseFromTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignInstructorToTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignInstructorFromTrainingEnrollmentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Certification Commands
data class CreateCertificationCommand(
    @Id var certificationId: UUID? = null,
    var name: String? = null,
    var issuer: String? = null,
    var validFrom:  Date? = null,
    var validTo:  Date? = null,
    var credentialId: String? = null
)

data class UpdateCertificationCommand(
    @Id var certificationId: UUID? = null,
    var name: String? = null,
    var issuer: String? = null,
    var validFrom:  Date? = null,
    var validTo:  Date? = null,
    var credentialId: String? = null,
    var employee: Employee? = null,
    var course: TrainingCourse? = null
)

data class DeleteCertificationCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToCertificationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromCertificationCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCourseToCertificationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCourseFromCertificationCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// JobRequisition Commands
data class CreateJobRequisitionCommand(
    @Id var jobRequisitionId: UUID? = null,
    var requisitionNumber: String? = null,
    var title: String? = null,
    var openings: Int? = null,
    var targetStartDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: RequisitionStatus? = null,
    @Enumerated(EnumType.STRING) var priority: RequisitionPriority? = null
)

data class UpdateJobRequisitionCommand(
    @Id var jobRequisitionId: UUID? = null,
    var requisitionNumber: String? = null,
    var title: String? = null,
    var openings: Int? = null,
    var targetStartDate:  Date? = null,
    var department: Department? = null,
    var hiringManager: Employee? = null,
    var recruiter: Employee? = null,
    var jobProfile: JobProfile? = null,
    var candidates:  Set<Candidate>? = null,
    var interviews:  Set<Interview>? = null,
    var offers:  Set<Offer>? = null,
    @Enumerated(EnumType.STRING) var status: RequisitionStatus? = null,
    @Enumerated(EnumType.STRING) var priority: RequisitionPriority? = null
)

data class DeleteJobRequisitionCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignDepartmentToJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignDepartmentFromJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignHiringManagerToJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignHiringManagerFromJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignRecruiterToJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRecruiterFromJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignJobProfileToJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignJobProfileFromJobRequisitionCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignCandidatesToJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveCandidatesFromJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignInterviewsToJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveInterviewsFromJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignOffersToJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveOffersFromJobRequisitionCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Candidate Commands
data class CreateCandidateCommand(
    @Id var candidateId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "firstName", column = Column(name = "name_firstName")),
      AttributeOverride( name = "lastName", column = Column(name = "name_lastName")),
      AttributeOverride( name = "middleName", column = Column(name = "name_middleName")),
      AttributeOverride( name = "preferredName", column = Column(name = "name_preferredName"))
    )
    var name: PersonName? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "email_value"))
    )
    var email: Email? = null,
         @AttributeOverrides(
      AttributeOverride( name = "countryCode", column = Column(name = "phone_countryCode")),
      AttributeOverride( name = "number", column = Column(name = "phone_number")),
      AttributeOverride( name = "extension", column = Column(name = "phone_extension"))
    )
    var phone: PhoneNumber? = null,
    @Enumerated(EnumType.STRING) var source: CandidateSource? = null
)

data class UpdateCandidateCommand(
    @Id var candidateId: UUID? = null,
         @AttributeOverrides(
      AttributeOverride( name = "firstName", column = Column(name = "name_firstName")),
      AttributeOverride( name = "lastName", column = Column(name = "name_lastName")),
      AttributeOverride( name = "middleName", column = Column(name = "name_middleName")),
      AttributeOverride( name = "preferredName", column = Column(name = "name_preferredName"))
    )
    var name: PersonName? = null,
         @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "email_value"))
    )
    var email: Email? = null,
         @AttributeOverrides(
      AttributeOverride( name = "countryCode", column = Column(name = "phone_countryCode")),
      AttributeOverride( name = "number", column = Column(name = "phone_number")),
      AttributeOverride( name = "extension", column = Column(name = "phone_extension"))
    )
    var phone: PhoneNumber? = null,
    var applications:  Set<JobApplication>? = null,
    var interviews:  Set<Interview>? = null,
    var offers:  Set<Offer>? = null,
    var documents:  Set<Document>? = null,
    @Enumerated(EnumType.STRING) var source: CandidateSource? = null
)

data class DeleteCandidateCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands
data class AssignApplicationsToCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveApplicationsFromCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignInterviewsToCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveInterviewsFromCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignOffersToCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveOffersFromCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class AssignDocumentsToCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDocumentsFromCandidateCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// JobApplication Commands
data class CreateJobApplicationCommand(
    @Id var jobApplicationId: UUID? = null,
    var applicationNumber: String? = null,
    var appliedDate:  Date? = null,
    var resumeUrl: String? = null,
    @Enumerated(EnumType.STRING) var status: ApplicationStatus? = null
)

data class UpdateJobApplicationCommand(
    @Id var jobApplicationId: UUID? = null,
    var applicationNumber: String? = null,
    var appliedDate:  Date? = null,
    var resumeUrl: String? = null,
    var candidate: Candidate? = null,
    var requisition: JobRequisition? = null,
    var screenings:  Set<Screening>? = null,
    @Enumerated(EnumType.STRING) var status: ApplicationStatus? = null
)

data class DeleteJobApplicationCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCandidateToJobApplicationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCandidateFromJobApplicationCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignRequisitionToJobApplicationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRequisitionFromJobApplicationCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignScreeningsToJobApplicationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveScreeningsFromJobApplicationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Interview Commands
data class CreateInterviewCommand(
    @Id var interviewId: UUID? = null,
    var interviewDate:  Date? = null,
    var feedback: String? = null,
    @Enumerated(EnumType.STRING) var stage: InterviewStage? = null,
    @Enumerated(EnumType.STRING) var result: InterviewResult? = null
)

data class UpdateInterviewCommand(
    @Id var interviewId: UUID? = null,
    var interviewDate:  Date? = null,
    var feedback: String? = null,
    var requisition: JobRequisition? = null,
    var candidate: Candidate? = null,
    var interviewers:  Set<Employee>? = null,
    @Enumerated(EnumType.STRING) var stage: InterviewStage? = null,
    @Enumerated(EnumType.STRING) var result: InterviewResult? = null
)

data class DeleteInterviewCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignRequisitionToInterviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRequisitionFromInterviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCandidateToInterviewCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCandidateFromInterviewCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignInterviewersToInterviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveInterviewersFromInterviewCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// Screening Commands
data class CreateScreeningCommand(
    @Id var screeningId: UUID? = null,
    var name: String? = null,
    var completedDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: BackgroundCheckStatus? = null
)

data class UpdateScreeningCommand(
    @Id var screeningId: UUID? = null,
    var name: String? = null,
    var completedDate:  Date? = null,
    var application: JobApplication? = null,
    @Enumerated(EnumType.STRING) var status: BackgroundCheckStatus? = null
)

data class DeleteScreeningCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignApplicationToScreeningCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignApplicationFromScreeningCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Offer Commands
data class CreateOfferCommand(
    @Id var offerId: UUID? = null,
    var offerNumber: String? = null,
    var proposedStartDate:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "baseSalary_amount")),
      AttributeOverride( name = "currency", column = Column(name = "baseSalary_currency"))
    )
    var baseSalary: Money? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "signOnBonus_amount")),
      AttributeOverride( name = "currency", column = Column(name = "signOnBonus_currency"))
    )
    var signOnBonus: Money? = null,
    @Enumerated(EnumType.STRING) var status: OfferStatus? = null
)

data class UpdateOfferCommand(
    @Id var offerId: UUID? = null,
    var offerNumber: String? = null,
    var proposedStartDate:  Date? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "baseSalary_amount")),
      AttributeOverride( name = "currency", column = Column(name = "baseSalary_currency"))
    )
    var baseSalary: Money? = null,
         @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "signOnBonus_amount")),
      AttributeOverride( name = "currency", column = Column(name = "signOnBonus_currency"))
    )
    var signOnBonus: Money? = null,
    var requisition: JobRequisition? = null,
    var candidate: Candidate? = null,
    var approvedBy: Employee? = null,
    var contract: EmploymentContract? = null,
    @Enumerated(EnumType.STRING) var status: OfferStatus? = null
)

data class DeleteOfferCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignRequisitionToOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRequisitionFromOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignCandidateToOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCandidateFromOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignApprovedByToOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignApprovedByFromOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignContractToOfferCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignContractFromOfferCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// OnboardingTask Commands
data class CreateOnboardingTaskCommand(
    @Id var onboardingTaskId: UUID? = null,
    var taskNumber: String? = null,
    var name: String? = null,
    var dueDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: OnboardingTaskStatus? = null
)

data class UpdateOnboardingTaskCommand(
    @Id var onboardingTaskId: UUID? = null,
    var taskNumber: String? = null,
    var name: String? = null,
    var dueDate:  Date? = null,
    var employee: Employee? = null,
    var assignedTo: Employee? = null,
    var dependencies:  Set<OnboardingTask>? = null,
    var relatedOffer: Offer? = null,
    @Enumerated(EnumType.STRING) var status: OnboardingTaskStatus? = null
)

data class DeleteOnboardingTaskCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignAssignedToToOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignAssignedToFromOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignRelatedOfferToOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRelatedOfferFromOnboardingTaskCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDependenciesToOnboardingTaskCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDependenciesFromOnboardingTaskCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// BackgroundCheck Commands
data class CreateBackgroundCheckCommand(
    @Id var backgroundCheckId: UUID? = null,
    var checkNumber: String? = null,
    var provider: String? = null,
    var completedDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: BackgroundCheckStatus? = null
)

data class UpdateBackgroundCheckCommand(
    @Id var backgroundCheckId: UUID? = null,
    var checkNumber: String? = null,
    var provider: String? = null,
    var completedDate:  Date? = null,
    var candidate: Candidate? = null,
    var requisition: JobRequisition? = null,
    var report: Document? = null,
    @Enumerated(EnumType.STRING) var status: BackgroundCheckStatus? = null
)

data class DeleteBackgroundCheckCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCandidateToBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCandidateFromBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignRequisitionToBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignRequisitionFromBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignReportToBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignReportFromBackgroundCheckCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Document Commands
data class CreateDocumentCommand(
    @Id var documentId: UUID? = null,
    var name: String? = null,
    var fileUrl: String? = null,
    var uploadedDate:  Date? = null,
    @Enumerated(EnumType.STRING) var documentType: DocumentType? = null
)

data class UpdateDocumentCommand(
    @Id var documentId: UUID? = null,
    var name: String? = null,
    var fileUrl: String? = null,
    var uploadedDate:  Date? = null,
    var candidate: Candidate? = null,
    var employee: Employee? = null,
    @Enumerated(EnumType.STRING) var documentType: DocumentType? = null
)

data class DeleteDocumentCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignCandidateToDocumentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignCandidateFromDocumentCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToDocumentCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromDocumentCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Policy Commands
data class CreatePolicyCommand(
    @Id var policyId: UUID? = null,
    var policyNumber: String? = null,
    var name: String? = null,
    var effectiveDate:  Date? = null,
    var description: String? = null
)

data class UpdatePolicyCommand(
    @Id var policyId: UUID? = null,
    var policyNumber: String? = null,
    var name: String? = null,
    var effectiveDate:  Date? = null,
    var description: String? = null,
    var organization: Organization? = null,
    var acknowledgements:  Set<PolicyAcknowledgement>? = null
)

data class DeletePolicyCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignOrganizationToPolicyCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignOrganizationFromPolicyCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignAcknowledgementsToPolicyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveAcknowledgementsFromPolicyCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// PolicyAcknowledgement Commands
data class CreatePolicyAcknowledgementCommand(
    @Id var policyAcknowledgementId: UUID? = null,
    var acknowledgementDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: AcknowledgementStatus? = null
)

data class UpdatePolicyAcknowledgementCommand(
    @Id var policyAcknowledgementId: UUID? = null,
    var acknowledgementDate:  Date? = null,
    var policy: Policy? = null,
    var employee: Employee? = null,
    @Enumerated(EnumType.STRING) var status: AcknowledgementStatus? = null
)

data class DeletePolicyAcknowledgementCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignPolicyToPolicyAcknowledgementCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignPolicyFromPolicyAcknowledgementCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignEmployeeToPolicyAcknowledgementCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromPolicyAcknowledgementCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// Termination Commands
data class CreateTerminationCommand(
    @Id var terminationId: UUID? = null,
    var terminationNumber: String? = null,
    var terminationDate:  Date? = null,
    var notes: String? = null,
    var eligibleForRehire: Boolean? = null,
    @Enumerated(EnumType.STRING) var reason: TerminationReason? = null,
    @Enumerated(EnumType.STRING) var type: TerminationType? = null
)

data class UpdateTerminationCommand(
    @Id var terminationId: UUID? = null,
    var terminationNumber: String? = null,
    var terminationDate:  Date? = null,
    var notes: String? = null,
    var eligibleForRehire: Boolean? = null,
    var employee: Employee? = null,
    var assignment: EmploymentAssignment? = null,
    @Enumerated(EnumType.STRING) var reason: TerminationReason? = null,
    @Enumerated(EnumType.STRING) var type: TerminationType? = null
)

data class DeleteTerminationCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToTerminationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromTerminationCommand(@Id  val parentId: UUID, val childId: UUID )
data class AssignAssignmentToTerminationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignAssignmentFromTerminationCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands


// WorkAuthorization Commands
data class CreateWorkAuthorizationCommand(
    @Id var workAuthorizationId: UUID? = null,
    var country: String? = null,
    var expirationDate:  Date? = null,
    @Enumerated(EnumType.STRING) var status: WorkAuthorizationStatus? = null
)

data class UpdateWorkAuthorizationCommand(
    @Id var workAuthorizationId: UUID? = null,
    var country: String? = null,
    var expirationDate:  Date? = null,
    var employee: Employee? = null,
    var documents:  Set<Document>? = null,
    @Enumerated(EnumType.STRING) var status: WorkAuthorizationStatus? = null
)

data class DeleteWorkAuthorizationCommand(@Id  var id: UUID? = null)

// single association commands
data class AssignEmployeeToWorkAuthorizationCommand(@Id  val parentId: UUID, val childId: UUID )
data class UnAssignEmployeeFromWorkAuthorizationCommand(@Id  val parentId: UUID, val childId: UUID )

// multiple association commands
data class AssignDocumentsToWorkAuthorizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )
data class RemoveDocumentsFromWorkAuthorizationCommand(@Id  val parentId: UUID, val childIds: List<UUID> )


// BankAccount Commands
data class CreateBankAccountCommand(
    @Id var bankAccountId: UUID? = null,
    var accountHolder: String? = null,
    var bankName: String? = null,
    var iban: String? = null,
    var bic: String? = null,
    var accountNumber: String? = null,
    var routingNumber: String? = null
)

data class UpdateBankAccountCommand(
    @Id var bankAccountId: UUID? = null,
    var accountHolder: String? = null,
    var bankName: String? = null,
    var iban: String? = null,
    var bic: String? = null,
    var accountNumber: String? = null,
    var routingNumber: String? = null
)

data class DeleteBankAccountCommand(@Id  var id: UUID? = null)

// single association commands

// multiple association commands




data class IdentifierRequest(
    val id: UUID
)

data class AssociationRequest(
    val parentId: UUID,
    val childId: UUID
)

data class MultipleAssociationRequest(
    val parentId: UUID,
    val childIds: List<UUID>
)