
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>CandidateEntity Projector</h2>
 * <p>
 * The Candidate Entity Projector is responsible for maintaining the read model for
 * Candidate entities. It subscribes to domain events published by the Candidate
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>CandidateRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("candidate-entity-projector")
public class CandidateEntityProjector implements EntityProjector<Candidate>{
		
	// core constructor
	public CandidateEntityProjector(ProjectorRegistry registry,
										CandidateRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Candidate> getEntityClass() {
		return Candidate.class;
	}

    /*
	 * Insert a Candidate
	 * 
     * @param	entity Candidate
     */
    public Candidate create( Candidate entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Candidate
	 * 
     * @param	entity Candidate
     */
    public Candidate update( Candidate entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Candidate
	 * 
     * @param	id		UUID
     */
    public Candidate delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Candidate entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    


    /*
     * Add to the Applications
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Candidate
     */
    public Candidate addToApplications( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignApplicationsToCandidateEvent - " );
	    
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			JobApplication child = registry.project(JobApplication.class, childId);
			parentEntity.getApplications().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Applications
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Candidate
     */
	public Candidate removeFromApplications( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveApplicationsFromCandidateEvent " );
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			JobApplication child = registry.project(JobApplication.class, childId);
			parentEntity.getApplications().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Interviews
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Candidate
     */
    public Candidate addToInterviews( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignInterviewsToCandidateEvent - " );
	    
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Interview child = registry.project(Interview.class, childId);
			parentEntity.getInterviews().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Interviews
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Candidate
     */
	public Candidate removeFromInterviews( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveInterviewsFromCandidateEvent " );
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Interview child = registry.project(Interview.class, childId);
			parentEntity.getInterviews().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Offers
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Candidate
     */
    public Candidate addToOffers( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignOffersToCandidateEvent - " );
	    
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Offer child = registry.project(Offer.class, childId);
			parentEntity.getOffers().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Offers
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Candidate
     */
	public Candidate removeFromOffers( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveOffersFromCandidateEvent " );
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Offer child = registry.project(Offer.class, childId);
			parentEntity.getOffers().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Documents
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Candidate
     */
    public Candidate addToDocuments( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignDocumentsToCandidateEvent - " );
	    
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Document child = registry.project(Document.class, childId);
			parentEntity.getDocuments().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Documents
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Candidate
     */
	public Candidate removeFromDocuments( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveDocumentsFromCandidateEvent " );
	    Candidate parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Document child = registry.project(Document.class, childId);
			parentEntity.getDocuments().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Candidate via an FindCandidateQuery
     * @return 	query	FindCandidateQuery
     */
    @SuppressWarnings("unused")
    public Candidate find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Candidate - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Candidates
     *
     * @param	query	FindAllCandidateQuery 
     * @return 	List<Candidate> 
     */
    @SuppressWarnings("unused")
    public List<Candidate> findAll( FindAllCandidateQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Candidate - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final CandidateRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(CandidateEntityProjector.class.getName());

}
