/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ApprovalValidation</h2>
 * <p>
 * The Approval Validation  handles state validation of a Approval include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateApprovalCommand</li>
 *      <li>UpdateApprovalCommand</li>
 *      <li>DeleteApprovalCommand</li>
 *set( false = false )
  *       <li>AssignApproverToApprovalCommand</li>
 *       <li>UnAssignApproverFromApprovalCommand</li>
  *       <li>AssignTimesheetToApprovalCommand</li>
 *       <li>UnAssignTimesheetFromApprovalCommand</li>
  *       <li>AssignLeaveRequestToApprovalCommand</li>
 *       <li>UnAssignLeaveRequestFromApprovalCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ApprovalValidator {

	/**
	 * default constructor
	 */
	protected ApprovalValidator() {
	}


	/**
	 * handles creation validation for a Approval
	 */
	public void validate( CreateApprovalCommand approval )throws ValidationException {
		if ( approval == null )
			throw new ValidationException( "Approval", "validating CreateApprovalCommand" );
		if ( approval.getApproverComment() == null )
			throw new ValidationException( "Approval", "validating access on getApproverComment" );
		if ( approval.getActionDate() == null )
			throw new ValidationException( "Approval", "validating access on getActionDate" );
	}

	/**
	 * handles update validation for a Approval
	 */
	public void validate( UpdateApprovalCommand approval ) throws ValidationException {
		if ( approval == null )
			throw new ValidationException( "Approval", "validating UpdateApprovalCommand" );
		if ( approval.getApproverComment() == null )
			throw new ValidationException( "Approval", "validating method getApproverComment" );
		if ( approval.getActionDate() == null )
			throw new ValidationException( "Approval", "validating method getActionDate" );
	}

/**
 * handles delete validation for a Approval
 */
	public void validate( DeleteApprovalCommand approval ) throws ValidationException {
		if ( approval == null )
			throw new ValidationException( "Approval", "validating DeleteApprovalCommand" );

		if ( approval.getId() == null )
			throw new ValidationException( "Approval", "validating DeleteApprovalCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Approval
 */
	public void validate( ApprovalFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Approval", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Approval", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Approver validation for a Approval
	 *
	 * @param	command AssignApproverToApprovalCommand
	 */
	public void validate( AssignApproverToApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating AssignApproverToApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on AssignApproverToApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Approver validation for a Approval
	 *
	 * @param	command UnAssignApproverFromApprovalCommand
	 */
	public void validate( UnAssignApproverFromApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating UnAssignApproverFromApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on UnAssignApproverFromApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Timesheet validation for a Approval
	 *
	 * @param	command AssignTimesheetToApprovalCommand
	 */
	public void validate( AssignTimesheetToApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating AssignTimesheetToApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on AssignTimesheetToApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Timesheet validation for a Approval
	 *
	 * @param	command UnAssignTimesheetFromApprovalCommand
	 */
	public void validate( UnAssignTimesheetFromApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating UnAssignTimesheetFromApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on UnAssignTimesheetFromApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign LeaveRequest validation for a Approval
	 *
	 * @param	command AssignLeaveRequestToApprovalCommand
	 */
	public void validate( AssignLeaveRequestToApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating AssignLeaveRequestToApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on AssignLeaveRequestToApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign LeaveRequest validation for a Approval
	 *
	 * @param	command UnAssignLeaveRequestFromApprovalCommand
	 */
	public void validate( UnAssignLeaveRequestFromApprovalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Approval", "validating UnAssignLeaveRequestFromApprovalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Approval", "validating identity on UnAssignLeaveRequestFromApprovalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
