/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>BenefitEnrollmentValidation</h2>
 * <p>
 * The BenefitEnrollment Validation  handles state validation of a BenefitEnrollment include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBenefitEnrollmentCommand</li>
 *      <li>UpdateBenefitEnrollmentCommand</li>
 *      <li>DeleteBenefitEnrollmentCommand</li>
 *set( false = false )
  *       <li>AssignBenefitPlanToBenefitEnrollmentCommand</li>
 *       <li>UnAssignBenefitPlanFromBenefitEnrollmentCommand</li>
  *       <li>AssignEmployeeToBenefitEnrollmentCommand</li>
 *       <li>UnAssignEmployeeFromBenefitEnrollmentCommand</li>
   *       <li>AssignDependentsToBenefitEnrollmentCommand</li>
 *       <li>RemoveDependentsFromBenefitEnrollmentCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class BenefitEnrollmentValidator {

	/**
	 * default constructor
	 */
	protected BenefitEnrollmentValidator() {
	}


	/**
	 * handles creation validation for a BenefitEnrollment
	 */
	public void validate( CreateBenefitEnrollmentCommand benefitEnrollment )throws ValidationException {
		if ( benefitEnrollment == null )
			throw new ValidationException( "BenefitEnrollment", "validating CreateBenefitEnrollmentCommand" );
		if ( benefitEnrollment.getEnrollmentId() == null )
			throw new ValidationException( "BenefitEnrollment", "validating access on getEnrollmentId" );
		if ( benefitEnrollment.getEffectiveFrom() == null )
			throw new ValidationException( "BenefitEnrollment", "validating access on getEffectiveFrom" );
		if ( benefitEnrollment.getEffectiveTo() == null )
			throw new ValidationException( "BenefitEnrollment", "validating access on getEffectiveTo" );
	}

	/**
	 * handles update validation for a BenefitEnrollment
	 */
	public void validate( UpdateBenefitEnrollmentCommand benefitEnrollment ) throws ValidationException {
		if ( benefitEnrollment == null )
			throw new ValidationException( "BenefitEnrollment", "validating UpdateBenefitEnrollmentCommand" );
		if ( benefitEnrollment.getEnrollmentId() == null )
			throw new ValidationException( "BenefitEnrollment", "validating method getEnrollmentId" );
		if ( benefitEnrollment.getEffectiveFrom() == null )
			throw new ValidationException( "BenefitEnrollment", "validating method getEffectiveFrom" );
		if ( benefitEnrollment.getEffectiveTo() == null )
			throw new ValidationException( "BenefitEnrollment", "validating method getEffectiveTo" );
	}

/**
 * handles delete validation for a BenefitEnrollment
 */
	public void validate( DeleteBenefitEnrollmentCommand benefitEnrollment ) throws ValidationException {
		if ( benefitEnrollment == null )
			throw new ValidationException( "BenefitEnrollment", "validating DeleteBenefitEnrollmentCommand" );

		if ( benefitEnrollment.getId() == null )
			throw new ValidationException( "BenefitEnrollment", "validating DeleteBenefitEnrollmentCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a BenefitEnrollment
 */
	public void validate( BenefitEnrollmentFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "BenefitEnrollment", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "BenefitEnrollment", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign BenefitPlan validation for a BenefitEnrollment
	 *
	 * @param	command AssignBenefitPlanToBenefitEnrollmentCommand
	 */
	public void validate( AssignBenefitPlanToBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BenefitEnrollment", "validating AssignBenefitPlanToBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on AssignBenefitPlanToBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign BenefitPlan validation for a BenefitEnrollment
	 *
	 * @param	command UnAssignBenefitPlanFromBenefitEnrollmentCommand
	 */
	public void validate( UnAssignBenefitPlanFromBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BenefitEnrollment", "validating UnAssignBenefitPlanFromBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on UnAssignBenefitPlanFromBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Employee validation for a BenefitEnrollment
	 *
	 * @param	command AssignEmployeeToBenefitEnrollmentCommand
	 */
	public void validate( AssignEmployeeToBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BenefitEnrollment", "validating AssignEmployeeToBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on AssignEmployeeToBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Employee validation for a BenefitEnrollment
	 *
	 * @param	command UnAssignEmployeeFromBenefitEnrollmentCommand
	 */
	public void validate( UnAssignEmployeeFromBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BenefitEnrollment", "validating UnAssignEmployeeFromBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on UnAssignEmployeeFromBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Dependents validation for a BenefitEnrollment
	 *
	 * @param	command AssignDependentsToBenefitEnrollmentCommand
	 */
	public void validate( AssignDependentsToBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BenefitEnrollment", "validating AssignDependentsToBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on AssignDependentsToBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Dependents validation for a BenefitEnrollment
	 *
	 * @param	command RemoveDependentsFromBenefitEnrollmentCommand
	 */
	public void validate( RemoveDependentsFromBenefitEnrollmentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("BenefitEnrollment", "validating RemoveDependentsFromBenefitEnrollmentCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "BenefitEnrollment", "validating identity on RemoveDependentsFromBenefitEnrollmentCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
