/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>CandidateValidation</h2>
 * <p>
 * The Candidate Validation  handles state validation of a Candidate include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCandidateCommand</li>
 *      <li>UpdateCandidateCommand</li>
 *      <li>DeleteCandidateCommand</li>
 *set( false = false )
   *       <li>AssignApplicationsToCandidateCommand</li>
 *       <li>RemoveApplicationsFromCandidateCommand</li>
 *   </ul>
 *
  *       <li>AssignInterviewsToCandidateCommand</li>
 *       <li>RemoveInterviewsFromCandidateCommand</li>
 *   </ul>
 *
  *       <li>AssignOffersToCandidateCommand</li>
 *       <li>RemoveOffersFromCandidateCommand</li>
 *   </ul>
 *
  *       <li>AssignDocumentsToCandidateCommand</li>
 *       <li>RemoveDocumentsFromCandidateCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class CandidateValidator {

	/**
	 * default constructor
	 */
	protected CandidateValidator() {
	}


	/**
	 * handles creation validation for a Candidate
	 */
	public void validate( CreateCandidateCommand candidate )throws ValidationException {
		if ( candidate == null )
			throw new ValidationException( "Candidate", "validating CreateCandidateCommand" );
		if ( candidate.getName() == null )
			throw new ValidationException( "Candidate", "validating access on getName" );
		if ( candidate.getEmail() == null )
			throw new ValidationException( "Candidate", "validating access on getEmail" );
		if ( candidate.getPhone() == null )
			throw new ValidationException( "Candidate", "validating access on getPhone" );
	}

	/**
	 * handles update validation for a Candidate
	 */
	public void validate( UpdateCandidateCommand candidate ) throws ValidationException {
		if ( candidate == null )
			throw new ValidationException( "Candidate", "validating UpdateCandidateCommand" );
		if ( candidate.getName() == null )
			throw new ValidationException( "Candidate", "validating method getName" );
		if ( candidate.getEmail() == null )
			throw new ValidationException( "Candidate", "validating method getEmail" );
		if ( candidate.getPhone() == null )
			throw new ValidationException( "Candidate", "validating method getPhone" );
	}

/**
 * handles delete validation for a Candidate
 */
	public void validate( DeleteCandidateCommand candidate ) throws ValidationException {
		if ( candidate == null )
			throw new ValidationException( "Candidate", "validating DeleteCandidateCommand" );

		if ( candidate.getId() == null )
			throw new ValidationException( "Candidate", "validating DeleteCandidateCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Candidate
 */
	public void validate( CandidateFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Candidate", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Candidate", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Applications validation for a Candidate
	 *
	 * @param	command AssignApplicationsToCandidateCommand
	 */
	public void validate( AssignApplicationsToCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Candidate", "validating AssignApplicationsToCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on AssignApplicationsToCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Applications validation for a Candidate
	 *
	 * @param	command RemoveApplicationsFromCandidateCommand
	 */
	public void validate( RemoveApplicationsFromCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Candidate", "validating RemoveApplicationsFromCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on RemoveApplicationsFromCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Interviews validation for a Candidate
	 *
	 * @param	command AssignInterviewsToCandidateCommand
	 */
	public void validate( AssignInterviewsToCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Candidate", "validating AssignInterviewsToCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on AssignInterviewsToCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Interviews validation for a Candidate
	 *
	 * @param	command RemoveInterviewsFromCandidateCommand
	 */
	public void validate( RemoveInterviewsFromCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Candidate", "validating RemoveInterviewsFromCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on RemoveInterviewsFromCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Offers validation for a Candidate
	 *
	 * @param	command AssignOffersToCandidateCommand
	 */
	public void validate( AssignOffersToCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Candidate", "validating AssignOffersToCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on AssignOffersToCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Offers validation for a Candidate
	 *
	 * @param	command RemoveOffersFromCandidateCommand
	 */
	public void validate( RemoveOffersFromCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Candidate", "validating RemoveOffersFromCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on RemoveOffersFromCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Documents validation for a Candidate
	 *
	 * @param	command AssignDocumentsToCandidateCommand
	 */
	public void validate( AssignDocumentsToCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Candidate", "validating AssignDocumentsToCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on AssignDocumentsToCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Documents validation for a Candidate
	 *
	 * @param	command RemoveDocumentsFromCandidateCommand
	 */
	public void validate( RemoveDocumentsFromCandidateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Candidate", "validating RemoveDocumentsFromCandidateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Candidate", "validating identity on RemoveDocumentsFromCandidateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
