/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>CompensationPackageValidation</h2>
 * <p>
 * The CompensationPackage Validation  handles state validation of a CompensationPackage include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCompensationPackageCommand</li>
 *      <li>UpdateCompensationPackageCommand</li>
 *      <li>DeleteCompensationPackageCommand</li>
 *set( false = false )
  *       <li>AssignContractToCompensationPackageCommand</li>
 *       <li>UnAssignContractFromCompensationPackageCommand</li>
   *       <li>AssignSalaryComponentsToCompensationPackageCommand</li>
 *       <li>RemoveSalaryComponentsFromCompensationPackageCommand</li>
 *   </ul>
 *
  *       <li>AssignBonusPlansToCompensationPackageCommand</li>
 *       <li>RemoveBonusPlansFromCompensationPackageCommand</li>
 *   </ul>
 *
  *       <li>AssignEquityGrantsToCompensationPackageCommand</li>
 *       <li>RemoveEquityGrantsFromCompensationPackageCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class CompensationPackageValidator {

	/**
	 * default constructor
	 */
	protected CompensationPackageValidator() {
	}


	/**
	 * handles creation validation for a CompensationPackage
	 */
	public void validate( CreateCompensationPackageCommand compensationPackage )throws ValidationException {
		if ( compensationPackage == null )
			throw new ValidationException( "CompensationPackage", "validating CreateCompensationPackageCommand" );
		if ( compensationPackage.getEffectiveFrom() == null )
			throw new ValidationException( "CompensationPackage", "validating access on getEffectiveFrom" );
		if ( compensationPackage.getEffectiveTo() == null )
			throw new ValidationException( "CompensationPackage", "validating access on getEffectiveTo" );
		if ( compensationPackage.getCurrency() == null )
			throw new ValidationException( "CompensationPackage", "validating access on getCurrency" );
	}

	/**
	 * handles update validation for a CompensationPackage
	 */
	public void validate( UpdateCompensationPackageCommand compensationPackage ) throws ValidationException {
		if ( compensationPackage == null )
			throw new ValidationException( "CompensationPackage", "validating UpdateCompensationPackageCommand" );
		if ( compensationPackage.getEffectiveFrom() == null )
			throw new ValidationException( "CompensationPackage", "validating method getEffectiveFrom" );
		if ( compensationPackage.getEffectiveTo() == null )
			throw new ValidationException( "CompensationPackage", "validating method getEffectiveTo" );
		if ( compensationPackage.getCurrency() == null )
			throw new ValidationException( "CompensationPackage", "validating method getCurrency" );
	}

/**
 * handles delete validation for a CompensationPackage
 */
	public void validate( DeleteCompensationPackageCommand compensationPackage ) throws ValidationException {
		if ( compensationPackage == null )
			throw new ValidationException( "CompensationPackage", "validating DeleteCompensationPackageCommand" );

		if ( compensationPackage.getId() == null )
			throw new ValidationException( "CompensationPackage", "validating DeleteCompensationPackageCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a CompensationPackage
 */
	public void validate( CompensationPackageFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "CompensationPackage", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "CompensationPackage", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Contract validation for a CompensationPackage
	 *
	 * @param	command AssignContractToCompensationPackageCommand
	 */
	public void validate( AssignContractToCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "CompensationPackage", "validating AssignContractToCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on AssignContractToCompensationPackageCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Contract validation for a CompensationPackage
	 *
	 * @param	command UnAssignContractFromCompensationPackageCommand
	 */
	public void validate( UnAssignContractFromCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "CompensationPackage", "validating UnAssignContractFromCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on UnAssignContractFromCompensationPackageCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to SalaryComponents validation for a CompensationPackage
	 *
	 * @param	command AssignSalaryComponentsToCompensationPackageCommand
	 */
	public void validate( AssignSalaryComponentsToCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "CompensationPackage", "validating AssignSalaryComponentsToCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on AssignSalaryComponentsToCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from SalaryComponents validation for a CompensationPackage
	 *
	 * @param	command RemoveSalaryComponentsFromCompensationPackageCommand
	 */
	public void validate( RemoveSalaryComponentsFromCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("CompensationPackage", "validating RemoveSalaryComponentsFromCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on RemoveSalaryComponentsFromCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to BonusPlans validation for a CompensationPackage
	 *
	 * @param	command AssignBonusPlansToCompensationPackageCommand
	 */
	public void validate( AssignBonusPlansToCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "CompensationPackage", "validating AssignBonusPlansToCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on AssignBonusPlansToCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from BonusPlans validation for a CompensationPackage
	 *
	 * @param	command RemoveBonusPlansFromCompensationPackageCommand
	 */
	public void validate( RemoveBonusPlansFromCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("CompensationPackage", "validating RemoveBonusPlansFromCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on RemoveBonusPlansFromCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to EquityGrants validation for a CompensationPackage
	 *
	 * @param	command AssignEquityGrantsToCompensationPackageCommand
	 */
	public void validate( AssignEquityGrantsToCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "CompensationPackage", "validating AssignEquityGrantsToCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on AssignEquityGrantsToCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from EquityGrants validation for a CompensationPackage
	 *
	 * @param	command RemoveEquityGrantsFromCompensationPackageCommand
	 */
	public void validate( RemoveEquityGrantsFromCompensationPackageCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("CompensationPackage", "validating RemoveEquityGrantsFromCompensationPackageCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "CompensationPackage", "validating identity on RemoveEquityGrantsFromCompensationPackageCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
