/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>GoalValidation</h2>
 * <p>
 * The Goal Validation  handles state validation of a Goal include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateGoalCommand</li>
 *      <li>UpdateGoalCommand</li>
 *      <li>DeleteGoalCommand</li>
 *set( false = false )
  *       <li>AssignEmployeeToGoalCommand</li>
 *       <li>UnAssignEmployeeFromGoalCommand</li>
  *       <li>AssignCycleToGoalCommand</li>
 *       <li>UnAssignCycleFromGoalCommand</li>
  *       <li>AssignParentGoalToGoalCommand</li>
 *       <li>UnAssignParentGoalFromGoalCommand</li>
   *       <li>AssignChildGoalsToGoalCommand</li>
 *       <li>RemoveChildGoalsFromGoalCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class GoalValidator {

	/**
	 * default constructor
	 */
	protected GoalValidator() {
	}


	/**
	 * handles creation validation for a Goal
	 */
	public void validate( CreateGoalCommand goal )throws ValidationException {
		if ( goal == null )
			throw new ValidationException( "Goal", "validating CreateGoalCommand" );
		if ( goal.getTitle() == null )
			throw new ValidationException( "Goal", "validating access on getTitle" );
		if ( goal.getDescription() == null )
			throw new ValidationException( "Goal", "validating access on getDescription" );
		if ( goal.getTargetDate() == null )
			throw new ValidationException( "Goal", "validating access on getTargetDate" );
		if ( goal.getWeight() == null )
			throw new ValidationException( "Goal", "validating access on getWeight" );
	}

	/**
	 * handles update validation for a Goal
	 */
	public void validate( UpdateGoalCommand goal ) throws ValidationException {
		if ( goal == null )
			throw new ValidationException( "Goal", "validating UpdateGoalCommand" );
		if ( goal.getTitle() == null )
			throw new ValidationException( "Goal", "validating method getTitle" );
		if ( goal.getDescription() == null )
			throw new ValidationException( "Goal", "validating method getDescription" );
		if ( goal.getTargetDate() == null )
			throw new ValidationException( "Goal", "validating method getTargetDate" );
		if ( goal.getWeight() == null )
			throw new ValidationException( "Goal", "validating method getWeight" );
	}

/**
 * handles delete validation for a Goal
 */
	public void validate( DeleteGoalCommand goal ) throws ValidationException {
		if ( goal == null )
			throw new ValidationException( "Goal", "validating DeleteGoalCommand" );

		if ( goal.getId() == null )
			throw new ValidationException( "Goal", "validating DeleteGoalCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Goal
 */
	public void validate( GoalFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Goal", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Goal", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Employee validation for a Goal
	 *
	 * @param	command AssignEmployeeToGoalCommand
	 */
	public void validate( AssignEmployeeToGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating AssignEmployeeToGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on AssignEmployeeToGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Employee validation for a Goal
	 *
	 * @param	command UnAssignEmployeeFromGoalCommand
	 */
	public void validate( UnAssignEmployeeFromGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating UnAssignEmployeeFromGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on UnAssignEmployeeFromGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Cycle validation for a Goal
	 *
	 * @param	command AssignCycleToGoalCommand
	 */
	public void validate( AssignCycleToGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating AssignCycleToGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on AssignCycleToGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Cycle validation for a Goal
	 *
	 * @param	command UnAssignCycleFromGoalCommand
	 */
	public void validate( UnAssignCycleFromGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating UnAssignCycleFromGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on UnAssignCycleFromGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign ParentGoal validation for a Goal
	 *
	 * @param	command AssignParentGoalToGoalCommand
	 */
	public void validate( AssignParentGoalToGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating AssignParentGoalToGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on AssignParentGoalToGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign ParentGoal validation for a Goal
	 *
	 * @param	command UnAssignParentGoalFromGoalCommand
	 */
	public void validate( UnAssignParentGoalFromGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating UnAssignParentGoalFromGoalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Goal", "validating identity on UnAssignParentGoalFromGoalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to ChildGoals validation for a Goal
	 *
	 * @param	command AssignChildGoalsToGoalCommand
	 */
	public void validate( AssignChildGoalsToGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Goal", "validating AssignChildGoalsToGoalCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Goal", "validating identity on AssignChildGoalsToGoalCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from ChildGoals validation for a Goal
	 *
	 * @param	command RemoveChildGoalsFromGoalCommand
	 */
	public void validate( RemoveChildGoalsFromGoalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Goal", "validating RemoveChildGoalsFromGoalCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Goal", "validating identity on RemoveChildGoalsFromGoalCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
