/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>InterviewValidation</h2>
 * <p>
 * The Interview Validation  handles state validation of a Interview include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateInterviewCommand</li>
 *      <li>UpdateInterviewCommand</li>
 *      <li>DeleteInterviewCommand</li>
 *set( false = false )
  *       <li>AssignRequisitionToInterviewCommand</li>
 *       <li>UnAssignRequisitionFromInterviewCommand</li>
  *       <li>AssignCandidateToInterviewCommand</li>
 *       <li>UnAssignCandidateFromInterviewCommand</li>
   *       <li>AssignInterviewersToInterviewCommand</li>
 *       <li>RemoveInterviewersFromInterviewCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class InterviewValidator {

	/**
	 * default constructor
	 */
	protected InterviewValidator() {
	}


	/**
	 * handles creation validation for a Interview
	 */
	public void validate( CreateInterviewCommand interview )throws ValidationException {
		if ( interview == null )
			throw new ValidationException( "Interview", "validating CreateInterviewCommand" );
		if ( interview.getInterviewDate() == null )
			throw new ValidationException( "Interview", "validating access on getInterviewDate" );
		if ( interview.getFeedback() == null )
			throw new ValidationException( "Interview", "validating access on getFeedback" );
	}

	/**
	 * handles update validation for a Interview
	 */
	public void validate( UpdateInterviewCommand interview ) throws ValidationException {
		if ( interview == null )
			throw new ValidationException( "Interview", "validating UpdateInterviewCommand" );
		if ( interview.getInterviewDate() == null )
			throw new ValidationException( "Interview", "validating method getInterviewDate" );
		if ( interview.getFeedback() == null )
			throw new ValidationException( "Interview", "validating method getFeedback" );
	}

/**
 * handles delete validation for a Interview
 */
	public void validate( DeleteInterviewCommand interview ) throws ValidationException {
		if ( interview == null )
			throw new ValidationException( "Interview", "validating DeleteInterviewCommand" );

		if ( interview.getId() == null )
			throw new ValidationException( "Interview", "validating DeleteInterviewCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Interview
 */
	public void validate( InterviewFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Interview", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Interview", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Requisition validation for a Interview
	 *
	 * @param	command AssignRequisitionToInterviewCommand
	 */
	public void validate( AssignRequisitionToInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Interview", "validating AssignRequisitionToInterviewCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Interview", "validating identity on AssignRequisitionToInterviewCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Requisition validation for a Interview
	 *
	 * @param	command UnAssignRequisitionFromInterviewCommand
	 */
	public void validate( UnAssignRequisitionFromInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Interview", "validating UnAssignRequisitionFromInterviewCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Interview", "validating identity on UnAssignRequisitionFromInterviewCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Candidate validation for a Interview
	 *
	 * @param	command AssignCandidateToInterviewCommand
	 */
	public void validate( AssignCandidateToInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Interview", "validating AssignCandidateToInterviewCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Interview", "validating identity on AssignCandidateToInterviewCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Candidate validation for a Interview
	 *
	 * @param	command UnAssignCandidateFromInterviewCommand
	 */
	public void validate( UnAssignCandidateFromInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Interview", "validating UnAssignCandidateFromInterviewCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Interview", "validating identity on UnAssignCandidateFromInterviewCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Interviewers validation for a Interview
	 *
	 * @param	command AssignInterviewersToInterviewCommand
	 */
	public void validate( AssignInterviewersToInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Interview", "validating AssignInterviewersToInterviewCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Interview", "validating identity on AssignInterviewersToInterviewCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Interviewers validation for a Interview
	 *
	 * @param	command RemoveInterviewersFromInterviewCommand
	 */
	public void validate( RemoveInterviewersFromInterviewCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Interview", "validating RemoveInterviewersFromInterviewCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Interview", "validating identity on RemoveInterviewersFromInterviewCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
