/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>JobApplicationValidation</h2>
 * <p>
 * The JobApplication Validation  handles state validation of a JobApplication include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateJobApplicationCommand</li>
 *      <li>UpdateJobApplicationCommand</li>
 *      <li>DeleteJobApplicationCommand</li>
 *set( false = false )
  *       <li>AssignCandidateToJobApplicationCommand</li>
 *       <li>UnAssignCandidateFromJobApplicationCommand</li>
  *       <li>AssignRequisitionToJobApplicationCommand</li>
 *       <li>UnAssignRequisitionFromJobApplicationCommand</li>
   *       <li>AssignScreeningsToJobApplicationCommand</li>
 *       <li>RemoveScreeningsFromJobApplicationCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class JobApplicationValidator {

	/**
	 * default constructor
	 */
	protected JobApplicationValidator() {
	}


	/**
	 * handles creation validation for a JobApplication
	 */
	public void validate( CreateJobApplicationCommand jobApplication )throws ValidationException {
		if ( jobApplication == null )
			throw new ValidationException( "JobApplication", "validating CreateJobApplicationCommand" );
		if ( jobApplication.getApplicationNumber() == null )
			throw new ValidationException( "JobApplication", "validating access on getApplicationNumber" );
		if ( jobApplication.getAppliedDate() == null )
			throw new ValidationException( "JobApplication", "validating access on getAppliedDate" );
		if ( jobApplication.getResumeUrl() == null )
			throw new ValidationException( "JobApplication", "validating access on getResumeUrl" );
	}

	/**
	 * handles update validation for a JobApplication
	 */
	public void validate( UpdateJobApplicationCommand jobApplication ) throws ValidationException {
		if ( jobApplication == null )
			throw new ValidationException( "JobApplication", "validating UpdateJobApplicationCommand" );
		if ( jobApplication.getApplicationNumber() == null )
			throw new ValidationException( "JobApplication", "validating method getApplicationNumber" );
		if ( jobApplication.getAppliedDate() == null )
			throw new ValidationException( "JobApplication", "validating method getAppliedDate" );
		if ( jobApplication.getResumeUrl() == null )
			throw new ValidationException( "JobApplication", "validating method getResumeUrl" );
	}

/**
 * handles delete validation for a JobApplication
 */
	public void validate( DeleteJobApplicationCommand jobApplication ) throws ValidationException {
		if ( jobApplication == null )
			throw new ValidationException( "JobApplication", "validating DeleteJobApplicationCommand" );

		if ( jobApplication.getId() == null )
			throw new ValidationException( "JobApplication", "validating DeleteJobApplicationCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a JobApplication
 */
	public void validate( JobApplicationFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "JobApplication", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "JobApplication", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Candidate validation for a JobApplication
	 *
	 * @param	command AssignCandidateToJobApplicationCommand
	 */
	public void validate( AssignCandidateToJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobApplication", "validating AssignCandidateToJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobApplication", "validating identity on AssignCandidateToJobApplicationCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Candidate validation for a JobApplication
	 *
	 * @param	command UnAssignCandidateFromJobApplicationCommand
	 */
	public void validate( UnAssignCandidateFromJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobApplication", "validating UnAssignCandidateFromJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobApplication", "validating identity on UnAssignCandidateFromJobApplicationCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Requisition validation for a JobApplication
	 *
	 * @param	command AssignRequisitionToJobApplicationCommand
	 */
	public void validate( AssignRequisitionToJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobApplication", "validating AssignRequisitionToJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobApplication", "validating identity on AssignRequisitionToJobApplicationCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Requisition validation for a JobApplication
	 *
	 * @param	command UnAssignRequisitionFromJobApplicationCommand
	 */
	public void validate( UnAssignRequisitionFromJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobApplication", "validating UnAssignRequisitionFromJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobApplication", "validating identity on UnAssignRequisitionFromJobApplicationCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Screenings validation for a JobApplication
	 *
	 * @param	command AssignScreeningsToJobApplicationCommand
	 */
	public void validate( AssignScreeningsToJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobApplication", "validating AssignScreeningsToJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobApplication", "validating identity on AssignScreeningsToJobApplicationCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Screenings validation for a JobApplication
	 *
	 * @param	command RemoveScreeningsFromJobApplicationCommand
	 */
	public void validate( RemoveScreeningsFromJobApplicationCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("JobApplication", "validating RemoveScreeningsFromJobApplicationCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobApplication", "validating identity on RemoveScreeningsFromJobApplicationCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
