/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>JobRequisitionValidation</h2>
 * <p>
 * The JobRequisition Validation  handles state validation of a JobRequisition include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateJobRequisitionCommand</li>
 *      <li>UpdateJobRequisitionCommand</li>
 *      <li>DeleteJobRequisitionCommand</li>
 *set( false = false )
  *       <li>AssignDepartmentToJobRequisitionCommand</li>
 *       <li>UnAssignDepartmentFromJobRequisitionCommand</li>
  *       <li>AssignHiringManagerToJobRequisitionCommand</li>
 *       <li>UnAssignHiringManagerFromJobRequisitionCommand</li>
  *       <li>AssignRecruiterToJobRequisitionCommand</li>
 *       <li>UnAssignRecruiterFromJobRequisitionCommand</li>
  *       <li>AssignJobProfileToJobRequisitionCommand</li>
 *       <li>UnAssignJobProfileFromJobRequisitionCommand</li>
   *       <li>AssignCandidatesToJobRequisitionCommand</li>
 *       <li>RemoveCandidatesFromJobRequisitionCommand</li>
 *   </ul>
 *
  *       <li>AssignInterviewsToJobRequisitionCommand</li>
 *       <li>RemoveInterviewsFromJobRequisitionCommand</li>
 *   </ul>
 *
  *       <li>AssignOffersToJobRequisitionCommand</li>
 *       <li>RemoveOffersFromJobRequisitionCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class JobRequisitionValidator {

	/**
	 * default constructor
	 */
	protected JobRequisitionValidator() {
	}


	/**
	 * handles creation validation for a JobRequisition
	 */
	public void validate( CreateJobRequisitionCommand jobRequisition )throws ValidationException {
		if ( jobRequisition == null )
			throw new ValidationException( "JobRequisition", "validating CreateJobRequisitionCommand" );
		if ( jobRequisition.getRequisitionNumber() == null )
			throw new ValidationException( "JobRequisition", "validating access on getRequisitionNumber" );
		if ( jobRequisition.getTitle() == null )
			throw new ValidationException( "JobRequisition", "validating access on getTitle" );
		if ( jobRequisition.getOpenings() == null )
			throw new ValidationException( "JobRequisition", "validating access on getOpenings" );
		if ( jobRequisition.getTargetStartDate() == null )
			throw new ValidationException( "JobRequisition", "validating access on getTargetStartDate" );
	}

	/**
	 * handles update validation for a JobRequisition
	 */
	public void validate( UpdateJobRequisitionCommand jobRequisition ) throws ValidationException {
		if ( jobRequisition == null )
			throw new ValidationException( "JobRequisition", "validating UpdateJobRequisitionCommand" );
		if ( jobRequisition.getRequisitionNumber() == null )
			throw new ValidationException( "JobRequisition", "validating method getRequisitionNumber" );
		if ( jobRequisition.getTitle() == null )
			throw new ValidationException( "JobRequisition", "validating method getTitle" );
		if ( jobRequisition.getOpenings() == null )
			throw new ValidationException( "JobRequisition", "validating method getOpenings" );
		if ( jobRequisition.getTargetStartDate() == null )
			throw new ValidationException( "JobRequisition", "validating method getTargetStartDate" );
	}

/**
 * handles delete validation for a JobRequisition
 */
	public void validate( DeleteJobRequisitionCommand jobRequisition ) throws ValidationException {
		if ( jobRequisition == null )
			throw new ValidationException( "JobRequisition", "validating DeleteJobRequisitionCommand" );

		if ( jobRequisition.getId() == null )
			throw new ValidationException( "JobRequisition", "validating DeleteJobRequisitionCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a JobRequisition
 */
	public void validate( JobRequisitionFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "JobRequisition", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "JobRequisition", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Department validation for a JobRequisition
	 *
	 * @param	command AssignDepartmentToJobRequisitionCommand
	 */
	public void validate( AssignDepartmentToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignDepartmentToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignDepartmentToJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Department validation for a JobRequisition
	 *
	 * @param	command UnAssignDepartmentFromJobRequisitionCommand
	 */
	public void validate( UnAssignDepartmentFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating UnAssignDepartmentFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on UnAssignDepartmentFromJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign HiringManager validation for a JobRequisition
	 *
	 * @param	command AssignHiringManagerToJobRequisitionCommand
	 */
	public void validate( AssignHiringManagerToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignHiringManagerToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignHiringManagerToJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign HiringManager validation for a JobRequisition
	 *
	 * @param	command UnAssignHiringManagerFromJobRequisitionCommand
	 */
	public void validate( UnAssignHiringManagerFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating UnAssignHiringManagerFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on UnAssignHiringManagerFromJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Recruiter validation for a JobRequisition
	 *
	 * @param	command AssignRecruiterToJobRequisitionCommand
	 */
	public void validate( AssignRecruiterToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignRecruiterToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignRecruiterToJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Recruiter validation for a JobRequisition
	 *
	 * @param	command UnAssignRecruiterFromJobRequisitionCommand
	 */
	public void validate( UnAssignRecruiterFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating UnAssignRecruiterFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on UnAssignRecruiterFromJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign JobProfile validation for a JobRequisition
	 *
	 * @param	command AssignJobProfileToJobRequisitionCommand
	 */
	public void validate( AssignJobProfileToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignJobProfileToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignJobProfileToJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign JobProfile validation for a JobRequisition
	 *
	 * @param	command UnAssignJobProfileFromJobRequisitionCommand
	 */
	public void validate( UnAssignJobProfileFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating UnAssignJobProfileFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on UnAssignJobProfileFromJobRequisitionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Candidates validation for a JobRequisition
	 *
	 * @param	command AssignCandidatesToJobRequisitionCommand
	 */
	public void validate( AssignCandidatesToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignCandidatesToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignCandidatesToJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Candidates validation for a JobRequisition
	 *
	 * @param	command RemoveCandidatesFromJobRequisitionCommand
	 */
	public void validate( RemoveCandidatesFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("JobRequisition", "validating RemoveCandidatesFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on RemoveCandidatesFromJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Interviews validation for a JobRequisition
	 *
	 * @param	command AssignInterviewsToJobRequisitionCommand
	 */
	public void validate( AssignInterviewsToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignInterviewsToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignInterviewsToJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Interviews validation for a JobRequisition
	 *
	 * @param	command RemoveInterviewsFromJobRequisitionCommand
	 */
	public void validate( RemoveInterviewsFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("JobRequisition", "validating RemoveInterviewsFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on RemoveInterviewsFromJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Offers validation for a JobRequisition
	 *
	 * @param	command AssignOffersToJobRequisitionCommand
	 */
	public void validate( AssignOffersToJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "JobRequisition", "validating AssignOffersToJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on AssignOffersToJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Offers validation for a JobRequisition
	 *
	 * @param	command RemoveOffersFromJobRequisitionCommand
	 */
	public void validate( RemoveOffersFromJobRequisitionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("JobRequisition", "validating RemoveOffersFromJobRequisitionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "JobRequisition", "validating identity on RemoveOffersFromJobRequisitionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
