/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>OfferValidation</h2>
 * <p>
 * The Offer Validation  handles state validation of a Offer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateOfferCommand</li>
 *      <li>UpdateOfferCommand</li>
 *      <li>DeleteOfferCommand</li>
 *set( false = false )
  *       <li>AssignRequisitionToOfferCommand</li>
 *       <li>UnAssignRequisitionFromOfferCommand</li>
  *       <li>AssignCandidateToOfferCommand</li>
 *       <li>UnAssignCandidateFromOfferCommand</li>
  *       <li>AssignApprovedByToOfferCommand</li>
 *       <li>UnAssignApprovedByFromOfferCommand</li>
  *       <li>AssignContractToOfferCommand</li>
 *       <li>UnAssignContractFromOfferCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class OfferValidator {

	/**
	 * default constructor
	 */
	protected OfferValidator() {
	}


	/**
	 * handles creation validation for a Offer
	 */
	public void validate( CreateOfferCommand offer )throws ValidationException {
		if ( offer == null )
			throw new ValidationException( "Offer", "validating CreateOfferCommand" );
		if ( offer.getOfferNumber() == null )
			throw new ValidationException( "Offer", "validating access on getOfferNumber" );
		if ( offer.getProposedStartDate() == null )
			throw new ValidationException( "Offer", "validating access on getProposedStartDate" );
		if ( offer.getBaseSalary() == null )
			throw new ValidationException( "Offer", "validating access on getBaseSalary" );
		if ( offer.getSignOnBonus() == null )
			throw new ValidationException( "Offer", "validating access on getSignOnBonus" );
	}

	/**
	 * handles update validation for a Offer
	 */
	public void validate( UpdateOfferCommand offer ) throws ValidationException {
		if ( offer == null )
			throw new ValidationException( "Offer", "validating UpdateOfferCommand" );
		if ( offer.getOfferNumber() == null )
			throw new ValidationException( "Offer", "validating method getOfferNumber" );
		if ( offer.getProposedStartDate() == null )
			throw new ValidationException( "Offer", "validating method getProposedStartDate" );
		if ( offer.getBaseSalary() == null )
			throw new ValidationException( "Offer", "validating method getBaseSalary" );
		if ( offer.getSignOnBonus() == null )
			throw new ValidationException( "Offer", "validating method getSignOnBonus" );
	}

/**
 * handles delete validation for a Offer
 */
	public void validate( DeleteOfferCommand offer ) throws ValidationException {
		if ( offer == null )
			throw new ValidationException( "Offer", "validating DeleteOfferCommand" );

		if ( offer.getId() == null )
			throw new ValidationException( "Offer", "validating DeleteOfferCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Offer
 */
	public void validate( OfferFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Offer", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Offer", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Requisition validation for a Offer
	 *
	 * @param	command AssignRequisitionToOfferCommand
	 */
	public void validate( AssignRequisitionToOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating AssignRequisitionToOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on AssignRequisitionToOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Requisition validation for a Offer
	 *
	 * @param	command UnAssignRequisitionFromOfferCommand
	 */
	public void validate( UnAssignRequisitionFromOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating UnAssignRequisitionFromOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on UnAssignRequisitionFromOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Candidate validation for a Offer
	 *
	 * @param	command AssignCandidateToOfferCommand
	 */
	public void validate( AssignCandidateToOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating AssignCandidateToOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on AssignCandidateToOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Candidate validation for a Offer
	 *
	 * @param	command UnAssignCandidateFromOfferCommand
	 */
	public void validate( UnAssignCandidateFromOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating UnAssignCandidateFromOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on UnAssignCandidateFromOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign ApprovedBy validation for a Offer
	 *
	 * @param	command AssignApprovedByToOfferCommand
	 */
	public void validate( AssignApprovedByToOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating AssignApprovedByToOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on AssignApprovedByToOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign ApprovedBy validation for a Offer
	 *
	 * @param	command UnAssignApprovedByFromOfferCommand
	 */
	public void validate( UnAssignApprovedByFromOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating UnAssignApprovedByFromOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on UnAssignApprovedByFromOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Contract validation for a Offer
	 *
	 * @param	command AssignContractToOfferCommand
	 */
	public void validate( AssignContractToOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating AssignContractToOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on AssignContractToOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Contract validation for a Offer
	 *
	 * @param	command UnAssignContractFromOfferCommand
	 */
	public void validate( UnAssignContractFromOfferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Offer", "validating UnAssignContractFromOfferCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Offer", "validating identity on UnAssignContractFromOfferCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
