/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PayrollRunValidation</h2>
 * <p>
 * The PayrollRun Validation  handles state validation of a PayrollRun include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePayrollRunCommand</li>
 *      <li>UpdatePayrollRunCommand</li>
 *      <li>DeletePayrollRunCommand</li>
 *set( false = false )
  *       <li>AssignPayrollCalendarToPayrollRunCommand</li>
 *       <li>UnAssignPayrollCalendarFromPayrollRunCommand</li>
   *       <li>AssignPayrollItemsToPayrollRunCommand</li>
 *       <li>RemovePayrollItemsFromPayrollRunCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PayrollRunValidator {

	/**
	 * default constructor
	 */
	protected PayrollRunValidator() {
	}


	/**
	 * handles creation validation for a PayrollRun
	 */
	public void validate( CreatePayrollRunCommand payrollRun )throws ValidationException {
		if ( payrollRun == null )
			throw new ValidationException( "PayrollRun", "validating CreatePayrollRunCommand" );
		if ( payrollRun.getRunNumber() == null )
			throw new ValidationException( "PayrollRun", "validating access on getRunNumber" );
		if ( payrollRun.getPeriodStart() == null )
			throw new ValidationException( "PayrollRun", "validating access on getPeriodStart" );
		if ( payrollRun.getPeriodEnd() == null )
			throw new ValidationException( "PayrollRun", "validating access on getPeriodEnd" );
		if ( payrollRun.getPaymentDate() == null )
			throw new ValidationException( "PayrollRun", "validating access on getPaymentDate" );
	}

	/**
	 * handles update validation for a PayrollRun
	 */
	public void validate( UpdatePayrollRunCommand payrollRun ) throws ValidationException {
		if ( payrollRun == null )
			throw new ValidationException( "PayrollRun", "validating UpdatePayrollRunCommand" );
		if ( payrollRun.getRunNumber() == null )
			throw new ValidationException( "PayrollRun", "validating method getRunNumber" );
		if ( payrollRun.getPeriodStart() == null )
			throw new ValidationException( "PayrollRun", "validating method getPeriodStart" );
		if ( payrollRun.getPeriodEnd() == null )
			throw new ValidationException( "PayrollRun", "validating method getPeriodEnd" );
		if ( payrollRun.getPaymentDate() == null )
			throw new ValidationException( "PayrollRun", "validating method getPaymentDate" );
	}

/**
 * handles delete validation for a PayrollRun
 */
	public void validate( DeletePayrollRunCommand payrollRun ) throws ValidationException {
		if ( payrollRun == null )
			throw new ValidationException( "PayrollRun", "validating DeletePayrollRunCommand" );

		if ( payrollRun.getId() == null )
			throw new ValidationException( "PayrollRun", "validating DeletePayrollRunCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PayrollRun
 */
	public void validate( PayrollRunFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PayrollRun", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PayrollRun", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign PayrollCalendar validation for a PayrollRun
	 *
	 * @param	command AssignPayrollCalendarToPayrollRunCommand
	 */
	public void validate( AssignPayrollCalendarToPayrollRunCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollRun", "validating AssignPayrollCalendarToPayrollRunCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PayrollRun", "validating identity on AssignPayrollCalendarToPayrollRunCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign PayrollCalendar validation for a PayrollRun
	 *
	 * @param	command UnAssignPayrollCalendarFromPayrollRunCommand
	 */
	public void validate( UnAssignPayrollCalendarFromPayrollRunCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollRun", "validating UnAssignPayrollCalendarFromPayrollRunCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PayrollRun", "validating identity on UnAssignPayrollCalendarFromPayrollRunCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to PayrollItems validation for a PayrollRun
	 *
	 * @param	command AssignPayrollItemsToPayrollRunCommand
	 */
	public void validate( AssignPayrollItemsToPayrollRunCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollRun", "validating AssignPayrollItemsToPayrollRunCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollRun", "validating identity on AssignPayrollItemsToPayrollRunCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from PayrollItems validation for a PayrollRun
	 *
	 * @param	command RemovePayrollItemsFromPayrollRunCommand
	 */
	public void validate( RemovePayrollItemsFromPayrollRunCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PayrollRun", "validating RemovePayrollItemsFromPayrollRunCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollRun", "validating identity on RemovePayrollItemsFromPayrollRunCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
