/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PayrollCalendarValidation</h2>
 * <p>
 * The PayrollCalendar Validation  handles state validation of a PayrollCalendar include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePayrollCalendarCommand</li>
 *      <li>UpdatePayrollCalendarCommand</li>
 *      <li>DeletePayrollCalendarCommand</li>
 *set( false = false )
  *       <li>AssignOrganizationToPayrollCalendarCommand</li>
 *       <li>UnAssignOrganizationFromPayrollCalendarCommand</li>
   *       <li>AssignPayrollRunsToPayrollCalendarCommand</li>
 *       <li>RemovePayrollRunsFromPayrollCalendarCommand</li>
 *   </ul>
 *
  *       <li>AssignEmployeesToPayrollCalendarCommand</li>
 *       <li>RemoveEmployeesFromPayrollCalendarCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PayrollCalendarValidator {

	/**
	 * default constructor
	 */
	protected PayrollCalendarValidator() {
	}


	/**
	 * handles creation validation for a PayrollCalendar
	 */
	public void validate( CreatePayrollCalendarCommand payrollCalendar )throws ValidationException {
		if ( payrollCalendar == null )
			throw new ValidationException( "PayrollCalendar", "validating CreatePayrollCalendarCommand" );
		if ( payrollCalendar.getName() == null )
			throw new ValidationException( "PayrollCalendar", "validating access on getName" );
		if ( payrollCalendar.getCountry() == null )
			throw new ValidationException( "PayrollCalendar", "validating access on getCountry" );
	}

	/**
	 * handles update validation for a PayrollCalendar
	 */
	public void validate( UpdatePayrollCalendarCommand payrollCalendar ) throws ValidationException {
		if ( payrollCalendar == null )
			throw new ValidationException( "PayrollCalendar", "validating UpdatePayrollCalendarCommand" );
		if ( payrollCalendar.getName() == null )
			throw new ValidationException( "PayrollCalendar", "validating method getName" );
		if ( payrollCalendar.getCountry() == null )
			throw new ValidationException( "PayrollCalendar", "validating method getCountry" );
	}

/**
 * handles delete validation for a PayrollCalendar
 */
	public void validate( DeletePayrollCalendarCommand payrollCalendar ) throws ValidationException {
		if ( payrollCalendar == null )
			throw new ValidationException( "PayrollCalendar", "validating DeletePayrollCalendarCommand" );

		if ( payrollCalendar.getId() == null )
			throw new ValidationException( "PayrollCalendar", "validating DeletePayrollCalendarCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PayrollCalendar
 */
	public void validate( PayrollCalendarFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PayrollCalendar", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PayrollCalendar", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Organization validation for a PayrollCalendar
	 *
	 * @param	command AssignOrganizationToPayrollCalendarCommand
	 */
	public void validate( AssignOrganizationToPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollCalendar", "validating AssignOrganizationToPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on AssignOrganizationToPayrollCalendarCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Organization validation for a PayrollCalendar
	 *
	 * @param	command UnAssignOrganizationFromPayrollCalendarCommand
	 */
	public void validate( UnAssignOrganizationFromPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollCalendar", "validating UnAssignOrganizationFromPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on UnAssignOrganizationFromPayrollCalendarCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to PayrollRuns validation for a PayrollCalendar
	 *
	 * @param	command AssignPayrollRunsToPayrollCalendarCommand
	 */
	public void validate( AssignPayrollRunsToPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollCalendar", "validating AssignPayrollRunsToPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on AssignPayrollRunsToPayrollCalendarCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from PayrollRuns validation for a PayrollCalendar
	 *
	 * @param	command RemovePayrollRunsFromPayrollCalendarCommand
	 */
	public void validate( RemovePayrollRunsFromPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PayrollCalendar", "validating RemovePayrollRunsFromPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on RemovePayrollRunsFromPayrollCalendarCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Employees validation for a PayrollCalendar
	 *
	 * @param	command AssignEmployeesToPayrollCalendarCommand
	 */
	public void validate( AssignEmployeesToPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PayrollCalendar", "validating AssignEmployeesToPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on AssignEmployeesToPayrollCalendarCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Employees validation for a PayrollCalendar
	 *
	 * @param	command RemoveEmployeesFromPayrollCalendarCommand
	 */
	public void validate( RemoveEmployeesFromPayrollCalendarCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PayrollCalendar", "validating RemoveEmployeesFromPayrollCalendarCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PayrollCalendar", "validating identity on RemoveEmployeesFromPayrollCalendarCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
