/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PerformanceCycleValidation</h2>
 * <p>
 * The PerformanceCycle Validation  handles state validation of a PerformanceCycle include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePerformanceCycleCommand</li>
 *      <li>UpdatePerformanceCycleCommand</li>
 *      <li>DeletePerformanceCycleCommand</li>
 *set( false = false )
  *       <li>AssignOrganizationToPerformanceCycleCommand</li>
 *       <li>UnAssignOrganizationFromPerformanceCycleCommand</li>
   *       <li>AssignReviewsToPerformanceCycleCommand</li>
 *       <li>RemoveReviewsFromPerformanceCycleCommand</li>
 *   </ul>
 *
  *       <li>AssignGoalsToPerformanceCycleCommand</li>
 *       <li>RemoveGoalsFromPerformanceCycleCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PerformanceCycleValidator {

	/**
	 * default constructor
	 */
	protected PerformanceCycleValidator() {
	}


	/**
	 * handles creation validation for a PerformanceCycle
	 */
	public void validate( CreatePerformanceCycleCommand performanceCycle )throws ValidationException {
		if ( performanceCycle == null )
			throw new ValidationException( "PerformanceCycle", "validating CreatePerformanceCycleCommand" );
		if ( performanceCycle.getName() == null )
			throw new ValidationException( "PerformanceCycle", "validating access on getName" );
		if ( performanceCycle.getStartDate() == null )
			throw new ValidationException( "PerformanceCycle", "validating access on getStartDate" );
		if ( performanceCycle.getEndDate() == null )
			throw new ValidationException( "PerformanceCycle", "validating access on getEndDate" );
	}

	/**
	 * handles update validation for a PerformanceCycle
	 */
	public void validate( UpdatePerformanceCycleCommand performanceCycle ) throws ValidationException {
		if ( performanceCycle == null )
			throw new ValidationException( "PerformanceCycle", "validating UpdatePerformanceCycleCommand" );
		if ( performanceCycle.getName() == null )
			throw new ValidationException( "PerformanceCycle", "validating method getName" );
		if ( performanceCycle.getStartDate() == null )
			throw new ValidationException( "PerformanceCycle", "validating method getStartDate" );
		if ( performanceCycle.getEndDate() == null )
			throw new ValidationException( "PerformanceCycle", "validating method getEndDate" );
	}

/**
 * handles delete validation for a PerformanceCycle
 */
	public void validate( DeletePerformanceCycleCommand performanceCycle ) throws ValidationException {
		if ( performanceCycle == null )
			throw new ValidationException( "PerformanceCycle", "validating DeletePerformanceCycleCommand" );

		if ( performanceCycle.getId() == null )
			throw new ValidationException( "PerformanceCycle", "validating DeletePerformanceCycleCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PerformanceCycle
 */
	public void validate( PerformanceCycleFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PerformanceCycle", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PerformanceCycle", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Organization validation for a PerformanceCycle
	 *
	 * @param	command AssignOrganizationToPerformanceCycleCommand
	 */
	public void validate( AssignOrganizationToPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PerformanceCycle", "validating AssignOrganizationToPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on AssignOrganizationToPerformanceCycleCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Organization validation for a PerformanceCycle
	 *
	 * @param	command UnAssignOrganizationFromPerformanceCycleCommand
	 */
	public void validate( UnAssignOrganizationFromPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PerformanceCycle", "validating UnAssignOrganizationFromPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on UnAssignOrganizationFromPerformanceCycleCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Reviews validation for a PerformanceCycle
	 *
	 * @param	command AssignReviewsToPerformanceCycleCommand
	 */
	public void validate( AssignReviewsToPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PerformanceCycle", "validating AssignReviewsToPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on AssignReviewsToPerformanceCycleCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Reviews validation for a PerformanceCycle
	 *
	 * @param	command RemoveReviewsFromPerformanceCycleCommand
	 */
	public void validate( RemoveReviewsFromPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PerformanceCycle", "validating RemoveReviewsFromPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on RemoveReviewsFromPerformanceCycleCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Goals validation for a PerformanceCycle
	 *
	 * @param	command AssignGoalsToPerformanceCycleCommand
	 */
	public void validate( AssignGoalsToPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PerformanceCycle", "validating AssignGoalsToPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on AssignGoalsToPerformanceCycleCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Goals validation for a PerformanceCycle
	 *
	 * @param	command RemoveGoalsFromPerformanceCycleCommand
	 */
	public void validate( RemoveGoalsFromPerformanceCycleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PerformanceCycle", "validating RemoveGoalsFromPerformanceCycleCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PerformanceCycle", "validating identity on RemoveGoalsFromPerformanceCycleCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
