/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PolicyValidation</h2>
 * <p>
 * The Policy Validation  handles state validation of a Policy include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePolicyCommand</li>
 *      <li>UpdatePolicyCommand</li>
 *      <li>DeletePolicyCommand</li>
 *set( false = false )
  *       <li>AssignOrganizationToPolicyCommand</li>
 *       <li>UnAssignOrganizationFromPolicyCommand</li>
   *       <li>AssignAcknowledgementsToPolicyCommand</li>
 *       <li>RemoveAcknowledgementsFromPolicyCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PolicyValidator {

	/**
	 * default constructor
	 */
	protected PolicyValidator() {
	}


	/**
	 * handles creation validation for a Policy
	 */
	public void validate( CreatePolicyCommand policy )throws ValidationException {
		if ( policy == null )
			throw new ValidationException( "Policy", "validating CreatePolicyCommand" );
		if ( policy.getPolicyNumber() == null )
			throw new ValidationException( "Policy", "validating access on getPolicyNumber" );
		if ( policy.getName() == null )
			throw new ValidationException( "Policy", "validating access on getName" );
		if ( policy.getEffectiveDate() == null )
			throw new ValidationException( "Policy", "validating access on getEffectiveDate" );
		if ( policy.getDescription() == null )
			throw new ValidationException( "Policy", "validating access on getDescription" );
	}

	/**
	 * handles update validation for a Policy
	 */
	public void validate( UpdatePolicyCommand policy ) throws ValidationException {
		if ( policy == null )
			throw new ValidationException( "Policy", "validating UpdatePolicyCommand" );
		if ( policy.getPolicyNumber() == null )
			throw new ValidationException( "Policy", "validating method getPolicyNumber" );
		if ( policy.getName() == null )
			throw new ValidationException( "Policy", "validating method getName" );
		if ( policy.getEffectiveDate() == null )
			throw new ValidationException( "Policy", "validating method getEffectiveDate" );
		if ( policy.getDescription() == null )
			throw new ValidationException( "Policy", "validating method getDescription" );
	}

/**
 * handles delete validation for a Policy
 */
	public void validate( DeletePolicyCommand policy ) throws ValidationException {
		if ( policy == null )
			throw new ValidationException( "Policy", "validating DeletePolicyCommand" );

		if ( policy.getId() == null )
			throw new ValidationException( "Policy", "validating DeletePolicyCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Policy
 */
	public void validate( PolicyFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Policy", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Policy", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Organization validation for a Policy
	 *
	 * @param	command AssignOrganizationToPolicyCommand
	 */
	public void validate( AssignOrganizationToPolicyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Policy", "validating AssignOrganizationToPolicyCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Policy", "validating identity on AssignOrganizationToPolicyCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Organization validation for a Policy
	 *
	 * @param	command UnAssignOrganizationFromPolicyCommand
	 */
	public void validate( UnAssignOrganizationFromPolicyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Policy", "validating UnAssignOrganizationFromPolicyCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Policy", "validating identity on UnAssignOrganizationFromPolicyCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Acknowledgements validation for a Policy
	 *
	 * @param	command AssignAcknowledgementsToPolicyCommand
	 */
	public void validate( AssignAcknowledgementsToPolicyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Policy", "validating AssignAcknowledgementsToPolicyCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Policy", "validating identity on AssignAcknowledgementsToPolicyCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Acknowledgements validation for a Policy
	 *
	 * @param	command RemoveAcknowledgementsFromPolicyCommand
	 */
	public void validate( RemoveAcknowledgementsFromPolicyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Policy", "validating RemoveAcknowledgementsFromPolicyCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Policy", "validating identity on RemoveAcknowledgementsFromPolicyCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
