/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>TimesheetValidation</h2>
 * <p>
 * The Timesheet Validation  handles state validation of a Timesheet include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTimesheetCommand</li>
 *      <li>UpdateTimesheetCommand</li>
 *      <li>DeleteTimesheetCommand</li>
 *set( false = false )
  *       <li>AssignEmployeeToTimesheetCommand</li>
 *       <li>UnAssignEmployeeFromTimesheetCommand</li>
   *       <li>AssignTimeEntriesToTimesheetCommand</li>
 *       <li>RemoveTimeEntriesFromTimesheetCommand</li>
 *   </ul>
 *
  *       <li>AssignApprovalsToTimesheetCommand</li>
 *       <li>RemoveApprovalsFromTimesheetCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class TimesheetValidator {

	/**
	 * default constructor
	 */
	protected TimesheetValidator() {
	}


	/**
	 * handles creation validation for a Timesheet
	 */
	public void validate( CreateTimesheetCommand timesheet )throws ValidationException {
		if ( timesheet == null )
			throw new ValidationException( "Timesheet", "validating CreateTimesheetCommand" );
		if ( timesheet.getPeriodStart() == null )
			throw new ValidationException( "Timesheet", "validating access on getPeriodStart" );
		if ( timesheet.getPeriodEnd() == null )
			throw new ValidationException( "Timesheet", "validating access on getPeriodEnd" );
		if ( timesheet.getSubmissionDate() == null )
			throw new ValidationException( "Timesheet", "validating access on getSubmissionDate" );
	}

	/**
	 * handles update validation for a Timesheet
	 */
	public void validate( UpdateTimesheetCommand timesheet ) throws ValidationException {
		if ( timesheet == null )
			throw new ValidationException( "Timesheet", "validating UpdateTimesheetCommand" );
		if ( timesheet.getPeriodStart() == null )
			throw new ValidationException( "Timesheet", "validating method getPeriodStart" );
		if ( timesheet.getPeriodEnd() == null )
			throw new ValidationException( "Timesheet", "validating method getPeriodEnd" );
		if ( timesheet.getSubmissionDate() == null )
			throw new ValidationException( "Timesheet", "validating method getSubmissionDate" );
	}

/**
 * handles delete validation for a Timesheet
 */
	public void validate( DeleteTimesheetCommand timesheet ) throws ValidationException {
		if ( timesheet == null )
			throw new ValidationException( "Timesheet", "validating DeleteTimesheetCommand" );

		if ( timesheet.getId() == null )
			throw new ValidationException( "Timesheet", "validating DeleteTimesheetCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Timesheet
 */
	public void validate( TimesheetFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Timesheet", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Timesheet", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Employee validation for a Timesheet
	 *
	 * @param	command AssignEmployeeToTimesheetCommand
	 */
	public void validate( AssignEmployeeToTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Timesheet", "validating AssignEmployeeToTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Timesheet", "validating identity on AssignEmployeeToTimesheetCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Employee validation for a Timesheet
	 *
	 * @param	command UnAssignEmployeeFromTimesheetCommand
	 */
	public void validate( UnAssignEmployeeFromTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Timesheet", "validating UnAssignEmployeeFromTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Timesheet", "validating identity on UnAssignEmployeeFromTimesheetCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to TimeEntries validation for a Timesheet
	 *
	 * @param	command AssignTimeEntriesToTimesheetCommand
	 */
	public void validate( AssignTimeEntriesToTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Timesheet", "validating AssignTimeEntriesToTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Timesheet", "validating identity on AssignTimeEntriesToTimesheetCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from TimeEntries validation for a Timesheet
	 *
	 * @param	command RemoveTimeEntriesFromTimesheetCommand
	 */
	public void validate( RemoveTimeEntriesFromTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Timesheet", "validating RemoveTimeEntriesFromTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Timesheet", "validating identity on RemoveTimeEntriesFromTimesheetCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Approvals validation for a Timesheet
	 *
	 * @param	command AssignApprovalsToTimesheetCommand
	 */
	public void validate( AssignApprovalsToTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Timesheet", "validating AssignApprovalsToTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Timesheet", "validating identity on AssignApprovalsToTimesheetCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Approvals validation for a Timesheet
	 *
	 * @param	command RemoveApprovalsFromTimesheetCommand
	 */
	public void validate( RemoveApprovalsFromTimesheetCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Timesheet", "validating RemoveApprovalsFromTimesheetCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Timesheet", "validating identity on RemoveApprovalsFromTimesheetCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
