/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>TrainingCourseValidation</h2>
 * <p>
 * The TrainingCourse Validation  handles state validation of a TrainingCourse include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTrainingCourseCommand</li>
 *      <li>UpdateTrainingCourseCommand</li>
 *      <li>DeleteTrainingCourseCommand</li>
 *set( false = false )
   *       <li>AssignPrerequisitesToTrainingCourseCommand</li>
 *       <li>RemovePrerequisitesFromTrainingCourseCommand</li>
 *   </ul>
 *
  *       <li>AssignEnrollmentsToTrainingCourseCommand</li>
 *       <li>RemoveEnrollmentsFromTrainingCourseCommand</li>
 *   </ul>
 *
  *       <li>AssignJobProfilesToTrainingCourseCommand</li>
 *       <li>RemoveJobProfilesFromTrainingCourseCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class TrainingCourseValidator {

	/**
	 * default constructor
	 */
	protected TrainingCourseValidator() {
	}


	/**
	 * handles creation validation for a TrainingCourse
	 */
	public void validate( CreateTrainingCourseCommand trainingCourse )throws ValidationException {
		if ( trainingCourse == null )
			throw new ValidationException( "TrainingCourse", "validating CreateTrainingCourseCommand" );
		if ( trainingCourse.getCode() == null )
			throw new ValidationException( "TrainingCourse", "validating access on getCode" );
		if ( trainingCourse.getTitle() == null )
			throw new ValidationException( "TrainingCourse", "validating access on getTitle" );
		if ( trainingCourse.getDurationHours() == null )
			throw new ValidationException( "TrainingCourse", "validating access on getDurationHours" );
	}

	/**
	 * handles update validation for a TrainingCourse
	 */
	public void validate( UpdateTrainingCourseCommand trainingCourse ) throws ValidationException {
		if ( trainingCourse == null )
			throw new ValidationException( "TrainingCourse", "validating UpdateTrainingCourseCommand" );
		if ( trainingCourse.getCode() == null )
			throw new ValidationException( "TrainingCourse", "validating method getCode" );
		if ( trainingCourse.getTitle() == null )
			throw new ValidationException( "TrainingCourse", "validating method getTitle" );
		if ( trainingCourse.getDurationHours() == null )
			throw new ValidationException( "TrainingCourse", "validating method getDurationHours" );
	}

/**
 * handles delete validation for a TrainingCourse
 */
	public void validate( DeleteTrainingCourseCommand trainingCourse ) throws ValidationException {
		if ( trainingCourse == null )
			throw new ValidationException( "TrainingCourse", "validating DeleteTrainingCourseCommand" );

		if ( trainingCourse.getId() == null )
			throw new ValidationException( "TrainingCourse", "validating DeleteTrainingCourseCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a TrainingCourse
 */
	public void validate( TrainingCourseFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "TrainingCourse", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "TrainingCourse", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Prerequisites validation for a TrainingCourse
	 *
	 * @param	command AssignPrerequisitesToTrainingCourseCommand
	 */
	public void validate( AssignPrerequisitesToTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TrainingCourse", "validating AssignPrerequisitesToTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on AssignPrerequisitesToTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Prerequisites validation for a TrainingCourse
	 *
	 * @param	command RemovePrerequisitesFromTrainingCourseCommand
	 */
	public void validate( RemovePrerequisitesFromTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TrainingCourse", "validating RemovePrerequisitesFromTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on RemovePrerequisitesFromTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Enrollments validation for a TrainingCourse
	 *
	 * @param	command AssignEnrollmentsToTrainingCourseCommand
	 */
	public void validate( AssignEnrollmentsToTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TrainingCourse", "validating AssignEnrollmentsToTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on AssignEnrollmentsToTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Enrollments validation for a TrainingCourse
	 *
	 * @param	command RemoveEnrollmentsFromTrainingCourseCommand
	 */
	public void validate( RemoveEnrollmentsFromTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TrainingCourse", "validating RemoveEnrollmentsFromTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on RemoveEnrollmentsFromTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to JobProfiles validation for a TrainingCourse
	 *
	 * @param	command AssignJobProfilesToTrainingCourseCommand
	 */
	public void validate( AssignJobProfilesToTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TrainingCourse", "validating AssignJobProfilesToTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on AssignJobProfilesToTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from JobProfiles validation for a TrainingCourse
	 *
	 * @param	command RemoveJobProfilesFromTrainingCourseCommand
	 */
	public void validate( RemoveJobProfilesFromTrainingCourseCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TrainingCourse", "validating RemoveJobProfilesFromTrainingCourseCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TrainingCourse", "validating identity on RemoveJobProfilesFromTrainingCourseCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
