
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * BenefitEnrollmentRestController as REST API
 *
 * <p>Exposes REST endpoints for the BenefitEnrollment entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BenefitEnrollmentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBenefitEnrollmentCommand</li>
 *      <li></li>UpdateBenefitEnrollmentCommand</li>
 *      <liDeleteBenefitEnrollmentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/BenefitEnrollment")
public class BenefitEnrollmentRestController extends BaseSpringRestController {

	public BenefitEnrollmentRestController( BenefitEnrollmentService service ) {
		this.service = service;
	}
    /**
     * Handles create a BenefitEnrollment.  if not key provided, calls create, otherwise calls save
     * @param		BenefitEnrollment	benefitEnrollment
     * @return		BenefitEnrollment 
     */
	@PostMapping("/create")
    public BenefitEnrollment create( @RequestBody(required=true) CreateBenefitEnrollmentCommand command ) {
    	BenefitEnrollment entity = null;

		entity = service.createBenefitEnrollment( command );
		LOGGER.info( "Successfully created BenefitEnrollment with Id " + entity.getBenefitEnrollmentId()  );

		return entity;
    }

    /**
     * Handles updating a BenefitEnrollment.  if no key provided, calls create, otherwise calls save
     * @param		BenefitEnrollment benefitEnrollment
     * @return		BenefitEnrollment
     */
	@PutMapping("/update")
    public BenefitEnrollment update( @RequestBody(required=true) UpdateBenefitEnrollmentCommand command ) {
		BenefitEnrollment entity = null;

		entity = service.updateBenefitEnrollment(command);
		LOGGER.info( "Successfully updated BenefitEnrollment with Id " + command.getBenefitEnrollmentId()  );

		return entity;
	}
 
    /**
     * Handles deleting a BenefitEnrollment entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteBenefitEnrollmentCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted BenefitEnrollment with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a BenefitEnrollment using a UUID
     * @param		UUID uuid 
     * @return		BenefitEnrollment
     */    
    @GetMapping("/get")
    public BenefitEnrollment get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	BenefitEnrollment entity = service.getBenefitEnrollment( new BenefitEnrollmentFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded BenefitEnrollment with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all BenefitEnrollment business objects
     * @return		List<BenefitEnrollment>
     */
    @GetMapping("/")
    public List<BenefitEnrollment> getAll() {
    	List<BenefitEnrollment> benefitEnrollmentList = null;

		benefitEnrollmentList = service.getAllBenefitEnrollment();
		LOGGER.info( "successfully loaded all BenefitEnrollments" );

        return benefitEnrollmentList;
                            
    }

	/**
	 * Handles loading all BenefitPlan} business objects
	 * @return		List<BenefitEnrollment>

    @GetMapping("/BenefitPlan")
    public List<BenefitEnrollment> BenefitPlan(UUID parentId) {
		List<BenefitEnrollment> benefitEnrollmentList = load(parentId).getBenefitPlan;
		return benefitEnrollmentList;
	}
	 */
    /**
     * save BenefitPlan on BenefitEnrollment
     * @param		command AssignBenefitPlanToBenefitEnrollmentCommand
     */     
	@PutMapping("/assignBenefitPlan")
	public void assignBenefitPlan( @RequestBody AssignBenefitPlanToBenefitEnrollmentCommand command ) {
		service.assignBenefitPlan( command );
		LOGGER.info( "Successfully assigned BenefitPlan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign BenefitPlan on BenefitEnrollment
     * @param		 command UnAssignBenefitPlanFromBenefitEnrollmentCommand
     */     
	@PutMapping("/unassignBenefitPlan")
	public void unAssignBenefitPlan( @RequestBody(required=true)  UnAssignBenefitPlanFromBenefitEnrollmentCommand command ) {
		service.unAssignBenefitPlan( command );
		LOGGER.info( "Successfully unassigned BenefitPlan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Employee} business objects
	 * @return		List<BenefitEnrollment>

    @GetMapping("/Employee")
    public List<BenefitEnrollment> Employee(UUID parentId) {
		List<BenefitEnrollment> benefitEnrollmentList = load(parentId).getEmployee;
		return benefitEnrollmentList;
	}
	 */
    /**
     * save Employee on BenefitEnrollment
     * @param		command AssignEmployeeToBenefitEnrollmentCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToBenefitEnrollmentCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on BenefitEnrollment
     * @param		 command UnAssignEmployeeFromBenefitEnrollmentCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromBenefitEnrollmentCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Dependents} business objects
	 * @return		List<BenefitEnrollment>

    @GetMapping("/Dependents")
    public List<BenefitEnrollment> Dependents(UUID parentId) {
		List<BenefitEnrollment> benefitEnrollmentList = load(parentId).getDependents;
		return benefitEnrollmentList;
	}

    /**
     * save Dependents on BenefitEnrollment
     * @param		command AssignDependentsToBenefitEnrollmentCommand
     */     
	@PutMapping("/addToDependents")
	public void addToDependents( @RequestBody(required=true) AssignDependentsToBenefitEnrollmentCommand command ) {
		service.addToDependents( command );
		LOGGER.info( "Successfully added Dependents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Dependents on BenefitEnrollment
     * @param		command RemoveDependentsFromBenefitEnrollmentCommand
     */     	
	@PutMapping("/removeFromDependents")
	public void removeFromDependents( 	@RequestBody(required=true) RemoveDependentsFromBenefitEnrollmentCommand command )
	{		
		service.removeFromDependents( command );
		LOGGER.info( "Successfully removed Dependents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected BenefitEnrollment benefitEnrollment = null;
	protected BenefitEnrollmentService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(BenefitEnrollmentRestController.class.getName());
    
}
