
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CandidateRestController as REST API
 *
 * <p>Exposes REST endpoints for the Candidate entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CandidateService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCandidateCommand</li>
 *      <li></li>UpdateCandidateCommand</li>
 *      <liDeleteCandidateCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Candidate")
public class CandidateRestController extends BaseSpringRestController {

	public CandidateRestController( CandidateService service ) {
		this.service = service;
	}
    /**
     * Handles create a Candidate.  if not key provided, calls create, otherwise calls save
     * @param		Candidate	candidate
     * @return		Candidate 
     */
	@PostMapping("/create")
    public Candidate create( @RequestBody(required=true) CreateCandidateCommand command ) {
    	Candidate entity = null;

		entity = service.createCandidate( command );
		LOGGER.info( "Successfully created Candidate with Id " + entity.getCandidateId()  );

		return entity;
    }

    /**
     * Handles updating a Candidate.  if no key provided, calls create, otherwise calls save
     * @param		Candidate candidate
     * @return		Candidate
     */
	@PutMapping("/update")
    public Candidate update( @RequestBody(required=true) UpdateCandidateCommand command ) {
		Candidate entity = null;

		entity = service.updateCandidate(command);
		LOGGER.info( "Successfully updated Candidate with Id " + command.getCandidateId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Candidate entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCandidateCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Candidate with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Candidate using a UUID
     * @param		UUID uuid 
     * @return		Candidate
     */    
    @GetMapping("/get")
    public Candidate get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Candidate entity = service.getCandidate( new CandidateFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Candidate with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Candidate business objects
     * @return		List<Candidate>
     */
    @GetMapping("/")
    public List<Candidate> getAll() {
    	List<Candidate> candidateList = null;

		candidateList = service.getAllCandidate();
		LOGGER.info( "successfully loaded all Candidates" );

        return candidateList;
                            
    }


	/**
	 * Handles loading all Applications} business objects
	 * @return		List<Candidate>

    @GetMapping("/Applications")
    public List<Candidate> Applications(UUID parentId) {
		List<Candidate> candidateList = load(parentId).getApplications;
		return candidateList;
	}

    /**
     * save Applications on Candidate
     * @param		command AssignApplicationsToCandidateCommand
     */     
	@PutMapping("/addToApplications")
	public void addToApplications( @RequestBody(required=true) AssignApplicationsToCandidateCommand command ) {
		service.addToApplications( command );
		LOGGER.info( "Successfully added Applications with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Applications on Candidate
     * @param		command RemoveApplicationsFromCandidateCommand
     */     	
	@PutMapping("/removeFromApplications")
	public void removeFromApplications( 	@RequestBody(required=true) RemoveApplicationsFromCandidateCommand command )
	{		
		service.removeFromApplications( command );
		LOGGER.info( "Successfully removed Applications with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Interviews} business objects
	 * @return		List<Candidate>

    @GetMapping("/Interviews")
    public List<Candidate> Interviews(UUID parentId) {
		List<Candidate> candidateList = load(parentId).getInterviews;
		return candidateList;
	}

    /**
     * save Interviews on Candidate
     * @param		command AssignInterviewsToCandidateCommand
     */     
	@PutMapping("/addToInterviews")
	public void addToInterviews( @RequestBody(required=true) AssignInterviewsToCandidateCommand command ) {
		service.addToInterviews( command );
		LOGGER.info( "Successfully added Interviews with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Interviews on Candidate
     * @param		command RemoveInterviewsFromCandidateCommand
     */     	
	@PutMapping("/removeFromInterviews")
	public void removeFromInterviews( 	@RequestBody(required=true) RemoveInterviewsFromCandidateCommand command )
	{		
		service.removeFromInterviews( command );
		LOGGER.info( "Successfully removed Interviews with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Offers} business objects
	 * @return		List<Candidate>

    @GetMapping("/Offers")
    public List<Candidate> Offers(UUID parentId) {
		List<Candidate> candidateList = load(parentId).getOffers;
		return candidateList;
	}

    /**
     * save Offers on Candidate
     * @param		command AssignOffersToCandidateCommand
     */     
	@PutMapping("/addToOffers")
	public void addToOffers( @RequestBody(required=true) AssignOffersToCandidateCommand command ) {
		service.addToOffers( command );
		LOGGER.info( "Successfully added Offers with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Offers on Candidate
     * @param		command RemoveOffersFromCandidateCommand
     */     	
	@PutMapping("/removeFromOffers")
	public void removeFromOffers( 	@RequestBody(required=true) RemoveOffersFromCandidateCommand command )
	{		
		service.removeFromOffers( command );
		LOGGER.info( "Successfully removed Offers with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Documents} business objects
	 * @return		List<Candidate>

    @GetMapping("/Documents")
    public List<Candidate> Documents(UUID parentId) {
		List<Candidate> candidateList = load(parentId).getDocuments;
		return candidateList;
	}

    /**
     * save Documents on Candidate
     * @param		command AssignDocumentsToCandidateCommand
     */     
	@PutMapping("/addToDocuments")
	public void addToDocuments( @RequestBody(required=true) AssignDocumentsToCandidateCommand command ) {
		service.addToDocuments( command );
		LOGGER.info( "Successfully added Documents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Documents on Candidate
     * @param		command RemoveDocumentsFromCandidateCommand
     */     	
	@PutMapping("/removeFromDocuments")
	public void removeFromDocuments( 	@RequestBody(required=true) RemoveDocumentsFromCandidateCommand command )
	{		
		service.removeFromDocuments( command );
		LOGGER.info( "Successfully removed Documents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Candidate candidate = null;
	protected CandidateService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CandidateRestController.class.getName());
    
}
