
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CompensationPackageRestController as REST API
 *
 * <p>Exposes REST endpoints for the CompensationPackage entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CompensationPackageService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCompensationPackageCommand</li>
 *      <li></li>UpdateCompensationPackageCommand</li>
 *      <liDeleteCompensationPackageCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/CompensationPackage")
public class CompensationPackageRestController extends BaseSpringRestController {

	public CompensationPackageRestController( CompensationPackageService service ) {
		this.service = service;
	}
    /**
     * Handles create a CompensationPackage.  if not key provided, calls create, otherwise calls save
     * @param		CompensationPackage	compensationPackage
     * @return		CompensationPackage 
     */
	@PostMapping("/create")
    public CompensationPackage create( @RequestBody(required=true) CreateCompensationPackageCommand command ) {
    	CompensationPackage entity = null;

		entity = service.createCompensationPackage( command );
		LOGGER.info( "Successfully created CompensationPackage with Id " + entity.getCompensationPackageId()  );

		return entity;
    }

    /**
     * Handles updating a CompensationPackage.  if no key provided, calls create, otherwise calls save
     * @param		CompensationPackage compensationPackage
     * @return		CompensationPackage
     */
	@PutMapping("/update")
    public CompensationPackage update( @RequestBody(required=true) UpdateCompensationPackageCommand command ) {
		CompensationPackage entity = null;

		entity = service.updateCompensationPackage(command);
		LOGGER.info( "Successfully updated CompensationPackage with Id " + command.getCompensationPackageId()  );

		return entity;
	}
 
    /**
     * Handles deleting a CompensationPackage entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCompensationPackageCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted CompensationPackage with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a CompensationPackage using a UUID
     * @param		UUID uuid 
     * @return		CompensationPackage
     */    
    @GetMapping("/get")
    public CompensationPackage get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	CompensationPackage entity = service.getCompensationPackage( new CompensationPackageFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded CompensationPackage with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all CompensationPackage business objects
     * @return		List<CompensationPackage>
     */
    @GetMapping("/")
    public List<CompensationPackage> getAll() {
    	List<CompensationPackage> compensationPackageList = null;

		compensationPackageList = service.getAllCompensationPackage();
		LOGGER.info( "successfully loaded all CompensationPackages" );

        return compensationPackageList;
                            
    }

	/**
	 * Handles loading all Contract} business objects
	 * @return		List<CompensationPackage>

    @GetMapping("/Contract")
    public List<CompensationPackage> Contract(UUID parentId) {
		List<CompensationPackage> compensationPackageList = load(parentId).getContract;
		return compensationPackageList;
	}
	 */
    /**
     * save Contract on CompensationPackage
     * @param		command AssignContractToCompensationPackageCommand
     */     
	@PutMapping("/assignContract")
	public void assignContract( @RequestBody AssignContractToCompensationPackageCommand command ) {
		service.assignContract( command );
		LOGGER.info( "Successfully assigned Contract with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Contract on CompensationPackage
     * @param		 command UnAssignContractFromCompensationPackageCommand
     */     
	@PutMapping("/unassignContract")
	public void unAssignContract( @RequestBody(required=true)  UnAssignContractFromCompensationPackageCommand command ) {
		service.unAssignContract( command );
		LOGGER.info( "Successfully unassigned Contract with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all SalaryComponents} business objects
	 * @return		List<CompensationPackage>

    @GetMapping("/SalaryComponents")
    public List<CompensationPackage> SalaryComponents(UUID parentId) {
		List<CompensationPackage> compensationPackageList = load(parentId).getSalaryComponents;
		return compensationPackageList;
	}

    /**
     * save SalaryComponents on CompensationPackage
     * @param		command AssignSalaryComponentsToCompensationPackageCommand
     */     
	@PutMapping("/addToSalaryComponents")
	public void addToSalaryComponents( @RequestBody(required=true) AssignSalaryComponentsToCompensationPackageCommand command ) {
		service.addToSalaryComponents( command );
		LOGGER.info( "Successfully added SalaryComponents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove SalaryComponents on CompensationPackage
     * @param		command RemoveSalaryComponentsFromCompensationPackageCommand
     */     	
	@PutMapping("/removeFromSalaryComponents")
	public void removeFromSalaryComponents( 	@RequestBody(required=true) RemoveSalaryComponentsFromCompensationPackageCommand command )
	{		
		service.removeFromSalaryComponents( command );
		LOGGER.info( "Successfully removed SalaryComponents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all BonusPlans} business objects
	 * @return		List<CompensationPackage>

    @GetMapping("/BonusPlans")
    public List<CompensationPackage> BonusPlans(UUID parentId) {
		List<CompensationPackage> compensationPackageList = load(parentId).getBonusPlans;
		return compensationPackageList;
	}

    /**
     * save BonusPlans on CompensationPackage
     * @param		command AssignBonusPlansToCompensationPackageCommand
     */     
	@PutMapping("/addToBonusPlans")
	public void addToBonusPlans( @RequestBody(required=true) AssignBonusPlansToCompensationPackageCommand command ) {
		service.addToBonusPlans( command );
		LOGGER.info( "Successfully added BonusPlans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove BonusPlans on CompensationPackage
     * @param		command RemoveBonusPlansFromCompensationPackageCommand
     */     	
	@PutMapping("/removeFromBonusPlans")
	public void removeFromBonusPlans( 	@RequestBody(required=true) RemoveBonusPlansFromCompensationPackageCommand command )
	{		
		service.removeFromBonusPlans( command );
		LOGGER.info( "Successfully removed BonusPlans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all EquityGrants} business objects
	 * @return		List<CompensationPackage>

    @GetMapping("/EquityGrants")
    public List<CompensationPackage> EquityGrants(UUID parentId) {
		List<CompensationPackage> compensationPackageList = load(parentId).getEquityGrants;
		return compensationPackageList;
	}

    /**
     * save EquityGrants on CompensationPackage
     * @param		command AssignEquityGrantsToCompensationPackageCommand
     */     
	@PutMapping("/addToEquityGrants")
	public void addToEquityGrants( @RequestBody(required=true) AssignEquityGrantsToCompensationPackageCommand command ) {
		service.addToEquityGrants( command );
		LOGGER.info( "Successfully added EquityGrants with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove EquityGrants on CompensationPackage
     * @param		command RemoveEquityGrantsFromCompensationPackageCommand
     */     	
	@PutMapping("/removeFromEquityGrants")
	public void removeFromEquityGrants( 	@RequestBody(required=true) RemoveEquityGrantsFromCompensationPackageCommand command )
	{		
		service.removeFromEquityGrants( command );
		LOGGER.info( "Successfully removed EquityGrants with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected CompensationPackage compensationPackage = null;
	protected CompensationPackageService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CompensationPackageRestController.class.getName());
    
}
