
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CostCenterRestController as REST API
 *
 * <p>Exposes REST endpoints for the CostCenter entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CostCenterService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCostCenterCommand</li>
 *      <li></li>UpdateCostCenterCommand</li>
 *      <liDeleteCostCenterCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/CostCenter")
public class CostCenterRestController extends BaseSpringRestController {

	public CostCenterRestController( CostCenterService service ) {
		this.service = service;
	}
    /**
     * Handles create a CostCenter.  if not key provided, calls create, otherwise calls save
     * @param		CostCenter	costCenter
     * @return		CostCenter 
     */
	@PostMapping("/create")
    public CostCenter create( @RequestBody(required=true) CreateCostCenterCommand command ) {
    	CostCenter entity = null;

		entity = service.createCostCenter( command );
		LOGGER.info( "Successfully created CostCenter with Id " + entity.getCostCenterId()  );

		return entity;
    }

    /**
     * Handles updating a CostCenter.  if no key provided, calls create, otherwise calls save
     * @param		CostCenter costCenter
     * @return		CostCenter
     */
	@PutMapping("/update")
    public CostCenter update( @RequestBody(required=true) UpdateCostCenterCommand command ) {
		CostCenter entity = null;

		entity = service.updateCostCenter(command);
		LOGGER.info( "Successfully updated CostCenter with Id " + command.getCostCenterId()  );

		return entity;
	}
 
    /**
     * Handles deleting a CostCenter entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCostCenterCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted CostCenter with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a CostCenter using a UUID
     * @param		UUID uuid 
     * @return		CostCenter
     */    
    @GetMapping("/get")
    public CostCenter get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	CostCenter entity = service.getCostCenter( new CostCenterFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded CostCenter with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all CostCenter business objects
     * @return		List<CostCenter>
     */
    @GetMapping("/")
    public List<CostCenter> getAll() {
    	List<CostCenter> costCenterList = null;

		costCenterList = service.getAllCostCenter();
		LOGGER.info( "successfully loaded all CostCenters" );

        return costCenterList;
                            
    }

	/**
	 * Handles loading all Organization} business objects
	 * @return		List<CostCenter>

    @GetMapping("/Organization")
    public List<CostCenter> Organization(UUID parentId) {
		List<CostCenter> costCenterList = load(parentId).getOrganization;
		return costCenterList;
	}
	 */
    /**
     * save Organization on CostCenter
     * @param		command AssignOrganizationToCostCenterCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToCostCenterCommand command ) {
		service.assignOrganization( command );
		LOGGER.info( "Successfully assigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Organization on CostCenter
     * @param		 command UnAssignOrganizationFromCostCenterCommand
     */     
	@PutMapping("/unassignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromCostCenterCommand command ) {
		service.unAssignOrganization( command );
		LOGGER.info( "Successfully unassigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Departments} business objects
	 * @return		List<CostCenter>

    @GetMapping("/Departments")
    public List<CostCenter> Departments(UUID parentId) {
		List<CostCenter> costCenterList = load(parentId).getDepartments;
		return costCenterList;
	}

    /**
     * save Departments on CostCenter
     * @param		command AssignDepartmentsToCostCenterCommand
     */     
	@PutMapping("/addToDepartments")
	public void addToDepartments( @RequestBody(required=true) AssignDepartmentsToCostCenterCommand command ) {
		service.addToDepartments( command );
		LOGGER.info( "Successfully added Departments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Departments on CostCenter
     * @param		command RemoveDepartmentsFromCostCenterCommand
     */     	
	@PutMapping("/removeFromDepartments")
	public void removeFromDepartments( 	@RequestBody(required=true) RemoveDepartmentsFromCostCenterCommand command )
	{		
		service.removeFromDepartments( command );
		LOGGER.info( "Successfully removed Departments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Positions} business objects
	 * @return		List<CostCenter>

    @GetMapping("/Positions")
    public List<CostCenter> Positions(UUID parentId) {
		List<CostCenter> costCenterList = load(parentId).getPositions;
		return costCenterList;
	}

    /**
     * save Positions on CostCenter
     * @param		command AssignPositionsToCostCenterCommand
     */     
	@PutMapping("/addToPositions")
	public void addToPositions( @RequestBody(required=true) AssignPositionsToCostCenterCommand command ) {
		service.addToPositions( command );
		LOGGER.info( "Successfully added Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Positions on CostCenter
     * @param		command RemovePositionsFromCostCenterCommand
     */     	
	@PutMapping("/removeFromPositions")
	public void removeFromPositions( 	@RequestBody(required=true) RemovePositionsFromCostCenterCommand command )
	{		
		service.removeFromPositions( command );
		LOGGER.info( "Successfully removed Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Employees} business objects
	 * @return		List<CostCenter>

    @GetMapping("/Employees")
    public List<CostCenter> Employees(UUID parentId) {
		List<CostCenter> costCenterList = load(parentId).getEmployees;
		return costCenterList;
	}

    /**
     * save Employees on CostCenter
     * @param		command AssignEmployeesToCostCenterCommand
     */     
	@PutMapping("/addToEmployees")
	public void addToEmployees( @RequestBody(required=true) AssignEmployeesToCostCenterCommand command ) {
		service.addToEmployees( command );
		LOGGER.info( "Successfully added Employees with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Employees on CostCenter
     * @param		command RemoveEmployeesFromCostCenterCommand
     */     	
	@PutMapping("/removeFromEmployees")
	public void removeFromEmployees( 	@RequestBody(required=true) RemoveEmployeesFromCostCenterCommand command )
	{		
		service.removeFromEmployees( command );
		LOGGER.info( "Successfully removed Employees with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected CostCenter costCenter = null;
	protected CostCenterService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CostCenterRestController.class.getName());
    
}
