
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * DepartmentRestController as REST API
 *
 * <p>Exposes REST endpoints for the Department entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DepartmentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDepartmentCommand</li>
 *      <li></li>UpdateDepartmentCommand</li>
 *      <liDeleteDepartmentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Department")
public class DepartmentRestController extends BaseSpringRestController {

	public DepartmentRestController( DepartmentService service ) {
		this.service = service;
	}
    /**
     * Handles create a Department.  if not key provided, calls create, otherwise calls save
     * @param		Department	department
     * @return		Department 
     */
	@PostMapping("/create")
    public Department create( @RequestBody(required=true) CreateDepartmentCommand command ) {
    	Department entity = null;

		entity = service.createDepartment( command );
		LOGGER.info( "Successfully created Department with Id " + entity.getDepartmentId()  );

		return entity;
    }

    /**
     * Handles updating a Department.  if no key provided, calls create, otherwise calls save
     * @param		Department department
     * @return		Department
     */
	@PutMapping("/update")
    public Department update( @RequestBody(required=true) UpdateDepartmentCommand command ) {
		Department entity = null;

		entity = service.updateDepartment(command);
		LOGGER.info( "Successfully updated Department with Id " + command.getDepartmentId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Department entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteDepartmentCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Department with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Department using a UUID
     * @param		UUID uuid 
     * @return		Department
     */    
    @GetMapping("/get")
    public Department get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Department entity = service.getDepartment( new DepartmentFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Department with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Department business objects
     * @return		List<Department>
     */
    @GetMapping("/")
    public List<Department> getAll() {
    	List<Department> departmentList = null;

		departmentList = service.getAllDepartment();
		LOGGER.info( "successfully loaded all Departments" );

        return departmentList;
                            
    }

	/**
	 * Handles loading all Organization} business objects
	 * @return		List<Department>

    @GetMapping("/Organization")
    public List<Department> Organization(UUID parentId) {
		List<Department> departmentList = load(parentId).getOrganization;
		return departmentList;
	}
	 */
    /**
     * save Organization on Department
     * @param		command AssignOrganizationToDepartmentCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToDepartmentCommand command ) {
		service.assignOrganization( command );
		LOGGER.info( "Successfully assigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Organization on Department
     * @param		 command UnAssignOrganizationFromDepartmentCommand
     */     
	@PutMapping("/unassignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromDepartmentCommand command ) {
		service.unAssignOrganization( command );
		LOGGER.info( "Successfully unassigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Manager} business objects
	 * @return		List<Department>

    @GetMapping("/Manager")
    public List<Department> Manager(UUID parentId) {
		List<Department> departmentList = load(parentId).getManager;
		return departmentList;
	}
	 */
    /**
     * save Manager on Department
     * @param		command AssignManagerToDepartmentCommand
     */     
	@PutMapping("/assignManager")
	public void assignManager( @RequestBody AssignManagerToDepartmentCommand command ) {
		service.assignManager( command );
		LOGGER.info( "Successfully assigned Manager with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Manager on Department
     * @param		 command UnAssignManagerFromDepartmentCommand
     */     
	@PutMapping("/unassignManager")
	public void unAssignManager( @RequestBody(required=true)  UnAssignManagerFromDepartmentCommand command ) {
		service.unAssignManager( command );
		LOGGER.info( "Successfully unassigned Manager with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all CostCenter} business objects
	 * @return		List<Department>

    @GetMapping("/CostCenter")
    public List<Department> CostCenter(UUID parentId) {
		List<Department> departmentList = load(parentId).getCostCenter;
		return departmentList;
	}
	 */
    /**
     * save CostCenter on Department
     * @param		command AssignCostCenterToDepartmentCommand
     */     
	@PutMapping("/assignCostCenter")
	public void assignCostCenter( @RequestBody AssignCostCenterToDepartmentCommand command ) {
		service.assignCostCenter( command );
		LOGGER.info( "Successfully assigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign CostCenter on Department
     * @param		 command UnAssignCostCenterFromDepartmentCommand
     */     
	@PutMapping("/unassignCostCenter")
	public void unAssignCostCenter( @RequestBody(required=true)  UnAssignCostCenterFromDepartmentCommand command ) {
		service.unAssignCostCenter( command );
		LOGGER.info( "Successfully unassigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Positions} business objects
	 * @return		List<Department>

    @GetMapping("/Positions")
    public List<Department> Positions(UUID parentId) {
		List<Department> departmentList = load(parentId).getPositions;
		return departmentList;
	}

    /**
     * save Positions on Department
     * @param		command AssignPositionsToDepartmentCommand
     */     
	@PutMapping("/addToPositions")
	public void addToPositions( @RequestBody(required=true) AssignPositionsToDepartmentCommand command ) {
		service.addToPositions( command );
		LOGGER.info( "Successfully added Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Positions on Department
     * @param		command RemovePositionsFromDepartmentCommand
     */     	
	@PutMapping("/removeFromPositions")
	public void removeFromPositions( 	@RequestBody(required=true) RemovePositionsFromDepartmentCommand command )
	{		
		service.removeFromPositions( command );
		LOGGER.info( "Successfully removed Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Employees} business objects
	 * @return		List<Department>

    @GetMapping("/Employees")
    public List<Department> Employees(UUID parentId) {
		List<Department> departmentList = load(parentId).getEmployees;
		return departmentList;
	}

    /**
     * save Employees on Department
     * @param		command AssignEmployeesToDepartmentCommand
     */     
	@PutMapping("/addToEmployees")
	public void addToEmployees( @RequestBody(required=true) AssignEmployeesToDepartmentCommand command ) {
		service.addToEmployees( command );
		LOGGER.info( "Successfully added Employees with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Employees on Department
     * @param		command RemoveEmployeesFromDepartmentCommand
     */     	
	@PutMapping("/removeFromEmployees")
	public void removeFromEmployees( 	@RequestBody(required=true) RemoveEmployeesFromDepartmentCommand command )
	{		
		service.removeFromEmployees( command );
		LOGGER.info( "Successfully removed Employees with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Department department = null;
	protected DepartmentService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(DepartmentRestController.class.getName());
    
}
