
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * EmploymentContractRestController as REST API
 *
 * <p>Exposes REST endpoints for the EmploymentContract entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	EmploymentContractService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateEmploymentContractCommand</li>
 *      <li></li>UpdateEmploymentContractCommand</li>
 *      <liDeleteEmploymentContractCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/EmploymentContract")
public class EmploymentContractRestController extends BaseSpringRestController {

	public EmploymentContractRestController( EmploymentContractService service ) {
		this.service = service;
	}
    /**
     * Handles create a EmploymentContract.  if not key provided, calls create, otherwise calls save
     * @param		EmploymentContract	employmentContract
     * @return		EmploymentContract 
     */
	@PostMapping("/create")
    public EmploymentContract create( @RequestBody(required=true) CreateEmploymentContractCommand command ) {
    	EmploymentContract entity = null;

		entity = service.createEmploymentContract( command );
		LOGGER.info( "Successfully created EmploymentContract with Id " + entity.getEmploymentContractId()  );

		return entity;
    }

    /**
     * Handles updating a EmploymentContract.  if no key provided, calls create, otherwise calls save
     * @param		EmploymentContract employmentContract
     * @return		EmploymentContract
     */
	@PutMapping("/update")
    public EmploymentContract update( @RequestBody(required=true) UpdateEmploymentContractCommand command ) {
		EmploymentContract entity = null;

		entity = service.updateEmploymentContract(command);
		LOGGER.info( "Successfully updated EmploymentContract with Id " + command.getEmploymentContractId()  );

		return entity;
	}
 
    /**
     * Handles deleting a EmploymentContract entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteEmploymentContractCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted EmploymentContract with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a EmploymentContract using a UUID
     * @param		UUID uuid 
     * @return		EmploymentContract
     */    
    @GetMapping("/get")
    public EmploymentContract get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	EmploymentContract entity = service.getEmploymentContract( new EmploymentContractFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded EmploymentContract with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all EmploymentContract business objects
     * @return		List<EmploymentContract>
     */
    @GetMapping("/")
    public List<EmploymentContract> getAll() {
    	List<EmploymentContract> employmentContractList = null;

		employmentContractList = service.getAllEmploymentContract();
		LOGGER.info( "successfully loaded all EmploymentContracts" );

        return employmentContractList;
                            
    }

	/**
	 * Handles loading all Employee} business objects
	 * @return		List<EmploymentContract>

    @GetMapping("/Employee")
    public List<EmploymentContract> Employee(UUID parentId) {
		List<EmploymentContract> employmentContractList = load(parentId).getEmployee;
		return employmentContractList;
	}
	 */
    /**
     * save Employee on EmploymentContract
     * @param		command AssignEmployeeToEmploymentContractCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToEmploymentContractCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on EmploymentContract
     * @param		 command UnAssignEmployeeFromEmploymentContractCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromEmploymentContractCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all CompensationPackage} business objects
	 * @return		List<EmploymentContract>

    @GetMapping("/CompensationPackage")
    public List<EmploymentContract> CompensationPackage(UUID parentId) {
		List<EmploymentContract> employmentContractList = load(parentId).getCompensationPackage;
		return employmentContractList;
	}
	 */
    /**
     * save CompensationPackage on EmploymentContract
     * @param		command AssignCompensationPackageToEmploymentContractCommand
     */     
	@PutMapping("/assignCompensationPackage")
	public void assignCompensationPackage( @RequestBody AssignCompensationPackageToEmploymentContractCommand command ) {
		service.assignCompensationPackage( command );
		LOGGER.info( "Successfully assigned CompensationPackage with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign CompensationPackage on EmploymentContract
     * @param		 command UnAssignCompensationPackageFromEmploymentContractCommand
     */     
	@PutMapping("/unassignCompensationPackage")
	public void unAssignCompensationPackage( @RequestBody(required=true)  UnAssignCompensationPackageFromEmploymentContractCommand command ) {
		service.unAssignCompensationPackage( command );
		LOGGER.info( "Successfully unassigned CompensationPackage with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all WorkSchedule} business objects
	 * @return		List<EmploymentContract>

    @GetMapping("/WorkSchedule")
    public List<EmploymentContract> WorkSchedule(UUID parentId) {
		List<EmploymentContract> employmentContractList = load(parentId).getWorkSchedule;
		return employmentContractList;
	}
	 */
    /**
     * save WorkSchedule on EmploymentContract
     * @param		command AssignWorkScheduleToEmploymentContractCommand
     */     
	@PutMapping("/assignWorkSchedule")
	public void assignWorkSchedule( @RequestBody AssignWorkScheduleToEmploymentContractCommand command ) {
		service.assignWorkSchedule( command );
		LOGGER.info( "Successfully assigned WorkSchedule with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign WorkSchedule on EmploymentContract
     * @param		 command UnAssignWorkScheduleFromEmploymentContractCommand
     */     
	@PutMapping("/unassignWorkSchedule")
	public void unAssignWorkSchedule( @RequestBody(required=true)  UnAssignWorkScheduleFromEmploymentContractCommand command ) {
		service.unAssignWorkSchedule( command );
		LOGGER.info( "Successfully unassigned WorkSchedule with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Location} business objects
	 * @return		List<EmploymentContract>

    @GetMapping("/Location")
    public List<EmploymentContract> Location(UUID parentId) {
		List<EmploymentContract> employmentContractList = load(parentId).getLocation;
		return employmentContractList;
	}
	 */
    /**
     * save Location on EmploymentContract
     * @param		command AssignLocationToEmploymentContractCommand
     */     
	@PutMapping("/assignLocation")
	public void assignLocation( @RequestBody AssignLocationToEmploymentContractCommand command ) {
		service.assignLocation( command );
		LOGGER.info( "Successfully assigned Location with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Location on EmploymentContract
     * @param		 command UnAssignLocationFromEmploymentContractCommand
     */     
	@PutMapping("/unassignLocation")
	public void unAssignLocation( @RequestBody(required=true)  UnAssignLocationFromEmploymentContractCommand command ) {
		service.unAssignLocation( command );
		LOGGER.info( "Successfully unassigned Location with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all PayrollCalendar} business objects
	 * @return		List<EmploymentContract>

    @GetMapping("/PayrollCalendar")
    public List<EmploymentContract> PayrollCalendar(UUID parentId) {
		List<EmploymentContract> employmentContractList = load(parentId).getPayrollCalendar;
		return employmentContractList;
	}
	 */
    /**
     * save PayrollCalendar on EmploymentContract
     * @param		command AssignPayrollCalendarToEmploymentContractCommand
     */     
	@PutMapping("/assignPayrollCalendar")
	public void assignPayrollCalendar( @RequestBody AssignPayrollCalendarToEmploymentContractCommand command ) {
		service.assignPayrollCalendar( command );
		LOGGER.info( "Successfully assigned PayrollCalendar with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign PayrollCalendar on EmploymentContract
     * @param		 command UnAssignPayrollCalendarFromEmploymentContractCommand
     */     
	@PutMapping("/unassignPayrollCalendar")
	public void unAssignPayrollCalendar( @RequestBody(required=true)  UnAssignPayrollCalendarFromEmploymentContractCommand command ) {
		service.unAssignPayrollCalendar( command );
		LOGGER.info( "Successfully unassigned PayrollCalendar with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected EmploymentContract employmentContract = null;
	protected EmploymentContractService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(EmploymentContractRestController.class.getName());
    
}
