
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * GoalRestController as REST API
 *
 * <p>Exposes REST endpoints for the Goal entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	GoalService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateGoalCommand</li>
 *      <li></li>UpdateGoalCommand</li>
 *      <liDeleteGoalCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Goal")
public class GoalRestController extends BaseSpringRestController {

	public GoalRestController( GoalService service ) {
		this.service = service;
	}
    /**
     * Handles create a Goal.  if not key provided, calls create, otherwise calls save
     * @param		Goal	goal
     * @return		Goal 
     */
	@PostMapping("/create")
    public Goal create( @RequestBody(required=true) CreateGoalCommand command ) {
    	Goal entity = null;

		entity = service.createGoal( command );
		LOGGER.info( "Successfully created Goal with Id " + entity.getGoalId()  );

		return entity;
    }

    /**
     * Handles updating a Goal.  if no key provided, calls create, otherwise calls save
     * @param		Goal goal
     * @return		Goal
     */
	@PutMapping("/update")
    public Goal update( @RequestBody(required=true) UpdateGoalCommand command ) {
		Goal entity = null;

		entity = service.updateGoal(command);
		LOGGER.info( "Successfully updated Goal with Id " + command.getGoalId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Goal entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteGoalCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Goal with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Goal using a UUID
     * @param		UUID uuid 
     * @return		Goal
     */    
    @GetMapping("/get")
    public Goal get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Goal entity = service.getGoal( new GoalFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Goal with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Goal business objects
     * @return		List<Goal>
     */
    @GetMapping("/")
    public List<Goal> getAll() {
    	List<Goal> goalList = null;

		goalList = service.getAllGoal();
		LOGGER.info( "successfully loaded all Goals" );

        return goalList;
                            
    }

	/**
	 * Handles loading all Employee} business objects
	 * @return		List<Goal>

    @GetMapping("/Employee")
    public List<Goal> Employee(UUID parentId) {
		List<Goal> goalList = load(parentId).getEmployee;
		return goalList;
	}
	 */
    /**
     * save Employee on Goal
     * @param		command AssignEmployeeToGoalCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToGoalCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on Goal
     * @param		 command UnAssignEmployeeFromGoalCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromGoalCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Cycle} business objects
	 * @return		List<Goal>

    @GetMapping("/Cycle")
    public List<Goal> Cycle(UUID parentId) {
		List<Goal> goalList = load(parentId).getCycle;
		return goalList;
	}
	 */
    /**
     * save Cycle on Goal
     * @param		command AssignCycleToGoalCommand
     */     
	@PutMapping("/assignCycle")
	public void assignCycle( @RequestBody AssignCycleToGoalCommand command ) {
		service.assignCycle( command );
		LOGGER.info( "Successfully assigned Cycle with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Cycle on Goal
     * @param		 command UnAssignCycleFromGoalCommand
     */     
	@PutMapping("/unassignCycle")
	public void unAssignCycle( @RequestBody(required=true)  UnAssignCycleFromGoalCommand command ) {
		service.unAssignCycle( command );
		LOGGER.info( "Successfully unassigned Cycle with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all ParentGoal} business objects
	 * @return		List<Goal>

    @GetMapping("/ParentGoal")
    public List<Goal> ParentGoal(UUID parentId) {
		List<Goal> goalList = load(parentId).getParentGoal;
		return goalList;
	}
	 */
    /**
     * save ParentGoal on Goal
     * @param		command AssignParentGoalToGoalCommand
     */     
	@PutMapping("/assignParentGoal")
	public void assignParentGoal( @RequestBody AssignParentGoalToGoalCommand command ) {
		service.assignParentGoal( command );
		LOGGER.info( "Successfully assigned ParentGoal with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ParentGoal on Goal
     * @param		 command UnAssignParentGoalFromGoalCommand
     */     
	@PutMapping("/unassignParentGoal")
	public void unAssignParentGoal( @RequestBody(required=true)  UnAssignParentGoalFromGoalCommand command ) {
		service.unAssignParentGoal( command );
		LOGGER.info( "Successfully unassigned ParentGoal with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all ChildGoals} business objects
	 * @return		List<Goal>

    @GetMapping("/ChildGoals")
    public List<Goal> ChildGoals(UUID parentId) {
		List<Goal> goalList = load(parentId).getChildGoals;
		return goalList;
	}

    /**
     * save ChildGoals on Goal
     * @param		command AssignChildGoalsToGoalCommand
     */     
	@PutMapping("/addToChildGoals")
	public void addToChildGoals( @RequestBody(required=true) AssignChildGoalsToGoalCommand command ) {
		service.addToChildGoals( command );
		LOGGER.info( "Successfully added ChildGoals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove ChildGoals on Goal
     * @param		command RemoveChildGoalsFromGoalCommand
     */     	
	@PutMapping("/removeFromChildGoals")
	public void removeFromChildGoals( 	@RequestBody(required=true) RemoveChildGoalsFromGoalCommand command )
	{		
		service.removeFromChildGoals( command );
		LOGGER.info( "Successfully removed ChildGoals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Goal goal = null;
	protected GoalService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(GoalRestController.class.getName());
    
}
