
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * JobApplicationRestController as REST API
 *
 * <p>Exposes REST endpoints for the JobApplication entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	JobApplicationService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateJobApplicationCommand</li>
 *      <li></li>UpdateJobApplicationCommand</li>
 *      <liDeleteJobApplicationCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/JobApplication")
public class JobApplicationRestController extends BaseSpringRestController {

	public JobApplicationRestController( JobApplicationService service ) {
		this.service = service;
	}
    /**
     * Handles create a JobApplication.  if not key provided, calls create, otherwise calls save
     * @param		JobApplication	jobApplication
     * @return		JobApplication 
     */
	@PostMapping("/create")
    public JobApplication create( @RequestBody(required=true) CreateJobApplicationCommand command ) {
    	JobApplication entity = null;

		entity = service.createJobApplication( command );
		LOGGER.info( "Successfully created JobApplication with Id " + entity.getJobApplicationId()  );

		return entity;
    }

    /**
     * Handles updating a JobApplication.  if no key provided, calls create, otherwise calls save
     * @param		JobApplication jobApplication
     * @return		JobApplication
     */
	@PutMapping("/update")
    public JobApplication update( @RequestBody(required=true) UpdateJobApplicationCommand command ) {
		JobApplication entity = null;

		entity = service.updateJobApplication(command);
		LOGGER.info( "Successfully updated JobApplication with Id " + command.getJobApplicationId()  );

		return entity;
	}
 
    /**
     * Handles deleting a JobApplication entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteJobApplicationCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted JobApplication with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a JobApplication using a UUID
     * @param		UUID uuid 
     * @return		JobApplication
     */    
    @GetMapping("/get")
    public JobApplication get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	JobApplication entity = service.getJobApplication( new JobApplicationFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded JobApplication with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all JobApplication business objects
     * @return		List<JobApplication>
     */
    @GetMapping("/")
    public List<JobApplication> getAll() {
    	List<JobApplication> jobApplicationList = null;

		jobApplicationList = service.getAllJobApplication();
		LOGGER.info( "successfully loaded all JobApplications" );

        return jobApplicationList;
                            
    }

	/**
	 * Handles loading all Candidate} business objects
	 * @return		List<JobApplication>

    @GetMapping("/Candidate")
    public List<JobApplication> Candidate(UUID parentId) {
		List<JobApplication> jobApplicationList = load(parentId).getCandidate;
		return jobApplicationList;
	}
	 */
    /**
     * save Candidate on JobApplication
     * @param		command AssignCandidateToJobApplicationCommand
     */     
	@PutMapping("/assignCandidate")
	public void assignCandidate( @RequestBody AssignCandidateToJobApplicationCommand command ) {
		service.assignCandidate( command );
		LOGGER.info( "Successfully assigned Candidate with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Candidate on JobApplication
     * @param		 command UnAssignCandidateFromJobApplicationCommand
     */     
	@PutMapping("/unassignCandidate")
	public void unAssignCandidate( @RequestBody(required=true)  UnAssignCandidateFromJobApplicationCommand command ) {
		service.unAssignCandidate( command );
		LOGGER.info( "Successfully unassigned Candidate with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Requisition} business objects
	 * @return		List<JobApplication>

    @GetMapping("/Requisition")
    public List<JobApplication> Requisition(UUID parentId) {
		List<JobApplication> jobApplicationList = load(parentId).getRequisition;
		return jobApplicationList;
	}
	 */
    /**
     * save Requisition on JobApplication
     * @param		command AssignRequisitionToJobApplicationCommand
     */     
	@PutMapping("/assignRequisition")
	public void assignRequisition( @RequestBody AssignRequisitionToJobApplicationCommand command ) {
		service.assignRequisition( command );
		LOGGER.info( "Successfully assigned Requisition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Requisition on JobApplication
     * @param		 command UnAssignRequisitionFromJobApplicationCommand
     */     
	@PutMapping("/unassignRequisition")
	public void unAssignRequisition( @RequestBody(required=true)  UnAssignRequisitionFromJobApplicationCommand command ) {
		service.unAssignRequisition( command );
		LOGGER.info( "Successfully unassigned Requisition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Screenings} business objects
	 * @return		List<JobApplication>

    @GetMapping("/Screenings")
    public List<JobApplication> Screenings(UUID parentId) {
		List<JobApplication> jobApplicationList = load(parentId).getScreenings;
		return jobApplicationList;
	}

    /**
     * save Screenings on JobApplication
     * @param		command AssignScreeningsToJobApplicationCommand
     */     
	@PutMapping("/addToScreenings")
	public void addToScreenings( @RequestBody(required=true) AssignScreeningsToJobApplicationCommand command ) {
		service.addToScreenings( command );
		LOGGER.info( "Successfully added Screenings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Screenings on JobApplication
     * @param		command RemoveScreeningsFromJobApplicationCommand
     */     	
	@PutMapping("/removeFromScreenings")
	public void removeFromScreenings( 	@RequestBody(required=true) RemoveScreeningsFromJobApplicationCommand command )
	{		
		service.removeFromScreenings( command );
		LOGGER.info( "Successfully removed Screenings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected JobApplication jobApplication = null;
	protected JobApplicationService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(JobApplicationRestController.class.getName());
    
}
