
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * JobFamilyRestController as REST API
 *
 * <p>Exposes REST endpoints for the JobFamily entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	JobFamilyService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateJobFamilyCommand</li>
 *      <li></li>UpdateJobFamilyCommand</li>
 *      <liDeleteJobFamilyCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/JobFamily")
public class JobFamilyRestController extends BaseSpringRestController {

	public JobFamilyRestController( JobFamilyService service ) {
		this.service = service;
	}
    /**
     * Handles create a JobFamily.  if not key provided, calls create, otherwise calls save
     * @param		JobFamily	jobFamily
     * @return		JobFamily 
     */
	@PostMapping("/create")
    public JobFamily create( @RequestBody(required=true) CreateJobFamilyCommand command ) {
    	JobFamily entity = null;

		entity = service.createJobFamily( command );
		LOGGER.info( "Successfully created JobFamily with Id " + entity.getJobFamilyId()  );

		return entity;
    }

    /**
     * Handles updating a JobFamily.  if no key provided, calls create, otherwise calls save
     * @param		JobFamily jobFamily
     * @return		JobFamily
     */
	@PutMapping("/update")
    public JobFamily update( @RequestBody(required=true) UpdateJobFamilyCommand command ) {
		JobFamily entity = null;

		entity = service.updateJobFamily(command);
		LOGGER.info( "Successfully updated JobFamily with Id " + command.getJobFamilyId()  );

		return entity;
	}
 
    /**
     * Handles deleting a JobFamily entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteJobFamilyCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted JobFamily with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a JobFamily using a UUID
     * @param		UUID uuid 
     * @return		JobFamily
     */    
    @GetMapping("/get")
    public JobFamily get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	JobFamily entity = service.getJobFamily( new JobFamilyFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded JobFamily with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all JobFamily business objects
     * @return		List<JobFamily>
     */
    @GetMapping("/")
    public List<JobFamily> getAll() {
    	List<JobFamily> jobFamilyList = null;

		jobFamilyList = service.getAllJobFamily();
		LOGGER.info( "successfully loaded all JobFamilys" );

        return jobFamilyList;
                            
    }

	/**
	 * Handles loading all Organization} business objects
	 * @return		List<JobFamily>

    @GetMapping("/Organization")
    public List<JobFamily> Organization(UUID parentId) {
		List<JobFamily> jobFamilyList = load(parentId).getOrganization;
		return jobFamilyList;
	}
	 */
    /**
     * save Organization on JobFamily
     * @param		command AssignOrganizationToJobFamilyCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToJobFamilyCommand command ) {
		service.assignOrganization( command );
		LOGGER.info( "Successfully assigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Organization on JobFamily
     * @param		 command UnAssignOrganizationFromJobFamilyCommand
     */     
	@PutMapping("/unassignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromJobFamilyCommand command ) {
		service.unAssignOrganization( command );
		LOGGER.info( "Successfully unassigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all JobProfiles} business objects
	 * @return		List<JobFamily>

    @GetMapping("/JobProfiles")
    public List<JobFamily> JobProfiles(UUID parentId) {
		List<JobFamily> jobFamilyList = load(parentId).getJobProfiles;
		return jobFamilyList;
	}

    /**
     * save JobProfiles on JobFamily
     * @param		command AssignJobProfilesToJobFamilyCommand
     */     
	@PutMapping("/addToJobProfiles")
	public void addToJobProfiles( @RequestBody(required=true) AssignJobProfilesToJobFamilyCommand command ) {
		service.addToJobProfiles( command );
		LOGGER.info( "Successfully added JobProfiles with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove JobProfiles on JobFamily
     * @param		command RemoveJobProfilesFromJobFamilyCommand
     */     	
	@PutMapping("/removeFromJobProfiles")
	public void removeFromJobProfiles( 	@RequestBody(required=true) RemoveJobProfilesFromJobFamilyCommand command )
	{		
		service.removeFromJobProfiles( command );
		LOGGER.info( "Successfully removed JobProfiles with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected JobFamily jobFamily = null;
	protected JobFamilyService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(JobFamilyRestController.class.getName());
    
}
