
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * LeaveRequestRestController as REST API
 *
 * <p>Exposes REST endpoints for the LeaveRequest entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	LeaveRequestService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateLeaveRequestCommand</li>
 *      <li></li>UpdateLeaveRequestCommand</li>
 *      <liDeleteLeaveRequestCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/LeaveRequest")
public class LeaveRequestRestController extends BaseSpringRestController {

	public LeaveRequestRestController( LeaveRequestService service ) {
		this.service = service;
	}
    /**
     * Handles create a LeaveRequest.  if not key provided, calls create, otherwise calls save
     * @param		LeaveRequest	leaveRequest
     * @return		LeaveRequest 
     */
	@PostMapping("/create")
    public LeaveRequest create( @RequestBody(required=true) CreateLeaveRequestCommand command ) {
    	LeaveRequest entity = null;

		entity = service.createLeaveRequest( command );
		LOGGER.info( "Successfully created LeaveRequest with Id " + entity.getLeaveRequestId()  );

		return entity;
    }

    /**
     * Handles updating a LeaveRequest.  if no key provided, calls create, otherwise calls save
     * @param		LeaveRequest leaveRequest
     * @return		LeaveRequest
     */
	@PutMapping("/update")
    public LeaveRequest update( @RequestBody(required=true) UpdateLeaveRequestCommand command ) {
		LeaveRequest entity = null;

		entity = service.updateLeaveRequest(command);
		LOGGER.info( "Successfully updated LeaveRequest with Id " + command.getLeaveRequestId()  );

		return entity;
	}
 
    /**
     * Handles deleting a LeaveRequest entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteLeaveRequestCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted LeaveRequest with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a LeaveRequest using a UUID
     * @param		UUID uuid 
     * @return		LeaveRequest
     */    
    @GetMapping("/get")
    public LeaveRequest get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	LeaveRequest entity = service.getLeaveRequest( new LeaveRequestFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded LeaveRequest with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all LeaveRequest business objects
     * @return		List<LeaveRequest>
     */
    @GetMapping("/")
    public List<LeaveRequest> getAll() {
    	List<LeaveRequest> leaveRequestList = null;

		leaveRequestList = service.getAllLeaveRequest();
		LOGGER.info( "successfully loaded all LeaveRequests" );

        return leaveRequestList;
                            
    }

	/**
	 * Handles loading all Employee} business objects
	 * @return		List<LeaveRequest>

    @GetMapping("/Employee")
    public List<LeaveRequest> Employee(UUID parentId) {
		List<LeaveRequest> leaveRequestList = load(parentId).getEmployee;
		return leaveRequestList;
	}
	 */
    /**
     * save Employee on LeaveRequest
     * @param		command AssignEmployeeToLeaveRequestCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToLeaveRequestCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on LeaveRequest
     * @param		 command UnAssignEmployeeFromLeaveRequestCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromLeaveRequestCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all LeavePolicy} business objects
	 * @return		List<LeaveRequest>

    @GetMapping("/LeavePolicy")
    public List<LeaveRequest> LeavePolicy(UUID parentId) {
		List<LeaveRequest> leaveRequestList = load(parentId).getLeavePolicy;
		return leaveRequestList;
	}
	 */
    /**
     * save LeavePolicy on LeaveRequest
     * @param		command AssignLeavePolicyToLeaveRequestCommand
     */     
	@PutMapping("/assignLeavePolicy")
	public void assignLeavePolicy( @RequestBody AssignLeavePolicyToLeaveRequestCommand command ) {
		service.assignLeavePolicy( command );
		LOGGER.info( "Successfully assigned LeavePolicy with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign LeavePolicy on LeaveRequest
     * @param		 command UnAssignLeavePolicyFromLeaveRequestCommand
     */     
	@PutMapping("/unassignLeavePolicy")
	public void unAssignLeavePolicy( @RequestBody(required=true)  UnAssignLeavePolicyFromLeaveRequestCommand command ) {
		service.unAssignLeavePolicy( command );
		LOGGER.info( "Successfully unassigned LeavePolicy with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Approvals} business objects
	 * @return		List<LeaveRequest>

    @GetMapping("/Approvals")
    public List<LeaveRequest> Approvals(UUID parentId) {
		List<LeaveRequest> leaveRequestList = load(parentId).getApprovals;
		return leaveRequestList;
	}

    /**
     * save Approvals on LeaveRequest
     * @param		command AssignApprovalsToLeaveRequestCommand
     */     
	@PutMapping("/addToApprovals")
	public void addToApprovals( @RequestBody(required=true) AssignApprovalsToLeaveRequestCommand command ) {
		service.addToApprovals( command );
		LOGGER.info( "Successfully added Approvals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Approvals on LeaveRequest
     * @param		command RemoveApprovalsFromLeaveRequestCommand
     */     	
	@PutMapping("/removeFromApprovals")
	public void removeFromApprovals( 	@RequestBody(required=true) RemoveApprovalsFromLeaveRequestCommand command )
	{		
		service.removeFromApprovals( command );
		LOGGER.info( "Successfully removed Approvals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected LeaveRequest leaveRequest = null;
	protected LeaveRequestService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(LeaveRequestRestController.class.getName());
    
}
