
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * OfferRestController as REST API
 *
 * <p>Exposes REST endpoints for the Offer entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	OfferService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateOfferCommand</li>
 *      <li></li>UpdateOfferCommand</li>
 *      <liDeleteOfferCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Offer")
public class OfferRestController extends BaseSpringRestController {

	public OfferRestController( OfferService service ) {
		this.service = service;
	}
    /**
     * Handles create a Offer.  if not key provided, calls create, otherwise calls save
     * @param		Offer	offer
     * @return		Offer 
     */
	@PostMapping("/create")
    public Offer create( @RequestBody(required=true) CreateOfferCommand command ) {
    	Offer entity = null;

		entity = service.createOffer( command );
		LOGGER.info( "Successfully created Offer with Id " + entity.getOfferId()  );

		return entity;
    }

    /**
     * Handles updating a Offer.  if no key provided, calls create, otherwise calls save
     * @param		Offer offer
     * @return		Offer
     */
	@PutMapping("/update")
    public Offer update( @RequestBody(required=true) UpdateOfferCommand command ) {
		Offer entity = null;

		entity = service.updateOffer(command);
		LOGGER.info( "Successfully updated Offer with Id " + command.getOfferId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Offer entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteOfferCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Offer with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Offer using a UUID
     * @param		UUID uuid 
     * @return		Offer
     */    
    @GetMapping("/get")
    public Offer get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Offer entity = service.getOffer( new OfferFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Offer with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Offer business objects
     * @return		List<Offer>
     */
    @GetMapping("/")
    public List<Offer> getAll() {
    	List<Offer> offerList = null;

		offerList = service.getAllOffer();
		LOGGER.info( "successfully loaded all Offers" );

        return offerList;
                            
    }

	/**
	 * Handles loading all Requisition} business objects
	 * @return		List<Offer>

    @GetMapping("/Requisition")
    public List<Offer> Requisition(UUID parentId) {
		List<Offer> offerList = load(parentId).getRequisition;
		return offerList;
	}
	 */
    /**
     * save Requisition on Offer
     * @param		command AssignRequisitionToOfferCommand
     */     
	@PutMapping("/assignRequisition")
	public void assignRequisition( @RequestBody AssignRequisitionToOfferCommand command ) {
		service.assignRequisition( command );
		LOGGER.info( "Successfully assigned Requisition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Requisition on Offer
     * @param		 command UnAssignRequisitionFromOfferCommand
     */     
	@PutMapping("/unassignRequisition")
	public void unAssignRequisition( @RequestBody(required=true)  UnAssignRequisitionFromOfferCommand command ) {
		service.unAssignRequisition( command );
		LOGGER.info( "Successfully unassigned Requisition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Candidate} business objects
	 * @return		List<Offer>

    @GetMapping("/Candidate")
    public List<Offer> Candidate(UUID parentId) {
		List<Offer> offerList = load(parentId).getCandidate;
		return offerList;
	}
	 */
    /**
     * save Candidate on Offer
     * @param		command AssignCandidateToOfferCommand
     */     
	@PutMapping("/assignCandidate")
	public void assignCandidate( @RequestBody AssignCandidateToOfferCommand command ) {
		service.assignCandidate( command );
		LOGGER.info( "Successfully assigned Candidate with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Candidate on Offer
     * @param		 command UnAssignCandidateFromOfferCommand
     */     
	@PutMapping("/unassignCandidate")
	public void unAssignCandidate( @RequestBody(required=true)  UnAssignCandidateFromOfferCommand command ) {
		service.unAssignCandidate( command );
		LOGGER.info( "Successfully unassigned Candidate with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all ApprovedBy} business objects
	 * @return		List<Offer>

    @GetMapping("/ApprovedBy")
    public List<Offer> ApprovedBy(UUID parentId) {
		List<Offer> offerList = load(parentId).getApprovedBy;
		return offerList;
	}
	 */
    /**
     * save ApprovedBy on Offer
     * @param		command AssignApprovedByToOfferCommand
     */     
	@PutMapping("/assignApprovedBy")
	public void assignApprovedBy( @RequestBody AssignApprovedByToOfferCommand command ) {
		service.assignApprovedBy( command );
		LOGGER.info( "Successfully assigned ApprovedBy with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ApprovedBy on Offer
     * @param		 command UnAssignApprovedByFromOfferCommand
     */     
	@PutMapping("/unassignApprovedBy")
	public void unAssignApprovedBy( @RequestBody(required=true)  UnAssignApprovedByFromOfferCommand command ) {
		service.unAssignApprovedBy( command );
		LOGGER.info( "Successfully unassigned ApprovedBy with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Contract} business objects
	 * @return		List<Offer>

    @GetMapping("/Contract")
    public List<Offer> Contract(UUID parentId) {
		List<Offer> offerList = load(parentId).getContract;
		return offerList;
	}
	 */
    /**
     * save Contract on Offer
     * @param		command AssignContractToOfferCommand
     */     
	@PutMapping("/assignContract")
	public void assignContract( @RequestBody AssignContractToOfferCommand command ) {
		service.assignContract( command );
		LOGGER.info( "Successfully assigned Contract with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Contract on Offer
     * @param		 command UnAssignContractFromOfferCommand
     */     
	@PutMapping("/unassignContract")
	public void unAssignContract( @RequestBody(required=true)  UnAssignContractFromOfferCommand command ) {
		service.unAssignContract( command );
		LOGGER.info( "Successfully unassigned Contract with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Offer offer = null;
	protected OfferService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(OfferRestController.class.getName());
    
}
