
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * OnboardingTaskRestController as REST API
 *
 * <p>Exposes REST endpoints for the OnboardingTask entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	OnboardingTaskService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateOnboardingTaskCommand</li>
 *      <li></li>UpdateOnboardingTaskCommand</li>
 *      <liDeleteOnboardingTaskCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/OnboardingTask")
public class OnboardingTaskRestController extends BaseSpringRestController {

	public OnboardingTaskRestController( OnboardingTaskService service ) {
		this.service = service;
	}
    /**
     * Handles create a OnboardingTask.  if not key provided, calls create, otherwise calls save
     * @param		OnboardingTask	onboardingTask
     * @return		OnboardingTask 
     */
	@PostMapping("/create")
    public OnboardingTask create( @RequestBody(required=true) CreateOnboardingTaskCommand command ) {
    	OnboardingTask entity = null;

		entity = service.createOnboardingTask( command );
		LOGGER.info( "Successfully created OnboardingTask with Id " + entity.getOnboardingTaskId()  );

		return entity;
    }

    /**
     * Handles updating a OnboardingTask.  if no key provided, calls create, otherwise calls save
     * @param		OnboardingTask onboardingTask
     * @return		OnboardingTask
     */
	@PutMapping("/update")
    public OnboardingTask update( @RequestBody(required=true) UpdateOnboardingTaskCommand command ) {
		OnboardingTask entity = null;

		entity = service.updateOnboardingTask(command);
		LOGGER.info( "Successfully updated OnboardingTask with Id " + command.getOnboardingTaskId()  );

		return entity;
	}
 
    /**
     * Handles deleting a OnboardingTask entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteOnboardingTaskCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted OnboardingTask with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a OnboardingTask using a UUID
     * @param		UUID uuid 
     * @return		OnboardingTask
     */    
    @GetMapping("/get")
    public OnboardingTask get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	OnboardingTask entity = service.getOnboardingTask( new OnboardingTaskFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded OnboardingTask with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all OnboardingTask business objects
     * @return		List<OnboardingTask>
     */
    @GetMapping("/")
    public List<OnboardingTask> getAll() {
    	List<OnboardingTask> onboardingTaskList = null;

		onboardingTaskList = service.getAllOnboardingTask();
		LOGGER.info( "successfully loaded all OnboardingTasks" );

        return onboardingTaskList;
                            
    }

	/**
	 * Handles loading all Employee} business objects
	 * @return		List<OnboardingTask>

    @GetMapping("/Employee")
    public List<OnboardingTask> Employee(UUID parentId) {
		List<OnboardingTask> onboardingTaskList = load(parentId).getEmployee;
		return onboardingTaskList;
	}
	 */
    /**
     * save Employee on OnboardingTask
     * @param		command AssignEmployeeToOnboardingTaskCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToOnboardingTaskCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on OnboardingTask
     * @param		 command UnAssignEmployeeFromOnboardingTaskCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromOnboardingTaskCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all AssignedTo} business objects
	 * @return		List<OnboardingTask>

    @GetMapping("/AssignedTo")
    public List<OnboardingTask> AssignedTo(UUID parentId) {
		List<OnboardingTask> onboardingTaskList = load(parentId).getAssignedTo;
		return onboardingTaskList;
	}
	 */
    /**
     * save AssignedTo on OnboardingTask
     * @param		command AssignAssignedToToOnboardingTaskCommand
     */     
	@PutMapping("/assignAssignedTo")
	public void assignAssignedTo( @RequestBody AssignAssignedToToOnboardingTaskCommand command ) {
		service.assignAssignedTo( command );
		LOGGER.info( "Successfully assigned AssignedTo with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign AssignedTo on OnboardingTask
     * @param		 command UnAssignAssignedToFromOnboardingTaskCommand
     */     
	@PutMapping("/unassignAssignedTo")
	public void unAssignAssignedTo( @RequestBody(required=true)  UnAssignAssignedToFromOnboardingTaskCommand command ) {
		service.unAssignAssignedTo( command );
		LOGGER.info( "Successfully unassigned AssignedTo with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all RelatedOffer} business objects
	 * @return		List<OnboardingTask>

    @GetMapping("/RelatedOffer")
    public List<OnboardingTask> RelatedOffer(UUID parentId) {
		List<OnboardingTask> onboardingTaskList = load(parentId).getRelatedOffer;
		return onboardingTaskList;
	}
	 */
    /**
     * save RelatedOffer on OnboardingTask
     * @param		command AssignRelatedOfferToOnboardingTaskCommand
     */     
	@PutMapping("/assignRelatedOffer")
	public void assignRelatedOffer( @RequestBody AssignRelatedOfferToOnboardingTaskCommand command ) {
		service.assignRelatedOffer( command );
		LOGGER.info( "Successfully assigned RelatedOffer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign RelatedOffer on OnboardingTask
     * @param		 command UnAssignRelatedOfferFromOnboardingTaskCommand
     */     
	@PutMapping("/unassignRelatedOffer")
	public void unAssignRelatedOffer( @RequestBody(required=true)  UnAssignRelatedOfferFromOnboardingTaskCommand command ) {
		service.unAssignRelatedOffer( command );
		LOGGER.info( "Successfully unassigned RelatedOffer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Dependencies} business objects
	 * @return		List<OnboardingTask>

    @GetMapping("/Dependencies")
    public List<OnboardingTask> Dependencies(UUID parentId) {
		List<OnboardingTask> onboardingTaskList = load(parentId).getDependencies;
		return onboardingTaskList;
	}

    /**
     * save Dependencies on OnboardingTask
     * @param		command AssignDependenciesToOnboardingTaskCommand
     */     
	@PutMapping("/addToDependencies")
	public void addToDependencies( @RequestBody(required=true) AssignDependenciesToOnboardingTaskCommand command ) {
		service.addToDependencies( command );
		LOGGER.info( "Successfully added Dependencies with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Dependencies on OnboardingTask
     * @param		command RemoveDependenciesFromOnboardingTaskCommand
     */     	
	@PutMapping("/removeFromDependencies")
	public void removeFromDependencies( 	@RequestBody(required=true) RemoveDependenciesFromOnboardingTaskCommand command )
	{		
		service.removeFromDependencies( command );
		LOGGER.info( "Successfully removed Dependencies with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected OnboardingTask onboardingTask = null;
	protected OnboardingTaskService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(OnboardingTaskRestController.class.getName());
    
}
