
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PayrollRunRestController as REST API
 *
 * <p>Exposes REST endpoints for the PayrollRun entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PayrollRunService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePayrollRunCommand</li>
 *      <li></li>UpdatePayrollRunCommand</li>
 *      <liDeletePayrollRunCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PayrollRun")
public class PayrollRunRestController extends BaseSpringRestController {

	public PayrollRunRestController( PayrollRunService service ) {
		this.service = service;
	}
    /**
     * Handles create a PayrollRun.  if not key provided, calls create, otherwise calls save
     * @param		PayrollRun	payrollRun
     * @return		PayrollRun 
     */
	@PostMapping("/create")
    public PayrollRun create( @RequestBody(required=true) CreatePayrollRunCommand command ) {
    	PayrollRun entity = null;

		entity = service.createPayrollRun( command );
		LOGGER.info( "Successfully created PayrollRun with Id " + entity.getPayrollRunId()  );

		return entity;
    }

    /**
     * Handles updating a PayrollRun.  if no key provided, calls create, otherwise calls save
     * @param		PayrollRun payrollRun
     * @return		PayrollRun
     */
	@PutMapping("/update")
    public PayrollRun update( @RequestBody(required=true) UpdatePayrollRunCommand command ) {
		PayrollRun entity = null;

		entity = service.updatePayrollRun(command);
		LOGGER.info( "Successfully updated PayrollRun with Id " + command.getPayrollRunId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PayrollRun entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePayrollRunCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PayrollRun with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a PayrollRun using a UUID
     * @param		UUID uuid 
     * @return		PayrollRun
     */    
    @GetMapping("/get")
    public PayrollRun get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	PayrollRun entity = service.getPayrollRun( new PayrollRunFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded PayrollRun with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all PayrollRun business objects
     * @return		List<PayrollRun>
     */
    @GetMapping("/")
    public List<PayrollRun> getAll() {
    	List<PayrollRun> payrollRunList = null;

		payrollRunList = service.getAllPayrollRun();
		LOGGER.info( "successfully loaded all PayrollRuns" );

        return payrollRunList;
                            
    }

	/**
	 * Handles loading all PayrollCalendar} business objects
	 * @return		List<PayrollRun>

    @GetMapping("/PayrollCalendar")
    public List<PayrollRun> PayrollCalendar(UUID parentId) {
		List<PayrollRun> payrollRunList = load(parentId).getPayrollCalendar;
		return payrollRunList;
	}
	 */
    /**
     * save PayrollCalendar on PayrollRun
     * @param		command AssignPayrollCalendarToPayrollRunCommand
     */     
	@PutMapping("/assignPayrollCalendar")
	public void assignPayrollCalendar( @RequestBody AssignPayrollCalendarToPayrollRunCommand command ) {
		service.assignPayrollCalendar( command );
		LOGGER.info( "Successfully assigned PayrollCalendar with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign PayrollCalendar on PayrollRun
     * @param		 command UnAssignPayrollCalendarFromPayrollRunCommand
     */     
	@PutMapping("/unassignPayrollCalendar")
	public void unAssignPayrollCalendar( @RequestBody(required=true)  UnAssignPayrollCalendarFromPayrollRunCommand command ) {
		service.unAssignPayrollCalendar( command );
		LOGGER.info( "Successfully unassigned PayrollCalendar with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all PayrollItems} business objects
	 * @return		List<PayrollRun>

    @GetMapping("/PayrollItems")
    public List<PayrollRun> PayrollItems(UUID parentId) {
		List<PayrollRun> payrollRunList = load(parentId).getPayrollItems;
		return payrollRunList;
	}

    /**
     * save PayrollItems on PayrollRun
     * @param		command AssignPayrollItemsToPayrollRunCommand
     */     
	@PutMapping("/addToPayrollItems")
	public void addToPayrollItems( @RequestBody(required=true) AssignPayrollItemsToPayrollRunCommand command ) {
		service.addToPayrollItems( command );
		LOGGER.info( "Successfully added PayrollItems with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove PayrollItems on PayrollRun
     * @param		command RemovePayrollItemsFromPayrollRunCommand
     */     	
	@PutMapping("/removeFromPayrollItems")
	public void removeFromPayrollItems( 	@RequestBody(required=true) RemovePayrollItemsFromPayrollRunCommand command )
	{		
		service.removeFromPayrollItems( command );
		LOGGER.info( "Successfully removed PayrollItems with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected PayrollRun payrollRun = null;
	protected PayrollRunService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PayrollRunRestController.class.getName());
    
}
