
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PerformanceCycleRestController as REST API
 *
 * <p>Exposes REST endpoints for the PerformanceCycle entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PerformanceCycleService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePerformanceCycleCommand</li>
 *      <li></li>UpdatePerformanceCycleCommand</li>
 *      <liDeletePerformanceCycleCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PerformanceCycle")
public class PerformanceCycleRestController extends BaseSpringRestController {

	public PerformanceCycleRestController( PerformanceCycleService service ) {
		this.service = service;
	}
    /**
     * Handles create a PerformanceCycle.  if not key provided, calls create, otherwise calls save
     * @param		PerformanceCycle	performanceCycle
     * @return		PerformanceCycle 
     */
	@PostMapping("/create")
    public PerformanceCycle create( @RequestBody(required=true) CreatePerformanceCycleCommand command ) {
    	PerformanceCycle entity = null;

		entity = service.createPerformanceCycle( command );
		LOGGER.info( "Successfully created PerformanceCycle with Id " + entity.getPerformanceCycleId()  );

		return entity;
    }

    /**
     * Handles updating a PerformanceCycle.  if no key provided, calls create, otherwise calls save
     * @param		PerformanceCycle performanceCycle
     * @return		PerformanceCycle
     */
	@PutMapping("/update")
    public PerformanceCycle update( @RequestBody(required=true) UpdatePerformanceCycleCommand command ) {
		PerformanceCycle entity = null;

		entity = service.updatePerformanceCycle(command);
		LOGGER.info( "Successfully updated PerformanceCycle with Id " + command.getPerformanceCycleId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PerformanceCycle entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePerformanceCycleCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PerformanceCycle with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a PerformanceCycle using a UUID
     * @param		UUID uuid 
     * @return		PerformanceCycle
     */    
    @GetMapping("/get")
    public PerformanceCycle get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	PerformanceCycle entity = service.getPerformanceCycle( new PerformanceCycleFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded PerformanceCycle with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all PerformanceCycle business objects
     * @return		List<PerformanceCycle>
     */
    @GetMapping("/")
    public List<PerformanceCycle> getAll() {
    	List<PerformanceCycle> performanceCycleList = null;

		performanceCycleList = service.getAllPerformanceCycle();
		LOGGER.info( "successfully loaded all PerformanceCycles" );

        return performanceCycleList;
                            
    }

	/**
	 * Handles loading all Organization} business objects
	 * @return		List<PerformanceCycle>

    @GetMapping("/Organization")
    public List<PerformanceCycle> Organization(UUID parentId) {
		List<PerformanceCycle> performanceCycleList = load(parentId).getOrganization;
		return performanceCycleList;
	}
	 */
    /**
     * save Organization on PerformanceCycle
     * @param		command AssignOrganizationToPerformanceCycleCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToPerformanceCycleCommand command ) {
		service.assignOrganization( command );
		LOGGER.info( "Successfully assigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Organization on PerformanceCycle
     * @param		 command UnAssignOrganizationFromPerformanceCycleCommand
     */     
	@PutMapping("/unassignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromPerformanceCycleCommand command ) {
		service.unAssignOrganization( command );
		LOGGER.info( "Successfully unassigned Organization with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Reviews} business objects
	 * @return		List<PerformanceCycle>

    @GetMapping("/Reviews")
    public List<PerformanceCycle> Reviews(UUID parentId) {
		List<PerformanceCycle> performanceCycleList = load(parentId).getReviews;
		return performanceCycleList;
	}

    /**
     * save Reviews on PerformanceCycle
     * @param		command AssignReviewsToPerformanceCycleCommand
     */     
	@PutMapping("/addToReviews")
	public void addToReviews( @RequestBody(required=true) AssignReviewsToPerformanceCycleCommand command ) {
		service.addToReviews( command );
		LOGGER.info( "Successfully added Reviews with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Reviews on PerformanceCycle
     * @param		command RemoveReviewsFromPerformanceCycleCommand
     */     	
	@PutMapping("/removeFromReviews")
	public void removeFromReviews( 	@RequestBody(required=true) RemoveReviewsFromPerformanceCycleCommand command )
	{		
		service.removeFromReviews( command );
		LOGGER.info( "Successfully removed Reviews with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Goals} business objects
	 * @return		List<PerformanceCycle>

    @GetMapping("/Goals")
    public List<PerformanceCycle> Goals(UUID parentId) {
		List<PerformanceCycle> performanceCycleList = load(parentId).getGoals;
		return performanceCycleList;
	}

    /**
     * save Goals on PerformanceCycle
     * @param		command AssignGoalsToPerformanceCycleCommand
     */     
	@PutMapping("/addToGoals")
	public void addToGoals( @RequestBody(required=true) AssignGoalsToPerformanceCycleCommand command ) {
		service.addToGoals( command );
		LOGGER.info( "Successfully added Goals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Goals on PerformanceCycle
     * @param		command RemoveGoalsFromPerformanceCycleCommand
     */     	
	@PutMapping("/removeFromGoals")
	public void removeFromGoals( 	@RequestBody(required=true) RemoveGoalsFromPerformanceCycleCommand command )
	{		
		service.removeFromGoals( command );
		LOGGER.info( "Successfully removed Goals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected PerformanceCycle performanceCycle = null;
	protected PerformanceCycleService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PerformanceCycleRestController.class.getName());
    
}
