
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PositionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Position entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PositionService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePositionCommand</li>
 *      <li></li>UpdatePositionCommand</li>
 *      <liDeletePositionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Position")
public class PositionRestController extends BaseSpringRestController {

	public PositionRestController( PositionService service ) {
		this.service = service;
	}
    /**
     * Handles create a Position.  if not key provided, calls create, otherwise calls save
     * @param		Position	position
     * @return		Position 
     */
	@PostMapping("/create")
    public Position create( @RequestBody(required=true) CreatePositionCommand command ) {
    	Position entity = null;

		entity = service.createPosition( command );
		LOGGER.info( "Successfully created Position with Id " + entity.getPositionId()  );

		return entity;
    }

    /**
     * Handles updating a Position.  if no key provided, calls create, otherwise calls save
     * @param		Position position
     * @return		Position
     */
	@PutMapping("/update")
    public Position update( @RequestBody(required=true) UpdatePositionCommand command ) {
		Position entity = null;

		entity = service.updatePosition(command);
		LOGGER.info( "Successfully updated Position with Id " + command.getPositionId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Position entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePositionCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Position with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Position using a UUID
     * @param		UUID uuid 
     * @return		Position
     */    
    @GetMapping("/get")
    public Position get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Position entity = service.getPosition( new PositionFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Position with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Position business objects
     * @return		List<Position>
     */
    @GetMapping("/")
    public List<Position> getAll() {
    	List<Position> positionList = null;

		positionList = service.getAllPosition();
		LOGGER.info( "successfully loaded all Positions" );

        return positionList;
                            
    }

	/**
	 * Handles loading all Department} business objects
	 * @return		List<Position>

    @GetMapping("/Department")
    public List<Position> Department(UUID parentId) {
		List<Position> positionList = load(parentId).getDepartment;
		return positionList;
	}
	 */
    /**
     * save Department on Position
     * @param		command AssignDepartmentToPositionCommand
     */     
	@PutMapping("/assignDepartment")
	public void assignDepartment( @RequestBody AssignDepartmentToPositionCommand command ) {
		service.assignDepartment( command );
		LOGGER.info( "Successfully assigned Department with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Department on Position
     * @param		 command UnAssignDepartmentFromPositionCommand
     */     
	@PutMapping("/unassignDepartment")
	public void unAssignDepartment( @RequestBody(required=true)  UnAssignDepartmentFromPositionCommand command ) {
		service.unAssignDepartment( command );
		LOGGER.info( "Successfully unassigned Department with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all JobProfile} business objects
	 * @return		List<Position>

    @GetMapping("/JobProfile")
    public List<Position> JobProfile(UUID parentId) {
		List<Position> positionList = load(parentId).getJobProfile;
		return positionList;
	}
	 */
    /**
     * save JobProfile on Position
     * @param		command AssignJobProfileToPositionCommand
     */     
	@PutMapping("/assignJobProfile")
	public void assignJobProfile( @RequestBody AssignJobProfileToPositionCommand command ) {
		service.assignJobProfile( command );
		LOGGER.info( "Successfully assigned JobProfile with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign JobProfile on Position
     * @param		 command UnAssignJobProfileFromPositionCommand
     */     
	@PutMapping("/unassignJobProfile")
	public void unAssignJobProfile( @RequestBody(required=true)  UnAssignJobProfileFromPositionCommand command ) {
		service.unAssignJobProfile( command );
		LOGGER.info( "Successfully unassigned JobProfile with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all CostCenter} business objects
	 * @return		List<Position>

    @GetMapping("/CostCenter")
    public List<Position> CostCenter(UUID parentId) {
		List<Position> positionList = load(parentId).getCostCenter;
		return positionList;
	}
	 */
    /**
     * save CostCenter on Position
     * @param		command AssignCostCenterToPositionCommand
     */     
	@PutMapping("/assignCostCenter")
	public void assignCostCenter( @RequestBody AssignCostCenterToPositionCommand command ) {
		service.assignCostCenter( command );
		LOGGER.info( "Successfully assigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign CostCenter on Position
     * @param		 command UnAssignCostCenterFromPositionCommand
     */     
	@PutMapping("/unassignCostCenter")
	public void unAssignCostCenter( @RequestBody(required=true)  UnAssignCostCenterFromPositionCommand command ) {
		service.unAssignCostCenter( command );
		LOGGER.info( "Successfully unassigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Location} business objects
	 * @return		List<Position>

    @GetMapping("/Location")
    public List<Position> Location(UUID parentId) {
		List<Position> positionList = load(parentId).getLocation;
		return positionList;
	}
	 */
    /**
     * save Location on Position
     * @param		command AssignLocationToPositionCommand
     */     
	@PutMapping("/assignLocation")
	public void assignLocation( @RequestBody AssignLocationToPositionCommand command ) {
		service.assignLocation( command );
		LOGGER.info( "Successfully assigned Location with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Location on Position
     * @param		 command UnAssignLocationFromPositionCommand
     */     
	@PutMapping("/unassignLocation")
	public void unAssignLocation( @RequestBody(required=true)  UnAssignLocationFromPositionCommand command ) {
		service.unAssignLocation( command );
		LOGGER.info( "Successfully unassigned Location with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all ManagerPosition} business objects
	 * @return		List<Position>

    @GetMapping("/ManagerPosition")
    public List<Position> ManagerPosition(UUID parentId) {
		List<Position> positionList = load(parentId).getManagerPosition;
		return positionList;
	}
	 */
    /**
     * save ManagerPosition on Position
     * @param		command AssignManagerPositionToPositionCommand
     */     
	@PutMapping("/assignManagerPosition")
	public void assignManagerPosition( @RequestBody AssignManagerPositionToPositionCommand command ) {
		service.assignManagerPosition( command );
		LOGGER.info( "Successfully assigned ManagerPosition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ManagerPosition on Position
     * @param		 command UnAssignManagerPositionFromPositionCommand
     */     
	@PutMapping("/unassignManagerPosition")
	public void unAssignManagerPosition( @RequestBody(required=true)  UnAssignManagerPositionFromPositionCommand command ) {
		service.unAssignManagerPosition( command );
		LOGGER.info( "Successfully unassigned ManagerPosition with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all DirectReports} business objects
	 * @return		List<Position>

    @GetMapping("/DirectReports")
    public List<Position> DirectReports(UUID parentId) {
		List<Position> positionList = load(parentId).getDirectReports;
		return positionList;
	}

    /**
     * save DirectReports on Position
     * @param		command AssignDirectReportsToPositionCommand
     */     
	@PutMapping("/addToDirectReports")
	public void addToDirectReports( @RequestBody(required=true) AssignDirectReportsToPositionCommand command ) {
		service.addToDirectReports( command );
		LOGGER.info( "Successfully added DirectReports with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove DirectReports on Position
     * @param		command RemoveDirectReportsFromPositionCommand
     */     	
	@PutMapping("/removeFromDirectReports")
	public void removeFromDirectReports( 	@RequestBody(required=true) RemoveDirectReportsFromPositionCommand command )
	{		
		service.removeFromDirectReports( command );
		LOGGER.info( "Successfully removed DirectReports with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Assignments} business objects
	 * @return		List<Position>

    @GetMapping("/Assignments")
    public List<Position> Assignments(UUID parentId) {
		List<Position> positionList = load(parentId).getAssignments;
		return positionList;
	}

    /**
     * save Assignments on Position
     * @param		command AssignAssignmentsToPositionCommand
     */     
	@PutMapping("/addToAssignments")
	public void addToAssignments( @RequestBody(required=true) AssignAssignmentsToPositionCommand command ) {
		service.addToAssignments( command );
		LOGGER.info( "Successfully added Assignments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Assignments on Position
     * @param		command RemoveAssignmentsFromPositionCommand
     */     	
	@PutMapping("/removeFromAssignments")
	public void removeFromAssignments( 	@RequestBody(required=true) RemoveAssignmentsFromPositionCommand command )
	{		
		service.removeFromAssignments( command );
		LOGGER.info( "Successfully removed Assignments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Position position = null;
	protected PositionService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PositionRestController.class.getName());
    
}
