
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * SalaryComponentRestController as REST API
 *
 * <p>Exposes REST endpoints for the SalaryComponent entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	SalaryComponentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateSalaryComponentCommand</li>
 *      <li></li>UpdateSalaryComponentCommand</li>
 *      <liDeleteSalaryComponentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/SalaryComponent")
public class SalaryComponentRestController extends BaseSpringRestController {

	public SalaryComponentRestController( SalaryComponentService service ) {
		this.service = service;
	}
    /**
     * Handles create a SalaryComponent.  if not key provided, calls create, otherwise calls save
     * @param		SalaryComponent	salaryComponent
     * @return		SalaryComponent 
     */
	@PostMapping("/create")
    public SalaryComponent create( @RequestBody(required=true) CreateSalaryComponentCommand command ) {
    	SalaryComponent entity = null;

		entity = service.createSalaryComponent( command );
		LOGGER.info( "Successfully created SalaryComponent with Id " + entity.getSalaryComponentId()  );

		return entity;
    }

    /**
     * Handles updating a SalaryComponent.  if no key provided, calls create, otherwise calls save
     * @param		SalaryComponent salaryComponent
     * @return		SalaryComponent
     */
	@PutMapping("/update")
    public SalaryComponent update( @RequestBody(required=true) UpdateSalaryComponentCommand command ) {
		SalaryComponent entity = null;

		entity = service.updateSalaryComponent(command);
		LOGGER.info( "Successfully updated SalaryComponent with Id " + command.getSalaryComponentId()  );

		return entity;
	}
 
    /**
     * Handles deleting a SalaryComponent entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteSalaryComponentCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted SalaryComponent with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a SalaryComponent using a UUID
     * @param		UUID uuid 
     * @return		SalaryComponent
     */    
    @GetMapping("/get")
    public SalaryComponent get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	SalaryComponent entity = service.getSalaryComponent( new SalaryComponentFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded SalaryComponent with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all SalaryComponent business objects
     * @return		List<SalaryComponent>
     */
    @GetMapping("/")
    public List<SalaryComponent> getAll() {
    	List<SalaryComponent> salaryComponentList = null;

		salaryComponentList = service.getAllSalaryComponent();
		LOGGER.info( "successfully loaded all SalaryComponents" );

        return salaryComponentList;
                            
    }

	/**
	 * Handles loading all CompensationPackage} business objects
	 * @return		List<SalaryComponent>

    @GetMapping("/CompensationPackage")
    public List<SalaryComponent> CompensationPackage(UUID parentId) {
		List<SalaryComponent> salaryComponentList = load(parentId).getCompensationPackage;
		return salaryComponentList;
	}
	 */
    /**
     * save CompensationPackage on SalaryComponent
     * @param		command AssignCompensationPackageToSalaryComponentCommand
     */     
	@PutMapping("/assignCompensationPackage")
	public void assignCompensationPackage( @RequestBody AssignCompensationPackageToSalaryComponentCommand command ) {
		service.assignCompensationPackage( command );
		LOGGER.info( "Successfully assigned CompensationPackage with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign CompensationPackage on SalaryComponent
     * @param		 command UnAssignCompensationPackageFromSalaryComponentCommand
     */     
	@PutMapping("/unassignCompensationPackage")
	public void unAssignCompensationPackage( @RequestBody(required=true)  UnAssignCompensationPackageFromSalaryComponentCommand command ) {
		service.unAssignCompensationPackage( command );
		LOGGER.info( "Successfully unassigned CompensationPackage with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected SalaryComponent salaryComponent = null;
	protected SalaryComponentService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(SalaryComponentRestController.class.getName());
    
}
