
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ScreeningRestController as REST API
 *
 * <p>Exposes REST endpoints for the Screening entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ScreeningService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateScreeningCommand</li>
 *      <li></li>UpdateScreeningCommand</li>
 *      <liDeleteScreeningCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Screening")
public class ScreeningRestController extends BaseSpringRestController {

	public ScreeningRestController( ScreeningService service ) {
		this.service = service;
	}
    /**
     * Handles create a Screening.  if not key provided, calls create, otherwise calls save
     * @param		Screening	screening
     * @return		Screening 
     */
	@PostMapping("/create")
    public Screening create( @RequestBody(required=true) CreateScreeningCommand command ) {
    	Screening entity = null;

		entity = service.createScreening( command );
		LOGGER.info( "Successfully created Screening with Id " + entity.getScreeningId()  );

		return entity;
    }

    /**
     * Handles updating a Screening.  if no key provided, calls create, otherwise calls save
     * @param		Screening screening
     * @return		Screening
     */
	@PutMapping("/update")
    public Screening update( @RequestBody(required=true) UpdateScreeningCommand command ) {
		Screening entity = null;

		entity = service.updateScreening(command);
		LOGGER.info( "Successfully updated Screening with Id " + command.getScreeningId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Screening entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteScreeningCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Screening with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Screening using a UUID
     * @param		UUID uuid 
     * @return		Screening
     */    
    @GetMapping("/get")
    public Screening get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Screening entity = service.getScreening( new ScreeningFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Screening with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Screening business objects
     * @return		List<Screening>
     */
    @GetMapping("/")
    public List<Screening> getAll() {
    	List<Screening> screeningList = null;

		screeningList = service.getAllScreening();
		LOGGER.info( "successfully loaded all Screenings" );

        return screeningList;
                            
    }

	/**
	 * Handles loading all Application} business objects
	 * @return		List<Screening>

    @GetMapping("/Application")
    public List<Screening> Application(UUID parentId) {
		List<Screening> screeningList = load(parentId).getApplication;
		return screeningList;
	}
	 */
    /**
     * save Application on Screening
     * @param		command AssignApplicationToScreeningCommand
     */     
	@PutMapping("/assignApplication")
	public void assignApplication( @RequestBody AssignApplicationToScreeningCommand command ) {
		service.assignApplication( command );
		LOGGER.info( "Successfully assigned Application with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Application on Screening
     * @param		 command UnAssignApplicationFromScreeningCommand
     */     
	@PutMapping("/unassignApplication")
	public void unAssignApplication( @RequestBody(required=true)  UnAssignApplicationFromScreeningCommand command ) {
		service.unAssignApplication( command );
		LOGGER.info( "Successfully unassigned Application with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Screening screening = null;
	protected ScreeningService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ScreeningRestController.class.getName());
    
}
