
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TimeEntryRestController as REST API
 *
 * <p>Exposes REST endpoints for the TimeEntry entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TimeEntryService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTimeEntryCommand</li>
 *      <li></li>UpdateTimeEntryCommand</li>
 *      <liDeleteTimeEntryCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/TimeEntry")
public class TimeEntryRestController extends BaseSpringRestController {

	public TimeEntryRestController( TimeEntryService service ) {
		this.service = service;
	}
    /**
     * Handles create a TimeEntry.  if not key provided, calls create, otherwise calls save
     * @param		TimeEntry	timeEntry
     * @return		TimeEntry 
     */
	@PostMapping("/create")
    public TimeEntry create( @RequestBody(required=true) CreateTimeEntryCommand command ) {
    	TimeEntry entity = null;

		entity = service.createTimeEntry( command );
		LOGGER.info( "Successfully created TimeEntry with Id " + entity.getTimeEntryId()  );

		return entity;
    }

    /**
     * Handles updating a TimeEntry.  if no key provided, calls create, otherwise calls save
     * @param		TimeEntry timeEntry
     * @return		TimeEntry
     */
	@PutMapping("/update")
    public TimeEntry update( @RequestBody(required=true) UpdateTimeEntryCommand command ) {
		TimeEntry entity = null;

		entity = service.updateTimeEntry(command);
		LOGGER.info( "Successfully updated TimeEntry with Id " + command.getTimeEntryId()  );

		return entity;
	}
 
    /**
     * Handles deleting a TimeEntry entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTimeEntryCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted TimeEntry with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a TimeEntry using a UUID
     * @param		UUID uuid 
     * @return		TimeEntry
     */    
    @GetMapping("/get")
    public TimeEntry get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	TimeEntry entity = service.getTimeEntry( new TimeEntryFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded TimeEntry with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all TimeEntry business objects
     * @return		List<TimeEntry>
     */
    @GetMapping("/")
    public List<TimeEntry> getAll() {
    	List<TimeEntry> timeEntryList = null;

		timeEntryList = service.getAllTimeEntry();
		LOGGER.info( "successfully loaded all TimeEntrys" );

        return timeEntryList;
                            
    }

	/**
	 * Handles loading all Timesheet} business objects
	 * @return		List<TimeEntry>

    @GetMapping("/Timesheet")
    public List<TimeEntry> Timesheet(UUID parentId) {
		List<TimeEntry> timeEntryList = load(parentId).getTimesheet;
		return timeEntryList;
	}
	 */
    /**
     * save Timesheet on TimeEntry
     * @param		command AssignTimesheetToTimeEntryCommand
     */     
	@PutMapping("/assignTimesheet")
	public void assignTimesheet( @RequestBody AssignTimesheetToTimeEntryCommand command ) {
		service.assignTimesheet( command );
		LOGGER.info( "Successfully assigned Timesheet with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Timesheet on TimeEntry
     * @param		 command UnAssignTimesheetFromTimeEntryCommand
     */     
	@PutMapping("/unassignTimesheet")
	public void unAssignTimesheet( @RequestBody(required=true)  UnAssignTimesheetFromTimeEntryCommand command ) {
		service.unAssignTimesheet( command );
		LOGGER.info( "Successfully unassigned Timesheet with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Employee} business objects
	 * @return		List<TimeEntry>

    @GetMapping("/Employee")
    public List<TimeEntry> Employee(UUID parentId) {
		List<TimeEntry> timeEntryList = load(parentId).getEmployee;
		return timeEntryList;
	}
	 */
    /**
     * save Employee on TimeEntry
     * @param		command AssignEmployeeToTimeEntryCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToTimeEntryCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on TimeEntry
     * @param		 command UnAssignEmployeeFromTimeEntryCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromTimeEntryCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all CostCenter} business objects
	 * @return		List<TimeEntry>

    @GetMapping("/CostCenter")
    public List<TimeEntry> CostCenter(UUID parentId) {
		List<TimeEntry> timeEntryList = load(parentId).getCostCenter;
		return timeEntryList;
	}
	 */
    /**
     * save CostCenter on TimeEntry
     * @param		command AssignCostCenterToTimeEntryCommand
     */     
	@PutMapping("/assignCostCenter")
	public void assignCostCenter( @RequestBody AssignCostCenterToTimeEntryCommand command ) {
		service.assignCostCenter( command );
		LOGGER.info( "Successfully assigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign CostCenter on TimeEntry
     * @param		 command UnAssignCostCenterFromTimeEntryCommand
     */     
	@PutMapping("/unassignCostCenter")
	public void unAssignCostCenter( @RequestBody(required=true)  UnAssignCostCenterFromTimeEntryCommand command ) {
		service.unAssignCostCenter( command );
		LOGGER.info( "Successfully unassigned CostCenter with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected TimeEntry timeEntry = null;
	protected TimeEntryService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(TimeEntryRestController.class.getName());
    
}
