
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TimesheetRestController as REST API
 *
 * <p>Exposes REST endpoints for the Timesheet entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TimesheetService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTimesheetCommand</li>
 *      <li></li>UpdateTimesheetCommand</li>
 *      <liDeleteTimesheetCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Timesheet")
public class TimesheetRestController extends BaseSpringRestController {

	public TimesheetRestController( TimesheetService service ) {
		this.service = service;
	}
    /**
     * Handles create a Timesheet.  if not key provided, calls create, otherwise calls save
     * @param		Timesheet	timesheet
     * @return		Timesheet 
     */
	@PostMapping("/create")
    public Timesheet create( @RequestBody(required=true) CreateTimesheetCommand command ) {
    	Timesheet entity = null;

		entity = service.createTimesheet( command );
		LOGGER.info( "Successfully created Timesheet with Id " + entity.getTimesheetId()  );

		return entity;
    }

    /**
     * Handles updating a Timesheet.  if no key provided, calls create, otherwise calls save
     * @param		Timesheet timesheet
     * @return		Timesheet
     */
	@PutMapping("/update")
    public Timesheet update( @RequestBody(required=true) UpdateTimesheetCommand command ) {
		Timesheet entity = null;

		entity = service.updateTimesheet(command);
		LOGGER.info( "Successfully updated Timesheet with Id " + command.getTimesheetId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Timesheet entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTimesheetCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Timesheet with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Timesheet using a UUID
     * @param		UUID uuid 
     * @return		Timesheet
     */    
    @GetMapping("/get")
    public Timesheet get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Timesheet entity = service.getTimesheet( new TimesheetFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Timesheet with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Timesheet business objects
     * @return		List<Timesheet>
     */
    @GetMapping("/")
    public List<Timesheet> getAll() {
    	List<Timesheet> timesheetList = null;

		timesheetList = service.getAllTimesheet();
		LOGGER.info( "successfully loaded all Timesheets" );

        return timesheetList;
                            
    }

	/**
	 * Handles loading all Employee} business objects
	 * @return		List<Timesheet>

    @GetMapping("/Employee")
    public List<Timesheet> Employee(UUID parentId) {
		List<Timesheet> timesheetList = load(parentId).getEmployee;
		return timesheetList;
	}
	 */
    /**
     * save Employee on Timesheet
     * @param		command AssignEmployeeToTimesheetCommand
     */     
	@PutMapping("/assignEmployee")
	public void assignEmployee( @RequestBody AssignEmployeeToTimesheetCommand command ) {
		service.assignEmployee( command );
		LOGGER.info( "Successfully assigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Employee on Timesheet
     * @param		 command UnAssignEmployeeFromTimesheetCommand
     */     
	@PutMapping("/unassignEmployee")
	public void unAssignEmployee( @RequestBody(required=true)  UnAssignEmployeeFromTimesheetCommand command ) {
		service.unAssignEmployee( command );
		LOGGER.info( "Successfully unassigned Employee with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all TimeEntries} business objects
	 * @return		List<Timesheet>

    @GetMapping("/TimeEntries")
    public List<Timesheet> TimeEntries(UUID parentId) {
		List<Timesheet> timesheetList = load(parentId).getTimeEntries;
		return timesheetList;
	}

    /**
     * save TimeEntries on Timesheet
     * @param		command AssignTimeEntriesToTimesheetCommand
     */     
	@PutMapping("/addToTimeEntries")
	public void addToTimeEntries( @RequestBody(required=true) AssignTimeEntriesToTimesheetCommand command ) {
		service.addToTimeEntries( command );
		LOGGER.info( "Successfully added TimeEntries with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove TimeEntries on Timesheet
     * @param		command RemoveTimeEntriesFromTimesheetCommand
     */     	
	@PutMapping("/removeFromTimeEntries")
	public void removeFromTimeEntries( 	@RequestBody(required=true) RemoveTimeEntriesFromTimesheetCommand command )
	{		
		service.removeFromTimeEntries( command );
		LOGGER.info( "Successfully removed TimeEntries with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Approvals} business objects
	 * @return		List<Timesheet>

    @GetMapping("/Approvals")
    public List<Timesheet> Approvals(UUID parentId) {
		List<Timesheet> timesheetList = load(parentId).getApprovals;
		return timesheetList;
	}

    /**
     * save Approvals on Timesheet
     * @param		command AssignApprovalsToTimesheetCommand
     */     
	@PutMapping("/addToApprovals")
	public void addToApprovals( @RequestBody(required=true) AssignApprovalsToTimesheetCommand command ) {
		service.addToApprovals( command );
		LOGGER.info( "Successfully added Approvals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Approvals on Timesheet
     * @param		command RemoveApprovalsFromTimesheetCommand
     */     	
	@PutMapping("/removeFromApprovals")
	public void removeFromApprovals( 	@RequestBody(required=true) RemoveApprovalsFromTimesheetCommand command )
	{		
		service.removeFromApprovals( command );
		LOGGER.info( "Successfully removed Approvals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Timesheet timesheet = null;
	protected TimesheetService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(TimesheetRestController.class.getName());
    
}
