/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Employee business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Employee related services in the case of a Employee business related service failing.</li>
 * <li>Exposes a simpler, uniform Employee interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Employee business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class EmployeeService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public EmployeeService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new EmployeeEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(EmployeeRepository.class) );
		this.validator		= applicationContext.getBean(EmployeeValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Employee
	 */
		public Employee createEmployee( CreateEmployeeCommand command ) {

		Employee entity = new Employee();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setEmployeeId( command.getEmployeeId() );
            entity.setEmployeeNumber( command.getEmployeeNumber() );
            entity.setName( command.getName() );
            entity.setWorkEmail( command.getWorkEmail() );
            entity.setWorkPhone( command.getWorkPhone() );
            entity.setDateOfHire( command.getDateOfHire() );
            entity.setNationalId( command.getNationalId() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Employee {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateEmployeeCommand
	 * @return		Employee
	 */
	public Employee updateEmployee( UpdateEmployeeCommand command ) {

		Employee entity = new Employee();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setEmployeeId( command.getEmployeeId() );
            entity.setEmployeeNumber( command.getEmployeeNumber() );
            entity.setName( command.getName() );
            entity.setWorkEmail( command.getWorkEmail() );
            entity.setWorkPhone( command.getWorkPhone() );
            entity.setDateOfHire( command.getDateOfHire() );
            entity.setNationalId( command.getNationalId() );
            entity.setManager( command.getManager() );
            entity.setDirectReports( command.getDirectReports() );
            entity.setDepartment( command.getDepartment() );
            entity.setPrimaryLocation( command.getPrimaryLocation() );
            entity.setCostCenter( command.getCostCenter() );
            entity.setEmploymentAssignments( command.getEmploymentAssignments() );
            entity.setContracts( command.getContracts() );
            entity.setBenefitEnrollments( command.getBenefitEnrollments() );
            entity.setTimesheets( command.getTimesheets() );
            entity.setLeaveRequests( command.getLeaveRequests() );
            entity.setPerformanceReviews( command.getPerformanceReviews() );
            entity.setTrainingEnrollments( command.getTrainingEnrollments() );
            entity.setWorkAuthorizations( command.getWorkAuthorizations() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Employee {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object.
	 * @param		command DeleteEmployeeCommand
	 */
	public void delete( DeleteEmployeeCommand command ) {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(command.getId());

		LOGGER.info( "done deleting of Employee id:{0} ", command.getId() );

	}

	/**
	 * Method to retrieve the Employee via EmployeeFetchOneSummary.
	 * @param 	summary EmployeeFetchOneSummary
	 * @return 	EmployeeFetchOneResponse
	 */
	public Employee getEmployee( EmployeeFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "EmployeeFetchOneSummary arg cannot be null" );

		Employee entity = null;
		UUID id = summary.getId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Employee using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Employees
	 *
	 * @return 	List<Employee>
	 */
    public List<Employee> getAllEmployee() {
		List<Employee> list = projector.findAll( new FindAllEmployeeQuery() );
		return list;
	}

	/**
	 * assign Manager on Employee
	 * @param		command AssignManagerToEmployeeCommand
	 */
	public void assignManager( AssignManagerToEmployeeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignManager(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign Manager on Employee
	 * @param		command UnAssignManagerFromEmployeeCommand
	 */
	public void unAssignManager( UnAssignManagerFromEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignManager(command.getParentId());
	}
	
	/**
	 * assign Department on Employee
	 * @param		command AssignDepartmentToEmployeeCommand
	 */
	public void assignDepartment( AssignDepartmentToEmployeeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignDepartment(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign Department on Employee
	 * @param		command UnAssignDepartmentFromEmployeeCommand
	 */
	public void unAssignDepartment( UnAssignDepartmentFromEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignDepartment(command.getParentId());
	}
	
	/**
	 * assign PrimaryLocation on Employee
	 * @param		command AssignPrimaryLocationToEmployeeCommand
	 */
	public void assignPrimaryLocation( AssignPrimaryLocationToEmployeeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignPrimaryLocation(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign PrimaryLocation on Employee
	 * @param		command UnAssignPrimaryLocationFromEmployeeCommand
	 */
	public void unAssignPrimaryLocation( UnAssignPrimaryLocationFromEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignPrimaryLocation(command.getParentId());
	}
	
	/**
	 * assign CostCenter on Employee
	 * @param		command AssignCostCenterToEmployeeCommand
	 */
	public void assignCostCenter( AssignCostCenterToEmployeeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignCostCenter(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign CostCenter on Employee
	 * @param		command UnAssignCostCenterFromEmployeeCommand
	 */
	public void unAssignCostCenter( UnAssignCostCenterFromEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignCostCenter(command.getParentId());
	}
	

	/**
	 * add Employee to DirectReports
	 * @param		command AssignDirectReportsToEmployeeCommand
	 */
	public void addToDirectReports( AssignDirectReportsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToDirectReports(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Employee from DirectReports
	 * @param		command RemoveDirectReportsFromEmployeeCommand
	 */
	public void removeFromDirectReports( RemoveDirectReportsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromDirectReports(command.getParentId(), command.getChildIds());
	}

	/**
	 * add EmploymentAssignment to EmploymentAssignments
	 * @param		command AssignEmploymentAssignmentsToEmployeeCommand
	 */
	public void addToEmploymentAssignments( AssignEmploymentAssignmentsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToEmploymentAssignments(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove EmploymentAssignment from EmploymentAssignments
	 * @param		command RemoveEmploymentAssignmentsFromEmployeeCommand
	 */
	public void removeFromEmploymentAssignments( RemoveEmploymentAssignmentsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromEmploymentAssignments(command.getParentId(), command.getChildIds());
	}

	/**
	 * add EmploymentContract to Contracts
	 * @param		command AssignContractsToEmployeeCommand
	 */
	public void addToContracts( AssignContractsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToContracts(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove EmploymentContract from Contracts
	 * @param		command RemoveContractsFromEmployeeCommand
	 */
	public void removeFromContracts( RemoveContractsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromContracts(command.getParentId(), command.getChildIds());
	}

	/**
	 * add BenefitEnrollment to BenefitEnrollments
	 * @param		command AssignBenefitEnrollmentsToEmployeeCommand
	 */
	public void addToBenefitEnrollments( AssignBenefitEnrollmentsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToBenefitEnrollments(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove BenefitEnrollment from BenefitEnrollments
	 * @param		command RemoveBenefitEnrollmentsFromEmployeeCommand
	 */
	public void removeFromBenefitEnrollments( RemoveBenefitEnrollmentsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromBenefitEnrollments(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Timesheet to Timesheets
	 * @param		command AssignTimesheetsToEmployeeCommand
	 */
	public void addToTimesheets( AssignTimesheetsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToTimesheets(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Timesheet from Timesheets
	 * @param		command RemoveTimesheetsFromEmployeeCommand
	 */
	public void removeFromTimesheets( RemoveTimesheetsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromTimesheets(command.getParentId(), command.getChildIds());
	}

	/**
	 * add LeaveRequest to LeaveRequests
	 * @param		command AssignLeaveRequestsToEmployeeCommand
	 */
	public void addToLeaveRequests( AssignLeaveRequestsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLeaveRequests(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove LeaveRequest from LeaveRequests
	 * @param		command RemoveLeaveRequestsFromEmployeeCommand
	 */
	public void removeFromLeaveRequests( RemoveLeaveRequestsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLeaveRequests(command.getParentId(), command.getChildIds());
	}

	/**
	 * add PerformanceReview to PerformanceReviews
	 * @param		command AssignPerformanceReviewsToEmployeeCommand
	 */
	public void addToPerformanceReviews( AssignPerformanceReviewsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPerformanceReviews(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove PerformanceReview from PerformanceReviews
	 * @param		command RemovePerformanceReviewsFromEmployeeCommand
	 */
	public void removeFromPerformanceReviews( RemovePerformanceReviewsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPerformanceReviews(command.getParentId(), command.getChildIds());
	}

	/**
	 * add TrainingEnrollment to TrainingEnrollments
	 * @param		command AssignTrainingEnrollmentsToEmployeeCommand
	 */
	public void addToTrainingEnrollments( AssignTrainingEnrollmentsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToTrainingEnrollments(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove TrainingEnrollment from TrainingEnrollments
	 * @param		command RemoveTrainingEnrollmentsFromEmployeeCommand
	 */
	public void removeFromTrainingEnrollments( RemoveTrainingEnrollmentsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromTrainingEnrollments(command.getParentId(), command.getChildIds());
	}

	/**
	 * add WorkAuthorization to WorkAuthorizations
	 * @param		command AssignWorkAuthorizationsToEmployeeCommand
	 */
	public void addToWorkAuthorizations( AssignWorkAuthorizationsToEmployeeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToWorkAuthorizations(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove WorkAuthorization from WorkAuthorizations
	 * @param		command RemoveWorkAuthorizationsFromEmployeeCommand
	 */
	public void removeFromWorkAuthorizations( RemoveWorkAuthorizationsFromEmployeeCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromWorkAuthorizations(command.getParentId(), command.getChildIds());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final EmployeeEntityProjector projector;
	private final EmployeeValidator validator;
	private Employee employee 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(EmployeeService.class);
}
