/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Position business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Position related services in the case of a Position business related service failing.</li>
 * <li>Exposes a simpler, uniform Position interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Position business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Human Resources Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core HR capabilities across organization design, workforce, compensation, benefits, time, payroll, performance, learning, and talent acquisition.</td></tr>
 *          <tr><td>industry</td><td>Human Resources</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class PositionService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public PositionService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new PositionEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(PositionRepository.class) );
		this.validator		= applicationContext.getBean(PositionValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Position
	 */
		public Position createPosition( CreatePositionCommand command ) {

		Position entity = new Position();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setPositionId( command.getPositionId() );
            entity.setPositionCode( command.getPositionCode() );
            entity.setFte( command.getFte() );
            entity.setStatus( command.getStatus() );
            entity.setWorkLocationType( command.getWorkLocationType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Position {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdatePositionCommand
	 * @return		Position
	 */
	public Position updatePosition( UpdatePositionCommand command ) {

		Position entity = new Position();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setPositionId( command.getPositionId() );
            entity.setPositionCode( command.getPositionCode() );
            entity.setFte( command.getFte() );
            entity.setDepartment( command.getDepartment() );
            entity.setJobProfile( command.getJobProfile() );
            entity.setCostCenter( command.getCostCenter() );
            entity.setLocation( command.getLocation() );
            entity.setManagerPosition( command.getManagerPosition() );
            entity.setDirectReports( command.getDirectReports() );
            entity.setAssignments( command.getAssignments() );
            entity.setStatus( command.getStatus() );
            entity.setWorkLocationType( command.getWorkLocationType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Position {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object.
	 * @param		command DeletePositionCommand
	 */
	public void delete( DeletePositionCommand command ) {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(command.getId());

		LOGGER.info( "done deleting of Position id:{0} ", command.getId() );

	}

	/**
	 * Method to retrieve the Position via PositionFetchOneSummary.
	 * @param 	summary PositionFetchOneSummary
	 * @return 	PositionFetchOneResponse
	 */
	public Position getPosition( PositionFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "PositionFetchOneSummary arg cannot be null" );

		Position entity = null;
		UUID id = summary.getId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Position using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Positions
	 *
	 * @return 	List<Position>
	 */
    public List<Position> getAllPosition() {
		List<Position> list = projector.findAll( new FindAllPositionQuery() );
		return list;
	}

	/**
	 * assign Department on Position
	 * @param		command AssignDepartmentToPositionCommand
	 */
	public void assignDepartment( AssignDepartmentToPositionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignDepartment(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign Department on Position
	 * @param		command UnAssignDepartmentFromPositionCommand
	 */
	public void unAssignDepartment( UnAssignDepartmentFromPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignDepartment(command.getParentId());
	}
	
	/**
	 * assign JobProfile on Position
	 * @param		command AssignJobProfileToPositionCommand
	 */
	public void assignJobProfile( AssignJobProfileToPositionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignJobProfile(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign JobProfile on Position
	 * @param		command UnAssignJobProfileFromPositionCommand
	 */
	public void unAssignJobProfile( UnAssignJobProfileFromPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignJobProfile(command.getParentId());
	}
	
	/**
	 * assign CostCenter on Position
	 * @param		command AssignCostCenterToPositionCommand
	 */
	public void assignCostCenter( AssignCostCenterToPositionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignCostCenter(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign CostCenter on Position
	 * @param		command UnAssignCostCenterFromPositionCommand
	 */
	public void unAssignCostCenter( UnAssignCostCenterFromPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignCostCenter(command.getParentId());
	}
	
	/**
	 * assign Location on Position
	 * @param		command AssignLocationToPositionCommand
	 */
	public void assignLocation( AssignLocationToPositionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignLocation(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign Location on Position
	 * @param		command UnAssignLocationFromPositionCommand
	 */
	public void unAssignLocation( UnAssignLocationFromPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignLocation(command.getParentId());
	}
	
	/**
	 * assign ManagerPosition on Position
	 * @param		command AssignManagerPositionToPositionCommand
	 */
	public void assignManagerPosition( AssignManagerPositionToPositionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignManagerPosition(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign ManagerPosition on Position
	 * @param		command UnAssignManagerPositionFromPositionCommand
	 */
	public void unAssignManagerPosition( UnAssignManagerPositionFromPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignManagerPosition(command.getParentId());
	}
	

	/**
	 * add Position to DirectReports
	 * @param		command AssignDirectReportsToPositionCommand
	 */
	public void addToDirectReports( AssignDirectReportsToPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToDirectReports(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Position from DirectReports
	 * @param		command RemoveDirectReportsFromPositionCommand
	 */
	public void removeFromDirectReports( RemoveDirectReportsFromPositionCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromDirectReports(command.getParentId(), command.getChildIds());
	}

	/**
	 * add EmploymentAssignment to Assignments
	 * @param		command AssignAssignmentsToPositionCommand
	 */
	public void addToAssignments( AssignAssignmentsToPositionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAssignments(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove EmploymentAssignment from Assignments
	 * @param		command RemoveAssignmentsFromPositionCommand
	 */
	public void removeFromAssignments( RemoveAssignmentsFromPositionCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAssignments(command.getParentId(), command.getChildIds());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final PositionEntityProjector projector;
	private final PositionValidator validator;
	private Position position 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(PositionService.class);
}
